export const special_requests = [
  {
    id: 1,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "asda",
    wine_vintage: 1,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "asdasd",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-10-30T21:28:00Z",
    status: "",
    user: 3,
  },
  {
    id: 2,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Dr",
    wine_vintage: 200,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "private_gifting",
    priority_level: "standard",
    notes: "Dd",
    delivery_options: "add_to_cellard_collection",
    preferred_delivery_date: null,
    status: "",
    user: 9,
  },
  {
    id: 3,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Hhh",
    wine_vintage: 1995,
    quantity: 0,
    quantity_type: "single bottle",
    purpose: "yacht_party",
    priority_level: "standard",
    notes: "Hh",
    delivery_options: "ship_to_home",
    preferred_delivery_date: null,
    status: "",
    user: 9,
  },
  {
    id: 4,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Sassicaia",
    wine_vintage: 1998,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "personal_celebration",
    priority_level: "ultra rare",
    notes: "Cjsjdjcdkdx",
    delivery_options: "add_to_cellard_collection",
    preferred_delivery_date: "2025-11-21T14:54:00Z",
    status: "",
    user: 8,
  },
  {
    id: 5,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Y",
    wine_vintage: 0,
    quantity: 200,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "Hjii",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-11T08:00:00Z",
    status: "",
    user: 3,
  },
  {
    id: 6,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/f0b4f954-1276-446d-8d6c-e65044c8e736.png",
    wine_name: "Yhh",
    wine_vintage: 200,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "urgent",
    notes: "Yhh",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-05T08:00:00Z",
    status: "",
    user: 3,
  },
  {
    id: 7,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Tt",
    wine_vintage: 33,
    quantity: 200,
    quantity_type: "single bottle",
    purpose: "yacht_party",
    priority_level: "standard",
    notes: "NA",
    delivery_options: "ship_to_home",
    preferred_delivery_date: null,
    status: "",
    user: 9,
  },
  {
    id: 8,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Test",
    wine_vintage: 22,
    quantity: 2,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "asdasd",
    delivery_options: "deliver_to_event",
    preferred_delivery_date: "2025-11-13T10:23:00Z",
    status: "",
    user: 9,
  },
  {
    id: 9,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Bartolo",
    wine_vintage: 0,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "NA",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-14T08:00:00Z",
    status: "",
    user: 9,
  },
  {
    id: 10,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/1f6435b0-cf0f-40e1-ba51-7fb0a3457ccd.jpeg",
    wine_name: "1",
    wine_vintage: 0,
    quantity: 2,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "NA",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-14T08:00:00Z",
    status: "",
    user: 9,
  },
  {
    id: 11,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/29d0115c-c817-4cb2-b259-70960a1a0a65.jpeg",
    wine_name: "2",
    wine_vintage: 0,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "Vbh",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-14T08:00:00Z",
    status: "",
    user: 9,
  },
  {
    id: 12,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Hd",
    wine_vintage: 1,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "NA",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-14T08:00:00Z",
    status: "",
    user: 3,
  },
  {
    id: 13,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/4b7ccf2d-d732-4f95-98d6-b6302402ef27.png",
    wine_name: "Test",
    wine_vintage: 0,
    quantity: 2,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "NA",
    delivery_options: "ship_to_home",
    preferred_delivery_date: null,
    status: "",
    user: 3,
  },
  {
    id: 14,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Hshs",
    wine_vintage: 1,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "NA",
    delivery_options: "ship_to_home",
    preferred_delivery_date: null,
    status: "",
    user: 9,
  },
  {
    id: 15,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/af0175c8-85bc-4b44-bce2-b704fdc7d2c3.png",
    wine_name: "Angelus",
    wine_vintage: 1984,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "private_gifting",
    priority_level: "standard",
    notes: "With flowers",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-29T13:00:00Z",
    status: "",
    user: 38,
  },
  {
    id: 16,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Tesf",
    wine_vintage: 0,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "Hhss",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-17T08:00:00Z",
    status: "",
    user: 3,
  },
  {
    id: 17,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/534e52cb-a9e8-4211-89cc-db3dc158caa9.jpeg",
    wine_name: "Sassicaia",
    wine_vintage: 1994,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "special_celebration",
    priority_level: "standard",
    notes: "Leave with neighbours",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-12-26T08:00:00Z",
    status: "",
    user: 4,
  },
  {
    id: 18,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/67ABE7DB-7347-493F-AC75-EFCEF176D6EE.jpg",
    wine_name: "Sassicaia",
    wine_vintage: 1984,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "special_celebration",
    priority_level: "urgent",
    notes: "Please call to arrange delivery",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-28T13:00:00Z",
    status: "",
    user: 9,
  },
  {
    id: 19,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/54170F63-F764-4608-BD0A-A9BDB9A184ED.jpg",
    wine_name: "Coffee",
    wine_vintage: 2025,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "special_celebration",
    priority_level: "standard",
    notes: "Right now",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-05T13:00:00Z",
    status: "",
    user: 8,
  },
  {
    id: 20,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/0DDB3C22-C1B1-4A38-B28E-798C1E2C4714.jpg",
    wine_name: "The George",
    wine_vintage: 1991,
    quantity: 2,
    quantity_type: "cases_6",
    purpose: "personal_celebration",
    priority_level: "urgent",
    notes: "I need it by the weekend",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-28T08:00:00Z",
    status: "",
    user: 88,
  },
  {
    id: 21,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Gg",
    wine_vintage: 200,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "Yh",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-27T08:00:00Z",
    status: "",
    user: 3,
  },
  {
    id: 22,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "asda",
    wine_vintage: 123,
    quantity: 2,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "asdasd",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-21T08:57:00Z",
    status: "",
    user: 3,
  },
  {
    id: 23,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Test",
    wine_vintage: 2000,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "Nsjs",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-29T08:00:00Z",
    status: "",
    user: 9,
  },
  {
    id: 24,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Gg",
    wine_vintage: 200,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "Hh",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-11-12T08:00:00Z",
    status: "",
    user: 9,
  },
  {
    id: 25,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Jsjs",
    wine_vintage: 2000,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "Jdjs",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-12-01T08:00:00Z",
    status: "",
    user: 3,
  },
  {
    id: 26,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Sassicaia",
    wine_vintage: 0,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "NA",
    delivery_options: "add_to_cellard_collection",
    preferred_delivery_date: null,
    status: "",
    user: 8,
  },
  {
    id: 27,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/https%3A/vintage-associates-django-development.s3.eu-west-2.amazonaws.com/media/default.png",
    wine_name: "Sass",
    wine_vintage: 0,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "other",
    priority_level: "standard",
    notes: "No",
    delivery_options: "ship_to_home",
    preferred_delivery_date: "2025-12-03T08:00:00Z",
    status: "",
    user: 88,
  },
  {
    id: 28,
    reference_image:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/2424BBD6-3646-4A5C-93AE-FDF1A35EBD87.jpg",
    wine_name: "Sassicaia",
    wine_vintage: 1984,
    quantity: 1,
    quantity_type: "single bottle",
    purpose: "wedding",
    priority_level: "standard",
    notes: "Urgent",
    delivery_options: "deliver_to_event",
    preferred_delivery_date: "2025-12-25T13:00:00Z",
    status: "",
    user: 4,
  },
];
