export const WineSpecialVol21 = {
  results: [
    {
      id: 1102,
      lwin11: "10826562008",
      name: "2008 Moët & Chandon Dom Pérignon",
      vintage: 2008,
      release_price: "70",
      wine: 21,
      rp_score: "96",
      rp_released: "Aug 31, 2022",
      rp_tasting_notes:
        "Unquestionably the finest Dom Pérignon of the decade, the 2008 Dom Pérignon is drinking brilliantly today, wafting from the glass with notes of citrus oil, ripe orchard fruit, peach, buttered toast, pastry cream, iodine and smoky reduction. Full-bodied, rich and fleshy, it's vinous and layered, with a deep core of sweet fruit, racy acids and a long, saline finish. The 2008 is aging very gracefully.",
      rp_reviewer: "William Kelley",
      holding_years: "0.00",
      liv_ex_value: "1595.00",
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2020 - 2040",
      market_value: "350.00",
      tags: "NA",
      processed_case: 1,
      bottle_size: "1500",
      oldest_vintage: 2015,
      mean: "77.56",
      median: "77.56",
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [6],
    },
  ],
  wine_details: {
    id: 21,
    lwin7: "1082656",
    name: "Dom Perignon",
    fromm: "Champagne",
    red_wine: "Sparkling Wine – Complex and Traditional",
    grapes: "Champagne Blend",
    pair_with: "Shellfish, Crab and Lobster",
    region_of_appellation: "NA",
    alcohol_abv: "12 - 12.5%",
    sweetness: "Dry",
    blend: "NA",
    ownership: "LVMH Moët Hennessy Louis Vuitton",
    closure_type: "Cork",
    grape_variety:
      "The Champagne Blend traditionally combines Pinot Noir, Chardonnay, and Pinot Meunier, creating balanced sparkling wines. Pinot Noir adds structure and red fruit notes, Chardonnay brings elegance and aging potential, and Meunier contributes bright, fruity flavors. This blend thrives in cool climates like Champagne, California, and Tasmania. Outside Champagne, Pinot Meunier is less common. Popular food pairings include smoked salmon terrine, pork and prawn dumplings, and fried chicken with chili mayo, complementing the wine's crisp, vibrant profile.",
    region:
      'Champagne Brut is a dry, sparkling wine from France\'s Champagne region. It can be white or rosé and is typically made from the classic blend of Chardonnay, Pinot Noir, and Pinot Meunier, though it may also include lesser-known varieties like Pinot Blanc, Pinot Gris, Petit Meslier, and Arbane. The term "Brut" means "raw," indicating minimal added sugar (dosage) during production. By law, Brut Champagne contains less than 15g/L of sugar. Drier styles include Brut Nature (0–3g/L) and Extra Brut (0–6g/L). Introduced by Perrier-Jouët in  1846 for the British market, Brut has become the most popular Champagne style today, surpassing sweeter versions like Sec, Demi-Sec, and Doux.',
    winery:
      "Dom Pérignon, owned by Moët & Chandon under LVMH, is a prestigious Champagne brand named after Dom Pierre Pérignon, a 17th-century monk credited with advancing Champagne production. First released in 1937, Dom Pérignon is a vintage-only Champagne, blending Chardonnay and Pinot Noir from the best vineyards. Its maturation follows the Plénitude concept: Vintage (9 years), P2 (12–15 years), and P3 (25+ years). Dom Pérignon also produces rare Rosé vintages, reflecting elegance and aging potential.",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Dom_Perignon_2012.png",
    ],
    vintage: 2008,
    price: 350.0,
    annual_production: 25000,
    default_case_size: 6,
  },
};

export const WineSpecialVol42 = {
  results: [
    {
      id: 1821,
      lwin11: "10825422012",
      name: "2014 Louis Roederer, cristal (1x600cl)",
      vintage: 2012,
      release_price: "360",
      wine: 42,
      rp_score: "96",
      rp_released: "Feb 03, 2022",
      rp_tasting_notes:
        "The 2014 Cristal is a terrific effort that transcends the vintage. Bursting from the glass with expressive aromas of ripe citrus fruit, nectarine, white flowers, freshly baked bread and subtle hints of honeycomb, it's medium to full-bodied, vinous and fleshy, with an exuberant core of fruit that's girdled by racy acids, resulting in a wine that's simultaneously chiseled and demonstrative, meaning that early appeal doesn't come at the expense of the requisite tension for long-term cellaring. Concluding with a long, aromatic and intensely chalky finish, it is a brilliant Champagne that will offer a broad drinking window. This bottle was disgorged in June 2021 with seven grams per liter dosage.",
      rp_reviewer: "William Kelley",
      holding_years: "0",
      liv_ex_value: "0.00",
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2021 - 2050",
      market_value: "5000.00",
      tags: "NA",
      processed_case: 1,
      bottle_size: "6000",
      oldest_vintage: 2015,
      mean: "0.00",
      median: "0.00",
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [1, 6],
    },
  ],
  wine_details: {
    id: 42,
    lwin7: "1082542",
    name: "Louis Roederer, Cristal",
    fromm: "Champagne",
    red_wine: "Sparkling Wine – Complex and Traditional",
    grapes: "Chardonnay - Pinot Noir",
    pair_with: "Shellfish, Crab and Lobster",
    region_of_appellation: "NA",
    alcohol_abv: "12.5%",
    sweetness: "Dry",
    blend: "Pinot Noir & Chardonnay",
    ownership: "NA",
    closure_type: "Cork",
    grape_variety:
      "Chardonnay–Pinot Noir blends are widely used for sparkling wines globally, often crafted via the traditional méthode champenoise. Originating in France, this blend is also popular in Italy (Franciacorta) and New World regions like California, Australia (Tasmania), New Zealand (Marlborough), and South Africa (Stellenbosch). Chardonnay adds texture and nutty flavors, while Pinot Noir contributes red-fruit notes. Styles range from crisp and mineral to rich and toasty, with brut denoting dryness. Ideal pairings include bay scallops with garlic butter, oysters, and Camembert cheese.",
    region:
      'Champagne Brut is a dry, sparkling wine from France\'s Champagne region. It can be white or rosé and is typically made from the classic blend of Chardonnay, Pinot Noir, and Pinot Meunier, though it may also include lesser-known varieties like Pinot Blanc, Pinot Gris, Petit Meslier, and Arbane. The term "Brut" means "raw," indicating minimal added sugar (dosage) during production. By law, Brut Champagne contains less than 15g/L of sugar. Drier styles include Brut Nature (0–3g/L) and Extra Brut (0–6g/L). Introduced by Perrier-Jouët in 1846 for the British market, Brut has become the most popular Champagne style today, surpassing sweeter versions like Sec, Demi-Sec, and Doux.',
    winery:
      "Louis Roederer is a prestigious Champagne house in Reims, best known for its iconic Cristal cuvée. Founded in 1776, it gained prominence when Louis Roederer took over in 1833, focusing on international markets, notably becoming the Champagne of choice for Russia’s Tsar Alexander II. Cristal was created for the Tsar in a clear, flat-bottomed bottle for security reasons.Roederer owns 240 hectares of vineyards across the Montagne de Reims, Vallée de la Marne, and Côte des Blancs, with a commitment to biodynamic farming. Cristal, made from around 60% Pinot Noir and 40% Chardonnay, is produced in vintage and rosé styles, with some aging in oak. The portfolio includes non-vintage brut, vintage, rosé, Blanc de Blancs, and the Brut Nature collaboration with designer Philippe Starck. Roederer also crafts still wines under the Hommage à Camille label in the Coteaux Champenois appellation.",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Louis_Roederer_Cristal.png",
    ],
    vintage: 2012,
    price: 5000.0,
    annual_production: 30000,
    default_case_size: 6,
  },
};

export const WineSpecialVol53 = {
  results: [
    {
      id: 1103,
      lwin11: "13143772008",
      name: "2008 Taittinger Brut Blanc de Blancs Comtes de Champagne",
      vintage: 2008,
      release_price: "46",
      wine: 53,
      rp_score: "NA",
      rp_released: "Sep 17, 2020",
      rp_tasting_notes:
        "Taittinger's 2008 Brut Blanc de Blancs Comtes de Champagne is being released this year, and it will be worth a special effort to track down. I wrote in August 2019 that this is the finest Comtes de Champagne since the brilliant 2002, and this tasting confirmed that. Offering up a deep and complex bouquet of citrus oil, crisp orchard fruit, warm brioche, crushed chalk, blanched almonds and smoke, it's full-bodied and incisive, with excellent concentration, racy acids and a long, searingly chalky finish. While this is already immensely impressive out of the gates, this 2008 is clearly built for the long haul, and three decades' longevity won't be a challenge.",
      rp_reviewer: "William Kelley",
      holding_years: "0",
      liv_ex_value: "0.00",
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2021 - 2048",
      market_value: "2869.2",
      tags: "NA",
      processed_case: 1,
      bottle_size: "1500",
      oldest_vintage: 2021,
      mean: "136.24",
      median: "136.24",
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [6],
    },
  ],
  wine_details: {
    id: 53,
    lwin7: "1314377",
    name: "Taittinger, Comtes de Champagne Blanc de Blancs",
    fromm: "Champagne",
    red_wine: "Sparkling Wine – Complex and Traditional",
    grapes: "Chardonnay",
    pair_with: "Shellfish, Crab and Lobster",
    region_of_appellation: "NA",
    alcohol_abv: "12%",
    sweetness: "Dry",
    blend: "100% Chardonnay",
    ownership: "NA",
    closure_type: "Cork",
    grape_variety:
      "Chardonnay is a globally renowned white grape variety, originating from a cross between Gouais Blanc and Pinot (Noir or a mutation). Its name derives from the village of Chardonnay in Burgundy's Maconnais. Burgundy is Chardonnay’s spiritual home, producing styles from mineral Chablis to rich wines in Meursault and Puligny-Montrachet. Globally, key producers include France, USA, Australia, and Italy. Chardonnay thrives in both cool and warm climates, offering flavors from citrus and green apple to tropical fruits. It’s versatile in sparkling wines, notably Champagne Blanc de Blancs, and pairs well with seafood, poultry, and creamy dishes.",
    region:
      "The Côte des Blancs is the heart of Blanc de Blancs Champagne production, located south of Épernay. Its chalky soils are ideal for growing Chardonnay, which makes up 96% of plantings. Blanc de Blancs Champagnes, made exclusively from white grapes, are generally more citrusy, crisp, and dry, making them perfect for aperitifs and seafood pairings. Notable Grand Cru villages include Le Mesnil-sur-Oger, Cramant, Avize, and Oger. Prestigious examples are Salon and Krug Clos du Mesnil, known for their elegance and aging potential.",
    winery:
      "Taittinger is a prestigious Champagne house based in Reims, renowned for its Chardonnay-dominant cuvées, especially the Comtes de Champagne Blanc de Blancs. Founded in 1932 by Pierre Taittinger, the house owns 290 hectares of vineyards, primarily planted with Pinot Noir, Chardonnay, and some Pinot Meunier. The Brut Reserve NV features a fresh, delicate style with 40% Chardonnay. The flagship Comtes de Champagne ages for at least 10 years in historic chalk cellars. Taittinger also produces a Comtes de Champagne Rosé, blending Pinot Noir and Chardonnay.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Taittinger.png"],
    vintage: 2008,
    price: 2869.2,
    annual_production: 12000,
    default_case_size: 6,
  },
};

export const WineSpecialVol54 = {
  results: [
    {
      id: 1096,
      lwin11: "10953912021",
      name: "2021 Marchesi Antinori Tignanello",
      vintage: 2021,
      release_price: "21",
      wine: 54,
      rp_score: "98",
      rp_released: "Mar 21, 2021",
      rp_tasting_notes:
        "First made in 1971, this legendary Italian wine now celebrates its 50th birthday. Happy Birthday, Tignanello! The Marchesi Antinori 2021 Tignanello (made with 79% Sangiovese, 13% Cabernet Sauvignon and 8% Cabernet Franc) pulls on all the heartstrings. To be released in May, the wine shows a quintessentially pretty taste profile with tart fruit flavors, redcurrant, tea leaf, heritage rose, crushed white pepper, licorice, nutmeg, clove and chopped mint. It opens slowly to reveal more richness and exuberance with time, becoming downright voluptuous and heady a short while later. The through line, however, remains the bright freshness and minerality of Sangiovese. Compared to the 2018 vintage (which I also loved), this vintage has more overall fruit weight and volume.",
      rp_reviewer: "Monica Larner",
      holding_years: "123",
      liv_ex_value: "0.00",
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2025 - 2048",
      market_value: "2250.0",
      tags: "red, French, Bordeaux",
      processed_case: 1,
      bottle_size: "3000",
      oldest_vintage: 2022,
      mean: "648.64",
      median: "631.00",
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [1, 6],
    },
    {
      id: 1094,
      lwin11: "10953912021",
      name: "2021 Marchesi Antinori Tignanello",
      vintage: 2021,
      release_price: "-1",
      wine: 54,
      rp_score: "98",
      rp_released: "Mar 21, 2021",
      rp_tasting_notes:
        "First made in 1971, this legendary Italian wine now celebrates its 50th birthday. Happy Birthday, Tignanello! The Marchesi Antinori 2021 Tignanello (made with 79% Sangiovese, 13% Cabernet Sauvignon and 8% Cabernet Franc) pulls on all the heartstrings. To be released in May, the wine shows a quintessentially pretty taste profile with tart fruit flavors, redcurrant, tea leaf, heritage rose, crushed white pepper, licorice, nutmeg, clove and chopped mint. It opens slowly to reveal more richness and exuberance with time, becoming downright voluptuous and heady a short while later. The through line, however, remains the bright freshness and minerality of Sangiovese. Compared to the 2018 vintage (which I also loved), this vintage has more overall fruit weight and volume.",
      rp_reviewer: "Monica Larner",
      holding_years: "0",
      liv_ex_value: "0.00",
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2025 - 2048",
      market_value: "215.00",
      tags: "6",
      processed_case: 1,
      bottle_size: "1500",
      oldest_vintage: 2022,
      mean: "648.64",
      median: "631.00",
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [1, 6],
    },
  ],
  wine_details: {
    id: 54,
    lwin7: "1095391",
    name: "Tignanello, Toscana",
    fromm: "Italy",
    red_wine: "Red Wine – Bold and Structured",
    grapes: "Cabernet - Sangiovese",
    pair_with: "Beef and Venison",
    region_of_appellation: "NA",
    alcohol_abv: "14%",
    sweetness: "Dry",
    blend: "Sangiovese, Cabernet Sauvignon & Cabernet Franc",
    ownership: "NA",
    closure_type: "Cork",
    grape_variety:
      "In the 1960s and 1970s, Tuscan producers began blending Sangiovese with Cabernet Sauvignon and Cabernet Franc, creating Italy's iconic Super Tuscans. These wines, once labeled as Vino da Tavola, led to the creation of the IGT classification and the Bolgheri DOC in 1994. The blend combines Sangiovese’s cherry and berry flavors with Cabernet’s structure and depth. Popular globally, especially in California, it pairs well with lasagna Bolognese, beef steaks, slow-roasted pork, and mushroom risotto.",
    region:
      "The Indicazione Geografica Tipica (IGT) classification in Tuscany allows winemakers flexibility beyond the stricter DOCG and DOC rules, covering diverse styles from dry whites to sweet reds and sparkling rosés. Introduced in 1992, IGT aimed to legitimize high-quality wines, notably Super Tuscans, which previously bore the low-ranking Vino da Tavola label. Predominantly made from Sangiovese, along with Cabernet Sauvignon, Merlot, and Cabernet Franc, IGT wines now span 13,388 hectares with annual production around 65 million liters, driving Tuscany’s modern wine evolution.",
    winery:
      "Tignanello, a Super Tuscan red wine from Marchesi Antinori, is a blend of Sangiovese, Cabernet Sauvignon and Cabernet Franc, known for its rich complex flavours and elegant structure, and is considered an innovative pioneer of modern italian top wines. Antinori is a prestigious Tuscan wine company and one of Italy's largest producers, with a history dating back to the 14th Century. Known for pioneering innovation in winemaking, Antinori produces around 20 million bottles annually across 150 labels. Its flagship wines include Tignanello, the first to blend Sangiovese with Cabernet Sauvignon and Cabernet Franc, and Solaia, a bold Bordeaux-style blend. Antinori also owns estates like Badia a Passignano, Pian delle Vigne in Montalcino, and Castello della Sala in Umbria.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Tignanello.png"],
    vintage: 2021,
    price: 2250.0,
    annual_production: 25000,
    default_case_size: 6,
  },
};
