import type { Metadata } from "next";
import { Poppins, Fleur_De_Leah } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { Toaster } from "@/components/ui/sonner";
import "flag-icons/css/flag-icons.min.css";
import { CartProvider } from "@/context/CartContext";
import { PortfolioProvider } from "@/context/PortfolioContext";
import { CartSummaryProvider } from "@/context/CartSummary";
import { WineCellarProvider } from "@/context/WineCellarContext";
import { SubAccountProvider } from "@/context/SubAccountContext";
import { RareProvider } from "@/context/RareContext";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const fleur = Fleur_De_Leah({
  variable: "--font-fleur-san",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${fleur.variable} antialiased bg-primary-gray-600`}
      >
        <UserProvider>
          <CartProvider>
            <CartSummaryProvider>
              <PortfolioProvider>
                <SubAccountProvider>
                  <RareProvider>
                    <WineCellarProvider>{children}</WineCellarProvider>
                  </RareProvider>
                </SubAccountProvider>
              </PortfolioProvider>
            </CartSummaryProvider>
          </CartProvider>
        </UserProvider>
        <Toaster></Toaster>
      </body>
    </html>
  );
}
