import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import { Toaster } from "@/components/ui/sonner";
import "flag-icons/css/flag-icons.min.css";
import { CartProvider } from "@/context/CartContext";
import { PortfolioProvider } from "@/context/PortfolioContext";
import { CartSummaryProvider } from "@/context/CartSummary";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-primary-gray-600`}>
        <UserProvider>
          <CartProvider>
            <CartSummaryProvider>
              <PortfolioProvider>{children}</PortfolioProvider>
            </CartSummaryProvider>
          </CartProvider>
        </UserProvider>
        <Toaster></Toaster>
      </body>
    </html>
  );
}
