import { uuidv4 } from "zod";
import { CartItemT, PortfolioT } from "./types";

export const portfolioId = uuidv4();

export const portfolio_default: CartItemT[] = [
  {
    id: "6df65967-efcf-4227-9cb8-5b8688625bb2",
    case_size: 6,
    location: "portfolio",
    quantity: 1,
    stock_wine_vintage: {
      id: 735,
      lwin11: "11222002003",
      name: "2003 Harlan Estate",
      vintage: 2003,
      release_price: "240",
      wine: 38,
      rp_score: "98+",
      rp_released: "Jun 28, 2013",
      rp_tasting_notes:
        "One of the most backward yet promising wines of the vintage is the 2003 Harlan Estate. Its dense opaque plum/purple color is accompanied by a sumptuous bouquet of graphite, camphor, creme de cassis, smoky barbecue wood and a hint of forest floor. Similar flavors hit the mouth with full-bodied splendor, a multidimensional mouthfeel and texture, and the sensational finish lasts more than 45 seconds. Some tannins are still present, and this wine seems much younger than expected at ten years of age, so give it 4-5 more years of bottle age and consume it over the following 20-25 years. One of the most stunningly beautiful vineyards in all of Napa Valley, Harlan Estate is located in the foothills of the Mayacamas Mountains overlooking the Oakville Corridor. Harlan has been making world-class, first growth quality wines since the debut vintages of 1990 and 1991. Virtually nothing has been changed by winemaker Bob Levy, owner Bill Harlan and globe-trotting consultant Michel Rolland. The wine is largely all Cabernet Sauvignon and the production from the 40-acre vineyard is usually under 2,000 cases. The vineyard has a surprising composition of 70% Cabernet Sauvignon, 20% Merlot, 8% Cabernet Franc and 2% Petit Verdot. Most blends lean heavily on the Cabernet Sauvignon with slightly more Cabernet Franc being utilized over recent vintages. Following the great 2001 and 2002 vintages, 2003 is the type of vintage that has a tendency to be forgotten, but the two 2003s prove that the site’s great pedigree is never easy to dismiss. Tel. (707) 944-1441",
      rp_reviewer: "Robert M. Parker, Jr.",
      holding_years: "0",
      liv_ex_value: 0,
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2017 - 2042",
      market_value: 5128.0,
      tags: "NA",
      processed_case: 6,
      bottle_size: "0750",
      oldest_vintage: 2021,
      mean: 5254.35,
      median: 5139.0,
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [6],
      is_unavailable: false,
      get_notified: false,
      investment_id: 0,
      case_size: 0,
      quantity: 0,
      is_owner: false,
    },
    user_investment_wine_vintage: null,
    short_description: "",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/HarlanEstate.png"],
    is_special_volumes: false,
    basket: null,
    basket_items: [],
    is_available: true,
    photo_request: false,
    wine_name: "2003 Harlan Estate",
    fromm: "California",
    purchase_date: "2025-01-06",
    purchase_price: 30768,
    status: "Buy Request",
    sub_account: {
      id: "1",
      first_name: "Rin",
      last_name: "Vie",
      relationship: "",
      image: "/profile.jpg",
      birth_date: "2000-29-01",
    },
    bottle_size: "0750",
    vintage: 2003,
    alcohol_abv: "13 - 13.5%",
    blend: "100% Pinot Noir",
    grapes: "Pinot Noir",
    ownership: "de Villaine & Leroy Families",
    winery:
      "Harlan Estate is a prestigious Napa Valley winery located in the Oakville AVA, renowned for its Cabernet Sauvignon-based wines. Founded in 1984 by Bill Harlan, the estate spans 240 acres, with 40 acres under vine, primarily Cabernet Sauvignon with Merlot, Cabernet Franc, and Petit Verdot. Its flagship wine debuted in 1990, gaining global acclaim with multiple 100-point scores from critics. Harlan Estate’s second wine, The Maiden, offers a more approachable expression. Winemaking emphasizes gentle extraction and aging in French oak for 24–26 months.",
    region:
      "Napa Valley is one of the world’s most prestigious wine regions, stretching 35 miles between the Vacas and Mayacamas mountain ranges. Its global acclaim stems from its ideal terroir—notably its climate and soils—for cultivating premium Cabernet Sauvignon. The region's proximity to San Francisco attracts millions of wine tourists annually. Napa's reputation was solidified by its victory over French wines in the 1976 Paris Judgment. Pioneers like George C. Yount, Charles Krug, and Robert Mondavi shaped its modern wine industry. While Cabernet Sauvignon dominates, varieties like Merlot, Zinfandel, Chardonnay, and Sauvignon Blanc also thrive.",
    grape_variety:
      'The term "Bordeaux Blend", whilst not legally defined, is widely used to describe wines that combine traditional Bordeaux grape varieties, primarily Cabernet Sauvignon and Merlot. Unlike its American counterpart "Meritage", it lacks official recognition but serves as a useful international reference for Bordeaux-style red wines. These blends are characterised by powerful structure, deep fruit flavours, and firm tannins. Though originating in France, the style has spread globally, with vineyards worldwide crafting their interpretations. The term\'s flexibility is both its strength and potential weakness.',
    rp_tasting_notes:
      "One of the most backward yet promising wines of the vintage is the 2003 Harlan Estate. Its dense opaque plum/purple color is accompanied by a sumptuous bouquet of graphite, camphor, creme de cassis, smoky barbecue wood and a hint of forest floor. Similar flavors hit the mouth with full-bodied splendor, a multidimensional mouthfeel and texture, and the sensational finish lasts more than 45 seconds. Some tannins are still present, and this wine seems much younger than expected at ten years of age, so give it 4-5 more years of bottle age and consume it over the following 20-25 years. One of the most stunningly beautiful vineyards in all of Napa Valley, Harlan Estate is located in the foothills of the Mayacamas Mountains overlooking the Oakville Corridor. Harlan has been making world-class, first growth quality wines since the debut vintages of 1990 and 1991. Virtually nothing has been changed by winemaker Bob Levy, owner Bill Harlan and globe-trotting consultant Michel Rolland. The wine is largely all Cabernet Sauvignon and the production from the 40-acre vineyard is usually under 2,000 cases. The vineyard has a surprising composition of 70% Cabernet Sauvignon, 20% Merlot, 8% Cabernet Franc and 2% Petit Verdot. Most blends lean heavily on the Cabernet Sauvignon with slightly more Cabernet Franc being utilized over recent vintages. Following the great 2001 and 2002 vintages, 2003 is the type of vintage that has a tendency to be forgotten, but the two 2003s prove that the site’s great pedigree is never easy to dismiss. Tel. (707) 944-1441",
  },
  {
    id: "b771646b-c0dd-45f5-8e23-6e874902a206",
    case_size: 3,
    location: "portfolio",
    quantity: 1,
    stock_wine_vintage: {
      id: 724,
      lwin11: "10984352014",
      name: "2014 Giacomo Conterno Barolo Riserva Monfortino",
      vintage: 2014,
      release_price: "55",
      wine: 37,
      rp_score: "100",
      rp_released: "Dec 01, 2021",
      rp_tasting_notes:
        'The Giacomo Conterno 2014 Barolo Riserva Monfortino is made with 100% fruit from the Francia cru, which is not the case for the 2015 vintage (that sees 22% Arione in the blend) or likely future vintages. In a sense, this 100-point wine represents a milestone or a chapter finale in the long and exciting trajectory of Italy\'s collected and revered Monfortino. I\'ve had the great fortune of tasting this wine from barrel over the course of four years and twice again this summer during my visits to the Conterno estates (in Gattinara and in Monforte d\'Alba). Roberto Conterno has long been referring to 2014 as "the vintage of his heart." There had been challenging rain during the summer, but by the end of August, Roberto knew that a window of warm and dry weather could make 2014 "the vintage of the century," he tells me. On cue, the skies opened, and the sun came shining through in September and lasted through harvest in the second half of October. As a result, this was a very long growing season and that is something the Nebbiolo grape loves most. You taste this in the tannic quality of the wine that is long, silky, elegant and firm. That quality texture and structure will carry this bottle over a half century of bottling aging, or more. From an analytical point of view, this 2014 vintage is the most tannic Monfortino made in 30 years, but you\'d hardly know it thanks to the smooth integration displayed here. The wine\'s bouquet is nuanced and fine with redcurrant, mint, blood orange, toasted aniseed, baked clay and tarry smoke. Initially, you get a savory touch of succulent grilled meat that adds to the "chewy" quality of the wine that Roberto Conterno often attributes to his favorite vintages of Monfortino. A note about corks: Extreme care is dedicated to quality control, and each of the 4,000 to 5,000 corks ordered for this wine are sniffed by human noses on team Conterno before making the cut.',
      rp_reviewer: "Monica Larner",
      holding_years: "0",
      liv_ex_value: 0.0,
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2027 - 2060",
      market_value: 6030.0,
      tags: "NA",
      processed_case: 6,
      bottle_size: "0750",
      oldest_vintage: 2021,
      mean: 6006.5,
      median: 6006.5,
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [3, 6],
      is_unavailable: false,
      get_notified: false,
      investment_id: 0,
      case_size: 0,
      quantity: 0,
      is_owner: false,
    },
    user_investment_wine_vintage: null,
    short_description: "",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_Monfortino.png",
    ],
    is_special_volumes: false,
    basket: null,
    basket_items: [],
    is_available: true,
    photo_request: false,
    wine_name: "2014 Giacomo Conterno Barolo Riserva Monfortino",
    fromm: "Italy",
    purchase_date: "2023-01-06",
    purchase_price: 18090,
    status: "Awaiting Arrival",
    sub_account: {
      id: "1",
      first_name: "Rin",
      last_name: "Vie",
      relationship: "",
      image: "/profile.jpg",
      birth_date: "2000-29-01",
    },
    bottle_size: "0750",
    vintage: 2014,
    alcohol_abv: "13 - 13.5%",
    blend: "100% Pinot Noir",
    grapes: "Pinot Noir",
    ownership: "de Villaine & Leroy Families",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    region:
      "Romanée-Conti, a Grand Cru vineyard in Vosne-Romanée, is one of the world’s most prestigious and exclusive wine estates. Owned solely by Domaine de la Romanée-Conti (DRC), its 1.81 hectares produce fewer than 500 cases annually of exceptional Pinot Noir, famed for elegance, depth, and ageing potential. Its ideal terroir—limestone-rich soils and an easterly slope—yields highly sought-after wines, commanding tens of thousands of dollars per bottle. Romanée-Conti’s rarity and prestige make it both the most coveted and counterfeited wine globally.",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    rp_tasting_notes:
      'The 2014 Romanée-Conti Grand Cru is not a million miles away from the Richebourg in style, again with hints of damp earth and woodland, quite ethereal as it often is at this stage, becoming more "airy" as it opens in the glass. The palate is structured on the entry, a little fuller and broader than the La Tâche, almost less discrete (though that sounds too pejorative). The acidity drives this forward and there is great substance on the finish. It will be intriguing to see whether this Romanée-Conti will retain this chutzpah once in bottle.',
  },
  {
    id: "7d86dde1-6e4a-4418-9c9e-916aeffc1f86",
    location: "portfolio",
    case_size: 6,
    quantity: 1,
    stock_wine_vintage: {
      id: 363,
      lwin11: "10826562000",
      name: "2000 Moët & Chandon Dom Perignon",
      vintage: 2000,
      release_price: "221",
      wine: 21,
      rp_score: "94",
      rp_released: "Dec 22, 2008",
      rp_tasting_notes:
        "The 2000 Brut Dom Perignon is a gorgeous, seductive wine that floats on the palate with remarkable grace. Toasty aromas meld into freshly cut flowers, apricots and pears, with sweet notes of mint and licorice that linger on the long finish. This perfumed, inviting Dom Perignon is elegance personified, and in this vintage the wine fully merits its lofty reputation. According to winemaker Vincent Chaperone there is only one disgorgement date for the first release of Dom Perignon, and the 2000 was disgorged over a period of weeks in March and April, 2007, 2007. Anticipated maturity: 2008-2018. Moet & Chandon is one of Champagne’s giants when it comes to the sheer number of bottles that emerge from its cellars each year. The house’s top wine, Dom Perignon, is quite possibly the most iconic wine in Champagne, and perhaps the world. Production numbers are always kept close to the vest, but that notwithstanding, it is impossible to ignore the exceptional quality that the best vintages offer. At its best Dom Perignon is also an extremely ageworthy wine. In recent years Chef de Caves Richard Geoffroy has instituted a program of re-releasing newly disgorged wines under the OEnotheque program. Younger vintages see a second release (also known as second plenitude), while some of the older, classic vintages from the 1970s are on their third release (also known as third plenitude). While the OEnotheques, particularly the third releases, can be very pricey, at their finest they offer an extraordinary,otherworldly drinking experience matched by few wines in the world. Although Moet & Chandon doesn't disclose disgorgement dates, Geoffroy is considering adding that information in the near future. An article covering a number older vintages of Dom Perignon will appear soon on www.erobertparker.com Importer: Moet Hennessy USA, New York, NY; tel. (212) 251-8200",
      rp_reviewer: "Antonio Galloni",
      holding_years: "0",
      liv_ex_value: 1780.0,
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2008 - 2018",
      market_value: 1165.0,
      tags: "NA",
      processed_case: 6,
      bottle_size: "0750",
      oldest_vintage: 2015,
      mean: 1206.6,
      median: 1172.0,
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [6],
      is_unavailable: false,
      get_notified: false,
      investment_id: 0,
      case_size: 0,
      quantity: 0,
      is_owner: false,
    },
    user_investment_wine_vintage: null,
    short_description: "",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Dom_Perignon_2012.png",
    ],
    is_special_volumes: false,
    basket: null,
    basket_items: [],
    is_available: true,
    photo_request: false,
    wine_name: "2000 Moët & Chandon Dom Perignon",
    fromm: "Champagne",
    purchase_date: "2025-01-06",
    purchase_price: 6990,
    status: "In Bond",
    sub_account: {
      id: "1",
      first_name: "Rin",
      last_name: "Vie",
      relationship: "",
      image: "/profile.jpg",
      birth_date: "2000-29-01",
    },
    bottle_size: "0750",
    vintage: 2000,
    alcohol_abv: "13 - 13.5%",
    blend: "100% Pinot Noir",
    grapes: "Pinot Noir",
    ownership: "de Villaine & Leroy Families",
    winery:
      "Dom Pérignon, owned by Moët & Chandon under LVMH, is a prestigious Champagne brand named after Dom Pierre Pérignon, a 17th-century monk credited with advancing Champagne production. First released in 1937, Dom Pérignon is a vintage-only Champagne, blending Chardonnay and Pinot Noir from the best vineyards. Its maturation follows the Plénitude concept: Vintage (9 years), P2 (12–15 years), and P3 (25+ years). Dom Pérignon also produces rare Rosé vintages, reflecting elegance and aging potential.",
    region:
      'Champagne Brut is a dry, sparkling wine from France\'s Champagne region. It can be white or rosé and is typically made from the classic blend of Chardonnay, Pinot Noir, and Pinot Meunier, though it may also include lesser-known varieties like Pinot Blanc, Pinot Gris, Petit Meslier, and Arbane. The term "Brut" means "raw," indicating minimal added sugar (dosage) during production. By law, Brut Champagne contains less than 15g/L of sugar. Drier styles include Brut Nature (0–3g/L) and Extra Brut (0–6g/L). Introduced by Perrier-Jouët in  1846 for the British market, Brut has become the most popular Champagne style today, surpassing sweeter versions like Sec, Demi-Sec, and Doux.',
    grape_variety:
      "The Champagne Blend traditionally combines Pinot Noir, Chardonnay, and Pinot Meunier, creating balanced sparkling wines. Pinot Noir adds structure and red fruit notes, Chardonnay brings elegance and aging potential, and Meunier contributes bright, fruity flavors. This blend thrives in cool climates like Champagne, California, and Tasmania. Outside Champagne, Pinot Meunier is less common. Popular food pairings include smoked salmon terrine, pork and prawn dumplings, and fried chicken with chili mayo, complementing the wine's crisp, vibrant profile.",
    rp_tasting_notes:
      "The 2000 Brut Dom Perignon is a gorgeous, seductive wine that floats on the palate with remarkable grace. Toasty aromas meld into freshly cut flowers, apricots and pears, with sweet notes of mint and licorice that linger on the long finish. This perfumed, inviting Dom Perignon is elegance personified, and in this vintage the wine fully merits its lofty reputation. According to winemaker Vincent Chaperone there is only one disgorgement date for the first release of Dom Perignon, and the 2000 was disgorged over a period of weeks in March and April, 2007, 2007. Anticipated maturity: 2008-2018. Moet & Chandon is one of Champagne’s giants when it comes to the sheer number of bottles that emerge from its cellars each year. The house’s top wine, Dom Perignon, is quite possibly the most iconic wine in Champagne, and perhaps the world. Production numbers are always kept close to the vest, but that notwithstanding, it is impossible to ignore the exceptional quality that the best vintages offer. At its best Dom Perignon is also an extremely ageworthy wine. In recent years Chef de Caves Richard Geoffroy has instituted a program of re-releasing newly disgorged wines under the OEnotheque program. Younger vintages see a second release (also known as second plenitude), while some of the older, classic vintages from the 1970s are on their third release (also known as third plenitude). While the OEnotheques, particularly the third releases, can be very pricey, at their finest they offer an extraordinary,otherworldly drinking experience matched by few wines in the world. Although Moet & Chandon doesn't disclose disgorgement dates, Geoffroy is considering adding that information in the near future. An article covering a number older vintages of Dom Perignon will appear soon on www.erobertparker.com Importer: Moet Hennessy USA, New York, NY; tel. (212) 251-8200",
  },
];
