import { uuidv4 } from "zod";
import { CartItemT, PortfolioT } from "./types";

export const portfolioId = uuidv4();

export const portfolio_default: CartItemT[] = [
  {
    id: "6df65967-efcf-4227-9cb8-5b8688625bb2",
    case_size: 6,
    location: "portfolio",
    quantity: 1,
    stock_wine_vintage: {
      id: 735,
      lwin11: "11222002003",
      name: "2003 Harlan Estate",
      vintage: 2003,
      release_price: "240",
      wine: 38,
      rp_score: "98+",
      rp_released: "Jun 28, 2013",
      rp_tasting_notes:
        "One of the most backward yet promising wines of the vintage is the 2003 Harlan Estate. Its dense opaque plum/purple color is accompanied by a sumptuous bouquet of graphite, camphor, creme de cassis, smoky barbecue wood and a hint of forest floor. Similar flavors hit the mouth with full-bodied splendor, a multidimensional mouthfeel and texture, and the sensational finish lasts more than 45 seconds. Some tannins are still present, and this wine seems much younger than expected at ten years of age, so give it 4-5 more years of bottle age and consume it over the following 20-25 years. One of the most stunningly beautiful vineyards in all of Napa Valley, Harlan Estate is located in the foothills of the Mayacamas Mountains overlooking the Oakville Corridor. Harlan has been making world-class, first growth quality wines since the debut vintages of 1990 and 1991. Virtually nothing has been changed by winemaker Bob Levy, owner Bill Harlan and globe-trotting consultant Michel Rolland. The wine is largely all Cabernet Sauvignon and the production from the 40-acre vineyard is usually under 2,000 cases. The vineyard has a surprising composition of 70% Cabernet Sauvignon, 20% Merlot, 8% Cabernet Franc and 2% Petit Verdot. Most blends lean heavily on the Cabernet Sauvignon with slightly more Cabernet Franc being utilized over recent vintages. Following the great 2001 and 2002 vintages, 2003 is the type of vintage that has a tendency to be forgotten, but the two 2003s prove that the site’s great pedigree is never easy to dismiss. Tel. (707) 944-1441",
      rp_reviewer: "Robert M. Parker, Jr.",
      holding_years: "3",
      liv_ex_value: 0,
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2017 - 2042",
      market_value: 5128.0,
      tags: "NA",
      processed_case: 6,
      bottle_size: "0750",
      oldest_vintage: 2021,
      mean: 5254.35,
      median: 5139.0,
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [6],
      is_unavailable: false,
      get_notified: false,
      investment_id: 0,
      case_size: 0,
      quantity: 0,
      is_owner: false,
    },
    user_investment_wine_vintage: null,
    short_description: "",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/HarlanEstate.png"],
    is_special_volumes: false,
    basket: null,
    basket_items: [],
    is_available: true,
    photo_request: false,
    wine_name: "2003 Harlan Estate",
    fromm: "California",
    purchase_date: "2025-01-06",
    purchase_price: 30768,
    status: "Buy Request",
    sub_account: {
      id: "1",
      first_name: "Rin",
      last_name: "Vie",
      relationship: "",
      image: "/profile.jpg",
      birth_date: "2000-29-01",
      is_active: false,
    },
    bottle_size: "0750",
    vintage: 2003,
    alcohol_abv: "13 - 13.5%",
    blend: "100% Pinot Noir",
    grapes: "Pinot Noir",
    ownership: "de Villaine & Leroy Families",
    winery:
      "Harlan Estate is a prestigious Napa Valley winery located in the Oakville AVA, renowned for its Cabernet Sauvignon-based wines. Founded in 1984 by Bill Harlan, the estate spans 240 acres, with 40 acres under vine, primarily Cabernet Sauvignon with Merlot, Cabernet Franc, and Petit Verdot. Its flagship wine debuted in 1990, gaining global acclaim with multiple 100-point scores from critics. Harlan Estate’s second wine, The Maiden, offers a more approachable expression. Winemaking emphasizes gentle extraction and aging in French oak for 24–26 months.",
    region:
      "Napa Valley is one of the world’s most prestigious wine regions, stretching 35 miles between the Vacas and Mayacamas mountain ranges. Its global acclaim stems from its ideal terroir—notably its climate and soils—for cultivating premium Cabernet Sauvignon. The region's proximity to San Francisco attracts millions of wine tourists annually. Napa's reputation was solidified by its victory over French wines in the 1976 Paris Judgment. Pioneers like George C. Yount, Charles Krug, and Robert Mondavi shaped its modern wine industry. While Cabernet Sauvignon dominates, varieties like Merlot, Zinfandel, Chardonnay, and Sauvignon Blanc also thrive.",
    grape_variety:
      'The term "Bordeaux Blend", whilst not legally defined, is widely used to describe wines that combine traditional Bordeaux grape varieties, primarily Cabernet Sauvignon and Merlot. Unlike its American counterpart "Meritage", it lacks official recognition but serves as a useful international reference for Bordeaux-style red wines. These blends are characterised by powerful structure, deep fruit flavours, and firm tannins. Though originating in France, the style has spread globally, with vineyards worldwide crafting their interpretations. The term\'s flexibility is both its strength and potential weakness.',
    rp_tasting_notes:
      "One of the most backward yet promising wines of the vintage is the 2003 Harlan Estate. Its dense opaque plum/purple color is accompanied by a sumptuous bouquet of graphite, camphor, creme de cassis, smoky barbecue wood and a hint of forest floor. Similar flavors hit the mouth with full-bodied splendor, a multidimensional mouthfeel and texture, and the sensational finish lasts more than 45 seconds. Some tannins are still present, and this wine seems much younger than expected at ten years of age, so give it 4-5 more years of bottle age and consume it over the following 20-25 years. One of the most stunningly beautiful vineyards in all of Napa Valley, Harlan Estate is located in the foothills of the Mayacamas Mountains overlooking the Oakville Corridor. Harlan has been making world-class, first growth quality wines since the debut vintages of 1990 and 1991. Virtually nothing has been changed by winemaker Bob Levy, owner Bill Harlan and globe-trotting consultant Michel Rolland. The wine is largely all Cabernet Sauvignon and the production from the 40-acre vineyard is usually under 2,000 cases. The vineyard has a surprising composition of 70% Cabernet Sauvignon, 20% Merlot, 8% Cabernet Franc and 2% Petit Verdot. Most blends lean heavily on the Cabernet Sauvignon with slightly more Cabernet Franc being utilized over recent vintages. Following the great 2001 and 2002 vintages, 2003 is the type of vintage that has a tendency to be forgotten, but the two 2003s prove that the site’s great pedigree is never easy to dismiss. Tel. (707) 944-1441",
    wine_parent: {
      id: 38,
      lwin7: "1122200",
      name: "Harlan Estate, Napa Valley",
      fromm: "California",
      red_wine: "Red Wine – Bold and Structured",
      grapes: "Bordeaux Blend Red",
      pair_with: "Beef and Venison",
      region_of_appellation: "NA",
      alcohol_abv: "13 - 14.5%",
      sweetness: "Dry",
      blend: "NA",
      ownership: "NA",
      closure_type: "Cork",
      grape_variety:
        'The term "Bordeaux Blend", whilst not legally defined, is widely used to describe wines that combine traditional Bordeaux grape varieties, primarily Cabernet Sauvignon and Merlot. Unlike its American counterpart "Meritage", it lacks official recognition but serves as a useful international reference for Bordeaux-style red wines. These blends are characterised by powerful structure, deep fruit flavours, and firm tannins. Though originating in France, the style has spread globally, with vineyards worldwide crafting their interpretations. The term\'s flexibility is both its strength and potential weakness.',
      region:
        "Napa Valley is one of the world’s most prestigious wine regions, stretching 35 miles between the Vacas and Mayacamas mountain ranges. Its global acclaim stems from its ideal terroir—notably its climate and soils—for cultivating premium Cabernet Sauvignon. The region's proximity to San Francisco attracts millions of wine tourists annually. Napa's reputation was solidified by its victory over French wines in the 1976 Paris Judgment. Pioneers like George C. Yount, Charles Krug, and Robert Mondavi shaped its modern wine industry. While Cabernet Sauvignon dominates, varieties like Merlot, Zinfandel, Chardonnay, and Sauvignon Blanc also thrive.",
      winery:
        "Harlan Estate is a prestigious Napa Valley winery located in the Oakville AVA, renowned for its Cabernet Sauvignon-based wines. Founded in 1984 by Bill Harlan, the estate spans 240 acres, with 40 acres under vine, primarily Cabernet Sauvignon with Merlot, Cabernet Franc, and Petit Verdot. Its flagship wine debuted in 1990, gaining global acclaim with multiple 100-point scores from critics. Harlan Estate’s second wine, The Maiden, offers a more approachable expression. Winemaking emphasizes gentle extraction and aging in French oak for 24–26 months.",
      images: [
        "https://d18vt6ndh4jzvp.cloudfront.net/media/HarlanEstate.png",
      ],
      oldest_vintage: 2000,
      maximum_price: 8200.0,
      annual_production: 2000,
      default_case_size: 3,
    },
    holding_year: "3",
  },
  {
    id: "b771646b-c0dd-45f5-8e23-6e874902a206",
    case_size: 3,
    location: "portfolio",
    quantity: 1,
    stock_wine_vintage: {
      id: 724,
      lwin11: "10984352014",
      name: "2014 Giacomo Conterno Barolo Riserva Monfortino",
      vintage: 2014,
      release_price: "55",
      wine: 37,
      rp_score: "100",
      rp_released: "Dec 01, 2021",
      rp_tasting_notes:
        'The Giacomo Conterno 2014 Barolo Riserva Monfortino is made with 100% fruit from the Francia cru, which is not the case for the 2015 vintage (that sees 22% Arione in the blend) or likely future vintages. In a sense, this 100-point wine represents a milestone or a chapter finale in the long and exciting trajectory of Italy\'s collected and revered Monfortino. I\'ve had the great fortune of tasting this wine from barrel over the course of four years and twice again this summer during my visits to the Conterno estates (in Gattinara and in Monforte d\'Alba). Roberto Conterno has long been referring to 2014 as "the vintage of his heart." There had been challenging rain during the summer, but by the end of August, Roberto knew that a window of warm and dry weather could make 2014 "the vintage of the century," he tells me. On cue, the skies opened, and the sun came shining through in September and lasted through harvest in the second half of October. As a result, this was a very long growing season and that is something the Nebbiolo grape loves most. You taste this in the tannic quality of the wine that is long, silky, elegant and firm. That quality texture and structure will carry this bottle over a half century of bottling aging, or more. From an analytical point of view, this 2014 vintage is the most tannic Monfortino made in 30 years, but you\'d hardly know it thanks to the smooth integration displayed here. The wine\'s bouquet is nuanced and fine with redcurrant, mint, blood orange, toasted aniseed, baked clay and tarry smoke. Initially, you get a savory touch of succulent grilled meat that adds to the "chewy" quality of the wine that Roberto Conterno often attributes to his favorite vintages of Monfortino. A note about corks: Extreme care is dedicated to quality control, and each of the 4,000 to 5,000 corks ordered for this wine are sniffed by human noses on team Conterno before making the cut.',
      rp_reviewer: "Monica Larner",
      holding_years: "1",
      liv_ex_value: 0.0,
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2027 - 2060",
      market_value: 6030.0,
      tags: "NA",
      processed_case: 6,
      bottle_size: "0750",
      oldest_vintage: 2021,
      mean: 6006.5,
      median: 6006.5,
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [3, 6],
      is_unavailable: false,
      get_notified: false,
      investment_id: 0,
      case_size: 0,
      quantity: 0,
      is_owner: false,
    },
    user_investment_wine_vintage: null,
    short_description: "",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_Monfortino.png",
    ],
    is_special_volumes: false,
    basket: null,
    basket_items: [],
    is_available: true,
    photo_request: false,
    wine_name: "2014 Giacomo Conterno Barolo Riserva Monfortino",
    fromm: "Italy",
    purchase_date: "2023-01-06",
    purchase_price: 18090,
    status: "Awaiting Arrival",
    sub_account: {
      id: "1",
      first_name: "Rin",
      last_name: "Vie",
      relationship: "",
      image: "/profile.jpg",
      birth_date: "2000-29-01",
      is_active: false,
    },
    bottle_size: "0750",
    vintage: 2014,
    alcohol_abv: "13 - 13.5%",
    blend: "100% Pinot Noir",
    grapes: "Pinot Noir",
    ownership: "de Villaine & Leroy Families",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    region:
      "Romanée-Conti, a Grand Cru vineyard in Vosne-Romanée, is one of the world’s most prestigious and exclusive wine estates. Owned solely by Domaine de la Romanée-Conti (DRC), its 1.81 hectares produce fewer than 500 cases annually of exceptional Pinot Noir, famed for elegance, depth, and ageing potential. Its ideal terroir—limestone-rich soils and an easterly slope—yields highly sought-after wines, commanding tens of thousands of dollars per bottle. Romanée-Conti’s rarity and prestige make it both the most coveted and counterfeited wine globally.",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    rp_tasting_notes:
      'The 2014 Romanée-Conti Grand Cru is not a million miles away from the Richebourg in style, again with hints of damp earth and woodland, quite ethereal as it often is at this stage, becoming more "airy" as it opens in the glass. The palate is structured on the entry, a little fuller and broader than the La Tâche, almost less discrete (though that sounds too pejorative). The acidity drives this forward and there is great substance on the finish. It will be intriguing to see whether this Romanée-Conti will retain this chutzpah once in bottle.',
    wine_parent: {
      id: 37,
      lwin7: "1098435",
      name: "Giacomo Conterno, Barolo, Monfortino Riserva",
      fromm: "Italy",
      red_wine: "Red Wine – Savory and Classic",
      grapes: "Nebbiolo",
      pair_with: "Lamb",
      region_of_appellation: "NA",
      alcohol_abv: "14 - 14.5%",
      sweetness: "Dry",
      blend: "100% Nebbiolo",
      ownership: "NA",
      closure_type: "Cork",
      grape_variety:
        'Nebbiolo is Piedmont’s iconic grape, famed for crafting Barolo and Barbaresco wines. Noted for its "tar and roses" aroma, Nebbiolo is high in tannins and acidity, aging into complex flavors of truffle and dark chocolate. It transitions from ruby to brick-red with age. Key regions include La Morra, Serralunga d\'Alba, and Roero. Nebbiolo thrives in well-drained, sunny slopes but is challenging to cultivate. Beyond Italy, it’s grown in the U.S., Australia, and Argentina.',
      region:
        'Barolo is a prestigious DOCG wine from Piedmont, Italy, crafted exclusively from Nebbiolo grapes. Known for its "tar and roses" aroma, firm tannins, and high acidity, Barolo develops complex flavors of truffles and dark chocolate with age. Key subregions like La Morra and Serralunga d\'Alba produce distinct styles, from aromatic to robust. Barolo must age at least 38 months (62 for Riserva). Modernists favor fruitier, earlier-drinking styles, sparking the ongoing "Barolo Wars" between tradition and innovation.',
      winery:
        "Giacomo Conterno is a prestigious Barolo producer in Monforte d'Alba, Piedmont. Renowned for its Monfortino Riserva and Cascina Francia Barolo, the estate emphasizes traditional winemaking, aging wines in large Slovenian oak casks. Founded in 1908 by Giovanni Conterno, the estate gained acclaim after acquiring the Cascina Francia vineyard in 1974. Under Roberto Conterno, it expanded with the Ceretta and Arione vineyards. Monfortino Riserva is produced only in top vintages, making around 7,000 bottles, while Barbera and Cascina Francia yield about 20,000 bottles annually.",
      images: [
        "https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_Monfortino.png",
      ],
      oldest_vintage: 2000,
      maximum_price: 13500.0,
      annual_production: 800,
      default_case_size: 6,
    },
    holding_year: "2",
  },
  {
    id: "7d86dde1-6e4a-4418-9c9e-916aeffc1f86",
    location: "portfolio",
    case_size: 6,
    quantity: 1,
    stock_wine_vintage: {
      id: 363,
      lwin11: "10826562000",
      name: "2000 Moët & Chandon Dom Perignon",
      vintage: 2000,
      release_price: "221",
      wine: 21,
      rp_score: "94",
      rp_released: "Dec 22, 2008",
      rp_tasting_notes:
        "The 2000 Brut Dom Perignon is a gorgeous, seductive wine that floats on the palate with remarkable grace. Toasty aromas meld into freshly cut flowers, apricots and pears, with sweet notes of mint and licorice that linger on the long finish. This perfumed, inviting Dom Perignon is elegance personified, and in this vintage the wine fully merits its lofty reputation. According to winemaker Vincent Chaperone there is only one disgorgement date for the first release of Dom Perignon, and the 2000 was disgorged over a period of weeks in March and April, 2007, 2007. Anticipated maturity: 2008-2018. Moet & Chandon is one of Champagne’s giants when it comes to the sheer number of bottles that emerge from its cellars each year. The house’s top wine, Dom Perignon, is quite possibly the most iconic wine in Champagne, and perhaps the world. Production numbers are always kept close to the vest, but that notwithstanding, it is impossible to ignore the exceptional quality that the best vintages offer. At its best Dom Perignon is also an extremely ageworthy wine. In recent years Chef de Caves Richard Geoffroy has instituted a program of re-releasing newly disgorged wines under the OEnotheque program. Younger vintages see a second release (also known as second plenitude), while some of the older, classic vintages from the 1970s are on their third release (also known as third plenitude). While the OEnotheques, particularly the third releases, can be very pricey, at their finest they offer an extraordinary,otherworldly drinking experience matched by few wines in the world. Although Moet & Chandon doesn't disclose disgorgement dates, Geoffroy is considering adding that information in the near future. An article covering a number older vintages of Dom Perignon will appear soon on www.erobertparker.com Importer: Moet Hennessy USA, New York, NY; tel. (212) 251-8200",
      rp_reviewer: "Antonio Galloni",
      holding_years: "4",
      liv_ex_value: 1780.0,
      is_listed: true,
      size: "NA",
      status: "NA",
      drinking_window: "2008 - 2018",
      market_value: 1165.0,
      tags: "NA",
      processed_case: 6,
      bottle_size: "0750",
      oldest_vintage: 2015,
      mean: 1206.6,
      median: 1172.0,
      is_user_investment: false,
      is_very_special: false,
      available_case_size: [6],
      is_unavailable: false,
      get_notified: false,
      investment_id: 0,
      case_size: 0,
      quantity: 0,
      is_owner: false,
    },
    user_investment_wine_vintage: null,
    short_description: "",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Dom_Perignon_2012.png",
    ],
    is_special_volumes: false,
    basket: null,
    basket_items: [],
    is_available: true,
    photo_request: false,
    wine_name: "2000 Moët & Chandon Dom Perignon",
    fromm: "Champagne",
    purchase_date: "2025-01-06",
    purchase_price: 6990,
    status: "In Bond",
    sub_account: {
      id: "1",
      first_name: "Rin",
      last_name: "Vie",
      relationship: "",
      image: "/profile.jpg",
      birth_date: "2000-29-01",
      is_active: false,
    },
    bottle_size: "0750",
    vintage: 2000,
    alcohol_abv: "13 - 13.5%",
    blend: "100% Pinot Noir",
    grapes: "Pinot Noir",
    ownership: "de Villaine & Leroy Families",
    winery:
      "Dom Pérignon, owned by Moët & Chandon under LVMH, is a prestigious Champagne brand named after Dom Pierre Pérignon, a 17th-century monk credited with advancing Champagne production. First released in 1937, Dom Pérignon is a vintage-only Champagne, blending Chardonnay and Pinot Noir from the best vineyards. Its maturation follows the Plénitude concept: Vintage (9 years), P2 (12–15 years), and P3 (25+ years). Dom Pérignon also produces rare Rosé vintages, reflecting elegance and aging potential.",
    region:
      'Champagne Brut is a dry, sparkling wine from France\'s Champagne region. It can be white or rosé and is typically made from the classic blend of Chardonnay, Pinot Noir, and Pinot Meunier, though it may also include lesser-known varieties like Pinot Blanc, Pinot Gris, Petit Meslier, and Arbane. The term "Brut" means "raw," indicating minimal added sugar (dosage) during production. By law, Brut Champagne contains less than 15g/L of sugar. Drier styles include Brut Nature (0–3g/L) and Extra Brut (0–6g/L). Introduced by Perrier-Jouët in  1846 for the British market, Brut has become the most popular Champagne style today, surpassing sweeter versions like Sec, Demi-Sec, and Doux.',
    grape_variety:
      "The Champagne Blend traditionally combines Pinot Noir, Chardonnay, and Pinot Meunier, creating balanced sparkling wines. Pinot Noir adds structure and red fruit notes, Chardonnay brings elegance and aging potential, and Meunier contributes bright, fruity flavors. This blend thrives in cool climates like Champagne, California, and Tasmania. Outside Champagne, Pinot Meunier is less common. Popular food pairings include smoked salmon terrine, pork and prawn dumplings, and fried chicken with chili mayo, complementing the wine's crisp, vibrant profile.",
    rp_tasting_notes:
      "The 2000 Brut Dom Perignon is a gorgeous, seductive wine that floats on the palate with remarkable grace. Toasty aromas meld into freshly cut flowers, apricots and pears, with sweet notes of mint and licorice that linger on the long finish. This perfumed, inviting Dom Perignon is elegance personified, and in this vintage the wine fully merits its lofty reputation. According to winemaker Vincent Chaperone there is only one disgorgement date for the first release of Dom Perignon, and the 2000 was disgorged over a period of weeks in March and April, 2007, 2007. Anticipated maturity: 2008-2018. Moet & Chandon is one of Champagne’s giants when it comes to the sheer number of bottles that emerge from its cellars each year. The house’s top wine, Dom Perignon, is quite possibly the most iconic wine in Champagne, and perhaps the world. Production numbers are always kept close to the vest, but that notwithstanding, it is impossible to ignore the exceptional quality that the best vintages offer. At its best Dom Perignon is also an extremely ageworthy wine. In recent years Chef de Caves Richard Geoffroy has instituted a program of re-releasing newly disgorged wines under the OEnotheque program. Younger vintages see a second release (also known as second plenitude), while some of the older, classic vintages from the 1970s are on their third release (also known as third plenitude). While the OEnotheques, particularly the third releases, can be very pricey, at their finest they offer an extraordinary,otherworldly drinking experience matched by few wines in the world. Although Moet & Chandon doesn't disclose disgorgement dates, Geoffroy is considering adding that information in the near future. An article covering a number older vintages of Dom Perignon will appear soon on www.erobertparker.com Importer: Moet Hennessy USA, New York, NY; tel. (212) 251-8200",
    wine_parent: {
      id: 21,
      lwin7: "1082656",
      name: "Dom Perignon",
      fromm: "Champagne",
      red_wine: "Sparkling Wine – Complex and Traditional",
      grapes: "Champagne Blend",
      pair_with: "Shellfish, Crab and Lobster",
      region_of_appellation: "NA",
      alcohol_abv: "12 - 12.5%",
      sweetness: "Dry",
      blend: "NA",
      ownership: "LVMH Moët Hennessy Louis Vuitton",
      closure_type: "Cork",
      grape_variety:
        "The Champagne Blend traditionally combines Pinot Noir, Chardonnay, and Pinot Meunier, creating balanced sparkling wines. Pinot Noir adds structure and red fruit notes, Chardonnay brings elegance and aging potential, and Meunier contributes bright, fruity flavors. This blend thrives in cool climates like Champagne, California, and Tasmania. Outside Champagne, Pinot Meunier is less common. Popular food pairings include smoked salmon terrine, pork and prawn dumplings, and fried chicken with chili mayo, complementing the wine's crisp, vibrant profile.",
      region:
        'Champagne Brut is a dry, sparkling wine from France\'s Champagne region. It can be white or rosé and is typically made from the classic blend of Chardonnay, Pinot Noir, and Pinot Meunier, though it may also include lesser-known varieties like Pinot Blanc, Pinot Gris, Petit Meslier, and Arbane. The term "Brut" means "raw," indicating minimal added sugar (dosage) during production. By law, Brut Champagne contains less than 15g/L of sugar. Drier styles include Brut Nature (0–3g/L) and Extra Brut (0–6g/L). Introduced by Perrier-Jouët in  1846 for the British market, Brut has become the most popular Champagne style today, surpassing sweeter versions like Sec, Demi-Sec, and Doux.',
      winery:
        "Dom Pérignon, owned by Moët & Chandon under LVMH, is a prestigious Champagne brand named after Dom Pierre Pérignon, a 17th-century monk credited with advancing Champagne production. First released in 1937, Dom Pérignon is a vintage-only Champagne, blending Chardonnay and Pinot Noir from the best vineyards. Its maturation follows the Plénitude concept: Vintage (9 years), P2 (12–15 years), and P3 (25+ years). Dom Pérignon also produces rare Rosé vintages, reflecting elegance and aging potential.",
      images: [
        "https://d18vt6ndh4jzvp.cloudfront.net/media/Dom_Perignon_2012.png",
      ],
      oldest_vintage: 1995,
      maximum_price: 1947.5,
      annual_production: 25000,
      default_case_size: 6,
    },
    holding_year: "1",
  },
  {
    id: "cffeac65-cd30-47b9-97a5-0112b0eab7da",
    case_size: 6,
    quantity: 1,
    stock_wine_vintage: null,
    user_investment_wine_vintage: null,
    short_description:
      "The Bordeaux Classic Collection brings together seven of the most iconic and historically significant wines from the Bordeaux region. Each estate represents a pinnacle of Old World winemaking, and together they form a distinguished, diversified bundle that blends prestige, rarity and long-term investment potential.\r\n\r\nThis collection includes Pétrus, Le Pin, Lafite Rothschild, Mouton Rothschild, Margaux, Latour and Haut-Brion – a line-up of estates whose reputations are built on centuries of excellence, critical acclaim, and enduring collector demand.\r\n\r\nBy acquiring these wines as a set, collectors secure exposure to multiple legendary producers whose track records for performance and value appreciation are unmatched. It is a portfolio built on heritage, scarcity, and timeless appeal.",
    images:
      "https://d18vt6ndh4jzvp.cloudfront.net/media/ChatGPT_Image_Dec_17_2025_09_20_19_PM.png",
    is_special_volumes: false,
    basket: {
      id: 3,
      name: "The Bordeaux Legends",
      vintage: null,
      quantity: 1,
      market_value: 43098,
      case_size: 6,
      winery:
        "The Bordeaux Classic Collection brings together seven of the most iconic and historically significant wines from the Bordeaux region. Each estate represents a pinnacle of Old World winemaking, and together they form a distinguished, diversified bundle that blends prestige, rarity and long-term investment potential.\r\n\r\nThis collection includes Pétrus, Le Pin, Lafite Rothschild, Mouton Rothschild, Margaux, Latour and Haut-Brion – a line-up of estates whose reputations are built on centuries of excellence, critical acclaim, and enduring collector demand.\r\n\r\nBy acquiring these wines as a set, collectors secure exposure to multiple legendary producers whose track records for performance and value appreciation are unmatched. It is a portfolio built on heritage, scarcity, and timeless appeal.",
      region:
        "Bordeaux is one of the world’s most prestigious wine regions, renowned for producing complex, age-worthy wines with structure, elegance, and remarkable longevity. Within the region, each estate occupies a distinct terroir that contributes to its unique character.\r\n\r\nPétrus, Pomerol - Located in Pomerol, famous for clay-rich soils that produce plush, powerful Merlot-driven wines.\r\n\r\nLe Pin, Pomerol - Also in Pomerol, offering tiny production, velvety textures, and exceptional rarity.\r\n\r\nLafite Rothschild, Pauillac - In Pauillac, known for gravelly soils that give structured, long-lived Cabernet Sauvignon blends.\r\n\r\nMouton Rothschild, Pauillac - Also in Pauillac, producing Cabernet Sauvignon-led wines with power, depth, and elegance.\r\n\r\nMargaux, Margaux - Set in Margaux, celebrated for silky, aromatic Cabernet Sauvignon-based blends.\r\n\r\nLatour, Pauillac -  Pauillac estate with concentrated, structured wines renowned for ageing.\r\n\r\nHaut-Brion, Pessac-Léognan - Based in Pessac-Léognan, producing refined, smoky blends of Cabernet Sauvignon and Merlot with distinctive character.",
      grapes: "Bordeaux Blend Red",
      grape_variety:
        "Pétrus – 100% Merlot, celebrated for its plush texture, richness, and incredible ageing potential.\r\n\r\nLe Pin – Predominantly Merlot, offering velvety, opulent wines with intense aromatic depth and rare scarcity.\r\n\r\nLafite Rothschild – Cabernet Sauvignon-led blend with Merlot, Cabernet Franc, and Petit Verdot, renowned for elegance, structure, and longevity.\r\n\r\nMouton Rothschild – Cabernet Sauvignon-dominant blend, combining power, depth, and a unique expression of Bordeaux artistry.\r\n\r\nMargaux – Cabernet Sauvignon-based blend with Merlot and Cabernet Franc, prized for its silky texture, aromatic complexity, and graceful finesse.\r\nLatour – Cabernet Sauvignon-driven blend, known for concentration, tannic strength, and extraordinary ageing potential.\r\n\r\nHaut-Brion – Blend of Cabernet Sauvignon, Merlot, and Cabernet Franc, offering profound depth, smoky elegance, and a distinctive Bordeaux signature.",
      fromm: "Bordeaux",
      image:
        "https://d18vt6ndh4jzvp.cloudfront.net/media/ChatGPT_Image_Dec_17_2025_09_20_19_PM.png",
      special_id: null,
      is_assortment: true,
      sub_header: "The Pinnacle Collection of Bordeaux’s Most Iconic Estates",
      bottle_size: "0750",
    },
    basket_items: [
      {
        id: 13,
        quantity: 1,
        wine_parent_id: 12,
        case_size: 6,
        basket_bottle_size: "0750",
        wine_vintage: {
          id: 181,
          lwin11: "10112472015",
          name: "2015 Haut-Brion",
          vintage: 2015,
          wine: 12,
          rp_score: "100",
          rp_released: "Feb 22, 2018",
          rp_tasting_notes:
            "A blend of 50% Merlot, 8% Cabernet Franc and 42% Cabernet Sauvignon, the medium to deep garnet-purple colored 2015 Haut-Brion is reticent to begin, languidly revealing crushed black cherries, ripe black plums and wild blueberries with sparks of cinnamon stick, cloves, nutmeg, espresso, unsmoked cigars, tapenade, crushed rocks and lavender. The full-bodied palate possesses wonderfully complementary contrasts of bold black and blue fruit richness and delicately nuanced cherry fruit, baking spices and floral accents, strutting ripe, finely pixelated tannins and seamless acidity that is placed firmly in the background, finishing very long and with plenty of attitude. This impeccably poised, exquisitely perfumed 2015 Haut-Brion possesses the most alluring yet seemingly effortless beauty. While it bears only a passing resemblance in its opulent personality to the now legendary 1989, like that vintage the 2015 cannot fail to hedonically satiate and intellectually edify all lovers of great Bordeaux who drink it. What’s more, it also has the blue-blooded tenaciousness to remain this jaw-droppingly impressive, throughout its many guises over time, and for a very, very long time.",
          rp_reviewer: "Lisa Perrotti-Brown",
          holding_years: "0",
          liv_ex_value: "0.00",
          is_listed: true,
          size: "NA",
          status: "NA",
          drinking_window: "2024 - 2064",
          market_value: "2088.00",
          tags: "NA",
          processed_case: 6,
          bottle_size: "0750",
          oldest_vintage: 2021,
          mean: "2327.03",
          median: "2178.00",
          is_user_investment: false,
          is_very_special: false,
        },
        wine_images: [
          "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_Haut_Brion.png",
        ],
      },
      {
        id: 14,
        quantity: 1,
        wine_parent_id: 13,
        case_size: 6,
        basket_bottle_size: "0750",
        wine_vintage: {
          id: 202,
          lwin11: "10118722014",
          name: "2014 Lafite Rothschild",
          vintage: 2014,
          wine: 13,
          rp_score: "95",
          rp_released: "Apr 01, 2017",
          rp_tasting_notes:
            "The 2014 Lafite-Rothschild, tasted with head winemaker Eric Kohler, has retained that very opulent and outgoing bouquet that dare I say actually reminded me of Mouton-Rothschild. There are layers of blackberry and boysenberry fruit, still that hint of juniper berry, certainly a more extrovert Lafite-Rothschild compared to recent vintages. The palate is medium-bodied with crisp tannin, very focused and quite linear, again with plenty of black fruit laced with cedar and tobacco. It begins to clam up towards the saline finish, suggesting that it will need several years in bottle, but I still have high expectations for this First Growth once afforded several years in bottle.",
          rp_reviewer: "Neal Martin",
          holding_years: "0",
          liv_ex_value: "0.00",
          is_listed: true,
          size: "NA",
          status: "NA",
          drinking_window: "2024 - 2045",
          market_value: "2152.00",
          tags: "NA",
          processed_case: 6,
          bottle_size: "0750",
          oldest_vintage: 2022,
          mean: "2302.07",
          median: "2297.50",
          is_user_investment: false,
          is_very_special: false,
        },
        wine_images: [
          "https://d18vt6ndh4jzvp.cloudfront.net/media/Lafite_Rothschild.png",
        ],
      },
      {
        id: 15,
        quantity: 1,
        wine_parent_id: 15,
        case_size: 6,
        basket_bottle_size: "0750",
        wine_vintage: {
          id: 248,
          lwin11: "10123162017",
          name: "2017 Latour",
          vintage: 2017,
          wine: 15,
          rp_score: "94",
          rp_released: "Apr 26, 2024",
          rp_tasting_notes:
            "The just-released 2017 Latour is surprisingly accessible by this estate's standards, offering up expressive aromas of crème de cassis, cigar wrapper, pencil shavings, burning embers and creamy new oak, followed by a medium to full-bodied, rich and layered palate that's fleshy and complete, with lively acids and a long, vanillin-inflected finish.",
          rp_reviewer: "William Kelley",
          holding_years: "0",
          liv_ex_value: "0.00",
          is_listed: true,
          size: "NA",
          status: "NA",
          drinking_window: "2025 - 2045",
          market_value: "2075.50",
          tags: "NA",
          processed_case: 6,
          bottle_size: "0750",
          oldest_vintage: 2017,
          mean: "2283.49",
          median: "2347.48",
          is_user_investment: false,
          is_very_special: false,
        },
        wine_images: [
          "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_Latour_1.png",
        ],
      },
      {
        id: 16,
        quantity: 1,
        wine_parent_id: 16,
        case_size: 6,
        basket_bottle_size: "0750",
        wine_vintage: {
          id: 266,
          lwin11: "10127812017",
          name: "2017 Château Margaux",
          vintage: 2017,
          wine: 16,
          rp_score: "98",
          rp_released: "Mar 17, 2020",
          rp_tasting_notes:
            "The 2017 Chateau Margaux is a blend of 89% Cabernet Sauvignon, 8% Merlot, 2% Cabernet Franc and 1% Petit Verdot. Deep garnet-purple colored, it needs a little coaxing to reveal alluring notes of blackcurrant cordial, Black Forest cake and black raspberries with suggestions of candied violets, tilled soil, fallen leaves, licorice and espresso plus wafts of underbrush and rosehip tea. Medium-bodied, the elegance and finesse on the palate is simply bedazzling, exuding a quiet intensity of fresh black fruits layered with oh-so-subtle floral and earth nuances. It has a soft, velvety texture and seamless freshness to support the tightly wound flavors, finishing long and perfumed. Beautiful! This grand vin accounts for just 37% of the crop.",
          rp_reviewer: "Lisa Perrotti-Brown",
          holding_years: "0",
          liv_ex_value: "0.00",
          is_listed: true,
          size: "NA",
          status: "NA",
          drinking_window: "2024 - 2060",
          market_value: "1721.00",
          tags: "NA",
          processed_case: 6,
          bottle_size: "0750",
          oldest_vintage: 2022,
          mean: "2053.10",
          median: "2100.00",
          is_user_investment: false,
          is_very_special: false,
        },
        wine_images: [
          "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_Margaux_1.png",
        ],
      },
      {
        id: 17,
        quantity: 1,
        wine_parent_id: 17,
        case_size: 6,
        basket_bottle_size: "0750",
        wine_vintage: {
          id: 285,
          lwin11: "10135442014",
          name: "2014 Mouton Rothschild",
          vintage: 2014,
          wine: 17,
          rp_score: "95",
          rp_released: "Apr 01, 2017",
          rp_tasting_notes:
            'The 2014 Mouton-Rothschild was closed at first when I tasted the wine in bottle with winemaker Philippe Dhalluin. But as it transpires, this First Growth is just toying with you. Initially quite understated, it responds to aeration like a young child peeking from around a corner and then running out, waving its hands. It suddenly hits you with gorgeous black cherries, bilberry, cedar and wilted rose petal. The palate is medium-bodied with a silky smooth entry. This is utterly seductive: a wine without a hair out of place. It is not as powerful or as complex as the 2015 Mouton-Rothschild, yet the precision and focus here is beguiling. It will require five to seven years to absorb the 100% new oak, then it will be an utterly delicious and to use a term employed at en primeur, "cerebral" First Growth that is destined to give two or three decades of pleasure.',
          rp_reviewer: "Neal Martin",
          holding_years: "0",
          liv_ex_value: "4055.00",
          is_listed: true,
          size: "NA",
          status: "NA",
          drinking_window: "2022 - 2060",
          market_value: "1822.50",
          tags: "NA",
          processed_case: 6,
          bottle_size: "0750",
          oldest_vintage: 2021,
          mean: "1987.98",
          median: "1925.00",
          is_user_investment: false,
          is_very_special: false,
        },
        wine_images: [
          "https://d18vt6ndh4jzvp.cloudfront.net/media/Mouton_Rothschild.png",
        ],
      },
      {
        id: 18,
        quantity: 1,
        wine_parent_id: 46,
        case_size: 6,
        basket_bottle_size: "0750",
        wine_vintage: {
          id: 904,
          lwin11: "10140332015",
          name: "2015 Pétrus",
          vintage: 2015,
          wine: 46,
          rp_score: "100",
          rp_released: "Feb 17, 2018",
          rp_tasting_notes:
            "When I asked winemaker Olivier Berrouet about his greatest challenges in 2015, he replied, “Our biggest challenge is to avoid all the temptations you can have in the vineyard and in the cellar. You can go too far. With our job, if you go too far, you can’t go back. Little steps are best.” His comments eloquently explain the immense pressure of handling a seemingly pressure-less vintage like 2015 in Pomerol. But, with the devil in all the many details that are involved in the pursuit of wine perfection, if anyone has that devil by the horns, it is this incredibly talented young winemaker. Medium to deep garnet-purple in color, the 2015 Petrus (bottled in mid-July 2017) opens in its own time to reveal crushed black cherries, warm plums, mulberries and cedar chest suggestions with touches of anise, lavender, beef drippings and wild thyme plus a waft of crushed rocks. Medium to full-bodied, it fills the palate with generous, exuberant, wonderfully layered red, black and perfumed blue fruits contrasted beautifully by very ripe, very fine-grained and very firm tannins plus an ethereal line of seamless acid, finishing long and minerally. Olivier Berrouet and his team have knocked it out of the park in 2015. Look for this Pétrus to build and unfold over the next 20 years and confidently cellar this legend for 40+ years.",
          rp_reviewer: "Lisa Perrotti-Brown",
          holding_years: "0",
          liv_ex_value: "37635.00",
          is_listed: true,
          size: "NA",
          status: "NA",
          drinking_window: "2024 - 2058",
          market_value: "17939.00",
          tags: "NA",
          processed_case: 6,
          bottle_size: "0750",
          oldest_vintage: 2021,
          mean: "18823.01",
          median: "18500.00",
          is_user_investment: false,
          is_very_special: false,
        },
        wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Petrus.png"],
      },
      {
        id: 19,
        quantity: 1,
        wine_parent_id: 41,
        case_size: 6,
        basket_bottle_size: "0750",
        wine_vintage: {
          id: 801,
          lwin11: "10141922015",
          name: "2015 Le Pin",
          vintage: 2015,
          wine: 41,
          rp_score: "99",
          rp_released: "Feb 22, 2018",
          rp_tasting_notes:
            "Deep garnet-purple in color, the 2015 Le Pin hits the dance floor with a completely gregarious nose of plum preserves, blackberry tart and wild blueberries, boldly accented by suggestions of Chinese five spice, cigar boxes, menthol and violets plus an earthy waft of underbrush. Full-bodied, concentrated, muscular and earthy with a firm backbone of exquisitely ripe, grainy tannins and plenty of freshness, it has an incredibly long finish featuring exotic spice and mineral layers.",
          rp_reviewer: "Lisa Perrotti-Brown",
          holding_years: "0",
          liv_ex_value: "37432.00",
          is_listed: true,
          size: "NA",
          status: "NA",
          drinking_window: "2022 - 2047",
          market_value: "15300.00",
          tags: "NA",
          processed_case: 6,
          bottle_size: "0750",
          oldest_vintage: 2021,
          mean: "15888.44",
          median: "16307.50",
          is_user_investment: false,
          is_very_special: false,
        },
        wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/LePin.png"],
      },
    ],
    is_available: true,
    photo_request: false,
    wine_name: "The Bordeaux Legends",
    fromm: "Bordeaux",
    purchase_date: "2026-01-10",
    purchase_price: 258588,
    status: "In Bond",
    sub_account: {
      id: "1",
      first_name: "Rin",
      last_name: "Vie",
      relationship: "",
      image: "/profile.jpg",
      birth_date: "2000-29-01",
      is_active: true,
    },
    bottle_size: "0750",
    vintage: 0,
    location: "portfolio",
    alcohol_abv: "",
    blend: "",
    grapes: "",
    ownership: "",
    winery:
      "The Bordeaux Classic Collection brings together seven of the most iconic and historically significant wines from the Bordeaux region. Each estate represents a pinnacle of Old World winemaking, and together they form a distinguished, diversified bundle that blends prestige, rarity and long-term investment potential.\r\n\r\nThis collection includes Pétrus, Le Pin, Lafite Rothschild, Mouton Rothschild, Margaux, Latour and Haut-Brion – a line-up of estates whose reputations are built on centuries of excellence, critical acclaim, and enduring collector demand.\r\n\r\nBy acquiring these wines as a set, collectors secure exposure to multiple legendary producers whose track records for performance and value appreciation are unmatched. It is a portfolio built on heritage, scarcity, and timeless appeal.",
    region:
      "Bordeaux is one of the world’s most prestigious wine regions, renowned for producing complex, age-worthy wines with structure, elegance, and remarkable longevity. Within the region, each estate occupies a distinct terroir that contributes to its unique character.\r\n\r\nPétrus, Pomerol - Located in Pomerol, famous for clay-rich soils that produce plush, powerful Merlot-driven wines.\r\n\r\nLe Pin, Pomerol - Also in Pomerol, offering tiny production, velvety textures, and exceptional rarity.\r\n\r\nLafite Rothschild, Pauillac - In Pauillac, known for gravelly soils that give structured, long-lived Cabernet Sauvignon blends.\r\n\r\nMouton Rothschild, Pauillac - Also in Pauillac, producing Cabernet Sauvignon-led wines with power, depth, and elegance.\r\n\r\nMargaux, Margaux - Set in Margaux, celebrated for silky, aromatic Cabernet Sauvignon-based blends.\r\n\r\nLatour, Pauillac -  Pauillac estate with concentrated, structured wines renowned for ageing.\r\n\r\nHaut-Brion, Pessac-Léognan - Based in Pessac-Léognan, producing refined, smoky blends of Cabernet Sauvignon and Merlot with distinctive character.",
    grape_variety:
      "Pétrus – 100% Merlot, celebrated for its plush texture, richness, and incredible ageing potential.\r\n\r\nLe Pin – Predominantly Merlot, offering velvety, opulent wines with intense aromatic depth and rare scarcity.\r\n\r\nLafite Rothschild – Cabernet Sauvignon-led blend with Merlot, Cabernet Franc, and Petit Verdot, renowned for elegance, structure, and longevity.\r\n\r\nMouton Rothschild – Cabernet Sauvignon-dominant blend, combining power, depth, and a unique expression of Bordeaux artistry.\r\n\r\nMargaux – Cabernet Sauvignon-based blend with Merlot and Cabernet Franc, prized for its silky texture, aromatic complexity, and graceful finesse.\r\nLatour – Cabernet Sauvignon-driven blend, known for concentration, tannic strength, and extraordinary ageing potential.\r\n\r\nHaut-Brion – Blend of Cabernet Sauvignon, Merlot, and Cabernet Franc, offering profound depth, smoky elegance, and a distinctive Bordeaux signature.",
    rp_tasting_notes: "",
    wine_parent: {
      id: 3,
      name: "The Bordeaux Legends",
      vintage: null,
      market_value: 43098,
      case_size: 6,
      winery:
        "The Bordeaux Classic Collection brings together seven of the most iconic and historically significant wines from the Bordeaux region. Each estate represents a pinnacle of Old World winemaking, and together they form a distinguished, diversified bundle that blends prestige, rarity and long-term investment potential.\r\n\r\nThis collection includes Pétrus, Le Pin, Lafite Rothschild, Mouton Rothschild, Margaux, Latour and Haut-Brion – a line-up of estates whose reputations are built on centuries of excellence, critical acclaim, and enduring collector demand.\r\n\r\nBy acquiring these wines as a set, collectors secure exposure to multiple legendary producers whose track records for performance and value appreciation are unmatched. It is a portfolio built on heritage, scarcity, and timeless appeal.",
      region:
        "Bordeaux is one of the world’s most prestigious wine regions, renowned for producing complex, age-worthy wines with structure, elegance, and remarkable longevity. Within the region, each estate occupies a distinct terroir that contributes to its unique character.\r\n\r\nPétrus, Pomerol - Located in Pomerol, famous for clay-rich soils that produce plush, powerful Merlot-driven wines.\r\n\r\nLe Pin, Pomerol - Also in Pomerol, offering tiny production, velvety textures, and exceptional rarity.\r\n\r\nLafite Rothschild, Pauillac - In Pauillac, known for gravelly soils that give structured, long-lived Cabernet Sauvignon blends.\r\n\r\nMouton Rothschild, Pauillac - Also in Pauillac, producing Cabernet Sauvignon-led wines with power, depth, and elegance.\r\n\r\nMargaux, Margaux - Set in Margaux, celebrated for silky, aromatic Cabernet Sauvignon-based blends.\r\n\r\nLatour, Pauillac -  Pauillac estate with concentrated, structured wines renowned for ageing.\r\n\r\nHaut-Brion, Pessac-Léognan - Based in Pessac-Léognan, producing refined, smoky blends of Cabernet Sauvignon and Merlot with distinctive character.",
      grapes: "Bordeaux Blend Red",
      grape_variety:
        "Pétrus – 100% Merlot, celebrated for its plush texture, richness, and incredible ageing potential.\r\n\r\nLe Pin – Predominantly Merlot, offering velvety, opulent wines with intense aromatic depth and rare scarcity.\r\n\r\nLafite Rothschild – Cabernet Sauvignon-led blend with Merlot, Cabernet Franc, and Petit Verdot, renowned for elegance, structure, and longevity.\r\n\r\nMouton Rothschild – Cabernet Sauvignon-dominant blend, combining power, depth, and a unique expression of Bordeaux artistry.\r\n\r\nMargaux – Cabernet Sauvignon-based blend with Merlot and Cabernet Franc, prized for its silky texture, aromatic complexity, and graceful finesse.\r\nLatour – Cabernet Sauvignon-driven blend, known for concentration, tannic strength, and extraordinary ageing potential.\r\n\r\nHaut-Brion – Blend of Cabernet Sauvignon, Merlot, and Cabernet Franc, offering profound depth, smoky elegance, and a distinctive Bordeaux signature.",
      fromm: "Bordeaux",
      special_id: null,
      is_assortment: false,
      sub_header: "The Pinnacle Collection of Bordeaux’s Most Iconic Estates",
    },
    holding_year: "5",
  },
];
