import { WineParent } from "./types";

export const defaultWineParent: WineParent = {
  id: 0,
  lwin7: "",
  name: "",
  fromm: "",
  region: "",
  region_of_appellation: "",
  red_wine: "",
  grapes: "",
  grape_variety: "",
  blend: "",
  pair_with: "",
  winery: "",
  annual_production: 0,
  default_case_size: 0,
  case_size: 0,
  special_id: null,
  vintage: null,
  oldest_vintage: 0,
  price: 0,
  market_value: 0,
  maximum_price: 0,
  alcohol_abv: "",
  sweetness: "",
  maturation: "",
  ownership: "",
  closure_type: "",
  images: [],
  is_assortment: false,
  sub_header: "",
};
