import { DefaultVintageT, VintexDetailsT, VintexResultsT, WineDetailsT } from "./types";

export const emptyVintexResult: VintexResultsT = {
  id: 0,
  lwin11: "",
  name: "",
  vintage: 0,
  release_price: "",
  wine: 0,
  rp_score: "",
  rp_released: "",
  rp_tasting_notes: "",
  rp_reviewer: "",
  holding_years: "",
  liv_ex_value: "",
  is_listed: false,
  size: "",
  status: "",
  drinking_window: "",
  market_value: "",
  tags: "",
  processed_case: 0,
  bottle_size: "",
  oldest_vintage: 0,
  mean: "",
  median: "",
  is_user_investment: false,
  is_very_special: false,
  available_case_size: [0],
  is_unavailable: false,
  get_notified: false,
};
export const emptyVintexWineDetail: WineDetailsT = {
  id: 0,
  lwin7: "",
  name: "",
  fromm: "",
  red_wine: "",
  grapes: "",
  pair_with: "",
  region_of_appellation: "",
  alcohol_abv: "",
  sweetness: "",
  blend: "",
  ownership: "",
  closure_type: "",
  grape_variety: "",
  region: "",
  winery: "",
  wine_images: [],
  oldest_vintage: 0,
  maximum_price: 0,
  annual_production: 0,
  default_case_size: 0,
};
export const emptyDefaultVintage: DefaultVintageT = {
  price: 0,
  vintage_year: 0,
  case_size: 0,
  wine_vintage: {
    id: 0,
    is_processed: false,
    lwin11: "",
    name: "",
    description: "",
    vintage: 0,
    wine: 0,
    rp_score: "",
    rp_released: "",
    rp_tasting_notes: "",
    rp_reviewer: "",
    holding_years: "",
    liv_ex_value: 0,
    is_listed: false,
    size: "",
    status: "",
    drinking_window: "",
    market_value: 0,
    tags: "",
    most_sold_cases: [0],
    available_case_size: [0],
    release_price: 0,
    mean: 0,
    median: 0,
    processed_case: 0,
    is_init: false,
    bottle_size: "",
    is_very_special: false,
    is_flagged: false,
    flagged_price: 0,
  },
};
export const emptyVintexParent: VintexDetailsT = {
  results: [],
  wine_details: emptyVintexWineDetail,
  default_vintage: emptyDefaultVintage,
};
