export const WineRare11 = {
  investment_id: 11,
  case_size: 1,
  quantity: 1,
  market_value: 300.0,
  is_owner: false,
  wine_vintage_details: {
    id: 1799,
    name: "Edivo, Navis Mysterium Undersea Amphora",
    lwin11: "30392452012",
    vintage: 2012,
    rp_score: "NA",
    release_price: 0.0,
    rp_released: "NA",
    rp_tasting_notes: "NA",
    rp_reviewer: "NA",
    holding_years: "NA",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "NA",
    market_value: "300.00",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 262.0,
    median: 262.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 60,
    lwin7: "0000000",
    name: "Edivo, Navis Mysterium Undersea Amphora",
    fromm: "Croatia",
    red_wine: "Rich and Intense",
    grapes: "Plavac Mali",
    pair_with: "Beef and Venison",
    region_of_appellation: "Peljesac Peninsula",
    alcohol_abv: "15%",
    sweetness: "NA",
    blend: "NA",
    maturation: "NA",
    ownership: "NA",
    closure_type: "NA",
    grape_variety:
      "Plavac Mali is a renowned red grape native to Croatia, especially prominent along the Dalmatian Coast. Known for producing robust wines with black cherry, spice, and smoky notes, it thrives in sun-drenched, rocky vineyards like those in Postup and Dingac. Its small, thick-skinned berries yield tannic, age-worthy wines, sometimes softened with residual sugar. Genetically linked to Zinfandel, it’s a cross between Zinfandel and Dobričić. Winemaker Mike Grgich helped introduce Plavac Mali to the global stage.",
    region:
      "The Pelješac Peninsula, between Split and Dubrovnik, is a key Croatian wine region famed for powerful Plavac Mali reds, especially from the Postup and Dingač appellations. Its mountainous, sun-drenched karst terrain creates ideal mesoclimates for viticulture. Dingač, established in 1961, was Croatia’s first appellation. Postup wines are slightly lighter but still rich. Pelješac wines are bold, tannic, and often feature smoky, gamey notes. The region also grows Graševina and lies just south of Hvar, another Plavac Mali stronghold.",
    winery:
      "Edivo Vina, located on Croatia's Pelješac Peninsula, is renowned for its unique underwater wine-aging process. Their signature wine, Navis Mysterium, matures in amphorae submerged beneath the Adriatic Sea for over 700 days, resulting in a distinct flavour profile. Visitors can enjoy wine tastings at the Edivo Wine Bar and, for certified divers, guided tours of the submerged cellar, offering an unparalleled oenological experience.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/edivo.png"],
    annual_production: 700,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};
