export const WineRare188 = {
  investment_id: 188,
  case_size: 1,
  quantity: 1,
  market_value: 306.0,
  is_owner: false,
  wine_vintage_details: {
    id: 779,
    name: "1998 Krug",
    lwin11: "13169351998",
    vintage: 1998,
    rp_score: "95",
    release_price: "135",
    rp_released: "Oct 31, 2012",
    rp_tasting_notes:
      "Krug's 1998 Brut Vintage is an excellent choice for drinking today, as the classic Krug style is rich, alive and totally vivid. Honey, almonds, smoke, graphite and dried apricots are some of the many aromas and flavors found in this rich, enveloping Champagne. A wine of texture and depth, the 1998 impresses for its vinous personality and terrific balance. Lively veins of underlying acidity suggest the 1998 will drink well for many years to follow. This is one of the best bottles of the 1998 I have ever tasted. Anticipated maturity: 2012-2038. There are no new vintage wines from Krug, but is always interesting to revisit these wines as they develop so much over time. The biggest news at Krug is the addition of ID Codes to the NV wines, which gives readers the opportunity to get more information on the wines (including disgorgement dates) through Krug's website. It would be great to see more of the larger houses follow suit.",
    rp_reviewer: "Antonio Galloni",
    holding_years: "0",
    liv_ex_value: 3112.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2012 - 2038",
    market_value: "1836.00",
    tags: "NA",
    processed_case: 6,
    bottle_size: "0750",
    mean: 1955.29,
    median: 1915.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 40,
    lwin7: "1316935",
    name: "Krug, Vintage Brut",
    fromm: "Champagne",
    red_wine: "Sparkling Wine – Complex and Traditional",
    grapes: "Champagne Blend",
    pair_with: "Shellfish, Crab and Lobster",
    region_of_appellation: "NA",
    alcohol_abv: "12%",
    sweetness: "Dry",
    blend: "Pinot Noir, Pinot Meunier & Chardonnay",
    maturation: "NA",
    ownership: "LVMH Moët Hennessy",
    closure_type: "Cork",
    grape_variety:
      "The Champagne Blend traditionally combines Pinot Noir, Chardonnay, and Pinot Meunier, creating balanced sparkling wines. Pinot Noir adds structure and red fruit notes, Chardonnay brings elegance and aging potential, and Meunier contributes bright, fruity flavors. This blend thrives in cool climates like Champagne, California, and Tasmania. Outside Champagne, Pinot Meunier is less common. Popular food pairings include smoked salmon terrine, pork and prawn dumplings, and fried chicken with chili mayo, complementing the wine's crisp, vibrant profile.",
    region:
      'Champagne Brut is a dry, sparkling wine from France’s Champagne region, made primarily from Chardonnay, Pinot Noir, and Pinot Meunier. It can also include rare varieties like Pinot Blanc, Pinot Gris, Petit Meslier, and Arbane. "Brut" means "raw," indicating minimal added sugar (less than 12g/L), although small amounts are added during disgorgement. Brut Champagne can be white, rosé, vintage, or non-vintage. Pioneered by Perrier-Jouët in 1846 for the English market, Brut is now the most popular Champagne style, surpassing sweeter versions like Sec and Demi-Sec.',
    winery:
      "Krug is one of Champagne's most prestigious houses, renowned for producing some of the most collectible and expensive wines in the region. Founded in 1843 by Joseph Krug, the house emphasizes crafting the best possible Champagne every year, rejecting traditional hierarchies. Its flagship wine, Grande Cuvée, blends around 120 wines from over 10 vintages, aged for six years for rich complexity. Krug also produces a vintage Champagne, a non-vintage rosé, and the rare, single-vineyard Clos du Mesnil (Chardonnay) and Clos d'Ambonnay (Pinot Noir). Now part of Moët Hennessy, Krug remains a symbol of luxury.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/krug.png"],
    annual_production: 15000,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};
