export const WineRare192 = {
  investment_id: 192,
  case_size: 6,
  quantity: 1,
  market_value: 1250.0,
  is_owner: false,
  wine_vintage_details: {
    id: 14,
    name: "2013 Bartolo Mascarello Barolo",
    lwin11: "11012452013",
    vintage: 2013,
    rp_score: "96",
    release_price: "60",
    rp_released: "Jul 01, 2017",
    rp_tasting_notes:
      "Bartolo Mascarello's 2013 Barolo is made with the estate's traditional blend of vineyard sites. This includes the San Lorenzo cru that will go offline starting with the 2015 vintage. This is a classic and traditional interpretation of Nebbiolo with an absolutely pristine and polished flavor profile. The bouquet opens to pressed violet, cassis, licorice, wild sage and cola. There is an elegant mineral imprint as well with rusty iron and iodine. This edition is evermore solid and centered compared to the warmer 2012 vintage. It will also require extra bottle aging in order to bring out its natural, but nuanced intensity.",
    rp_reviewer: "Monica Larner",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2019 - 2040",
    market_value: "1250.00",
    tags: "NA",
    processed_case: 6,
    bottle_size: "0750",
    mean: 1515.64,
    median: 1376.5,
    is_user_investment: true,
  },
  wine_parent: {
    id: 3,
    lwin7: "1101245",
    name: "Bartolo Mascarello, Barolo",
    fromm: "Italy",
    red_wine: "Savory and Classic",
    grapes: "Nebbiolo",
    pair_with: "Lamb",
    region_of_appellation: "NA",
    alcohol_abv: "13.50%",
    sweetness: "Dry",
    blend: "100% Nebbiolo",
    maturation: "Oaked",
    ownership: "Maria-Teresa Mascarello",
    closure_type: "Cork",
    grape_variety:
      'Nebbiolo is Piedmont’s iconic grape, famed for crafting Barolo and Barbaresco wines. Noted for its "tar and roses" aroma, Nebbiolo is high in tannins and acidity, aging into complex flavors of truffle and dark chocolate. It transitions from ruby to brick-red with age. Key regions include La Morra, Serralunga d\'Alba, and Roero. Nebbiolo thrives in well-drained, sunny slopes but is challenging to cultivate. Beyond Italy, it’s grown in the U.S., Australia, and Argentina.',
    region:
      'Barolo is a prestigious DOCG wine from Piedmont, Italy, crafted exclusively from Nebbiolo grapes. Known for its "tar and roses" aroma, firm tannins, and high acidity, Barolo develops complex flavors of truffles and dark chocolate with age. Key subregions like La Morra and Serralunga d\'Alba produce distinct styles, from aromatic to robust. Barolo must age at least 38 months (62 for Riserva). Modernists favor fruitier, earlier-drinking styles, sparking the ongoing "Barolo Wars" between tradition and innovation.',
    winery:
      'Bartolo Mascarello is a prestigious Barolo producer in Piedmont, Italy, founded in 1918. The estate gained global recognition under Bartolo Mascarello, a staunch traditionalist who opposed modern winemaking trends like French oak barriques and single-vineyard bottlings. His iconic "No Barrique, No Berlusconi" label highlighted his political views and commitment to tradition. Now led by his daughter Maria-Teresa Mascarello, the estate blends grapes from Cannubi, San Lorenzo, Rué, and Rocche dell\'Annunziata. Wines are elegant, aged in Slavonian oak botti, with annual Barolo production around 1,250 cases.',
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_-_Wine_3.png"],
    annual_production: 2000,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};
