export const WineRare379 = {
  investment_id: 379,
  case_size: 1,
  quantity: 1,
  market_value: 5083.333333333333,
  is_owner: false,
  wine_vintage_details: {
    id: 1852,
    name: "1994 Domaine de la Romanée-Conti La Tâche Grand Cru",
    lwin11: "10287041994",
    vintage: 1994,
    rp_score: "84",
    release_price: "4353",
    rp_released: "Dec 28, 2018",
    rp_tasting_notes:
      "The Domaine de la Romanée-Conti's 1994 La Tâche Grand Cru does not transcend the limitations of this challenging vintage, offering up a rather pedestrian bouquet of red-black fruit and licorice, becoming more and more dominated by its lavish application of high-quality new oak as it sits in the glass and never revealing any of the aromatic drama of which La Tâche is capable. On the palate, the wine is chunky and foursquare, with bright acids and a certain tannic asperity that suggests this is unlikely to change in any critical respect in the foreseeable future.",
    rp_reviewer: "William Kelley",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2018 - 2025",
    market_value: "30500.00",
    tags: "NA",
    processed_case: 6,
    bottle_size: "0750",
    mean: 30500.0,
    median: 30500.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 27,
    lwin7: "1028704",
    name: "DRC, La Tache Grand Cru (Romanee)",
    fromm: "Burgundy",
    red_wine: "Savory and Classic",
    grapes: "Pinot Noir",
    pair_with: "Duck, Goose and Game Birds",
    region_of_appellation: "NA",
    alcohol_abv: "13 - 13.5%",
    sweetness: "Dry",
    blend: "100% Pinot Noir",
    maturation: "Oaked",
    ownership: "de Villaine & Leroy Families",
    closure_type: "Cork",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    region:
      "La Tâche is a prestigious Grand Cru monopole vineyard in Vosne-Romanée, exclusively owned by Domaine de la Romanée-Conti (DRC) since 1933. Covering 6.06 hectares, it is over three times larger than Romanée-Conti. Its terroir features pebbly limestone soils, with thinner, free-draining soils on higher slopes and more clay at the base, allowing for complex, structured Pinot Noir wines. Known for power and elegance, La Tâche is farmed organically and produces wines celebrated for their depth, aging potential, and remarkable balance.",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRCLaTacheGrandCruRedWine.png",
    ],
    annual_production: 2000,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};
