export const WineRare380 = {
  investment_id: 380,
  case_size: 1,
  quantity: 1,
  market_value: 1862.0,
  is_owner: false,
  wine_vintage_details: {
    id: 1853,
    name: "1992 Domaine de la Romanée-Conti Richebourg Grand Cru",
    lwin11: "10286741992",
    vintage: 1992,
    rp_score: "83",
    release_price: "2721",
    rp_released: "NA",
    rp_tasting_notes: "NA",
    rp_reviewer: "Wine Spectator",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2007 - 2028",
    market_value: "1862.00",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 0.0,
    median: 0.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 28,
    lwin7: "1028674",
    name: "DRC, Richebourg Grand Cru (Romanee)",
    fromm: "Burgundy",
    red_wine: "Savory and Classic",
    grapes: "Pinot Noir",
    pair_with: "Duck, Goose and Game Birds",
    region_of_appellation: "NA",
    alcohol_abv: "13 - 13.5%",
    sweetness: "Dry",
    blend: "100% Pinot Noir",
    maturation: "Oaked",
    ownership: "de Villaine & Leroy Families",
    closure_type: "Cork",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    region:
      "Richebourg is a prestigious Grand Cru vineyard in Vosne-Romanée, producing some of Burgundy’s most opulent Pinot Noir wines, known for dense fruit, earthy complexity, and exceptional ageing potential. Covering 8 hectares, it consists of two lieux-dits: Les Richebourgs (warmer, denser wines) and Les Véroilles (cooler, more mineral-driven wines). Its well-drained pebbly clay and limestone soils contribute to rich, structured wines. Domaine de la Romanée-Conti is the largest owner, alongside Domaine Leroy and Anne Gros. Henri Jayer’s rare Richebourg wines remain highly prized.",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Richebourg.png"],
    annual_production: 1200,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};
