export const WineRare381 = {
  investment_id: 381,
  case_size: 3,
  quantity: 1,
  market_value: 10500.0,
  is_owner: false,
  wine_vintage_details: {
    id: 526,
    name: "2015 Domaine de la Romanée-Conti Richebourg Grand Cru",
    lwin11: "10286742015",
    vintage: 2015,
    rp_score: "96",
    release_price: "312",
    rp_released: "Mar 01, 2018",
    rp_tasting_notes:
      "The 2015 Richebourg Grand Cru is very good indeed, offering up a pure and surprisingly expressive nose of strawberry, dried rose, plum preserve, roast squab, raw cocoa and incipient rich soil tones, framed by some nutty new oak. On the palate, the wine is full-bodied, multidimensional and rich, sweet fruit playing in counterpoint with sapid, savory nuance. This Richebourg is denser at the core and less expansive than the corresponding Romanée-St-Vivant, and though the grain of its tannins is similar, their impact is more assertive and muscular. Cropped at 24 hectoliters per hectare and harvested September 8 and 9.",
    rp_reviewer: "William Kelley",
    holding_years: "0",
    liv_ex_value: 35018.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2025 - 2050",
    market_value: "10500.00",
    tags: "NA",
    processed_case: 3,
    bottle_size: "0750",
    mean: 10930.6,
    median: 10500.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 28,
    lwin7: "1028674",
    name: "DRC, Richebourg Grand Cru (Romanee)",
    fromm: "Burgundy",
    red_wine: "Savory and Classic",
    grapes: "Pinot Noir",
    pair_with: "Duck, Goose and Game Birds",
    region_of_appellation: "NA",
    alcohol_abv: "13 - 13.5%",
    sweetness: "Dry",
    blend: "100% Pinot Noir",
    maturation: "Oaked",
    ownership: "de Villaine & Leroy Families",
    closure_type: "Cork",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    region:
      "Richebourg is a prestigious Grand Cru vineyard in Vosne-Romanée, producing some of Burgundy’s most opulent Pinot Noir wines, known for dense fruit, earthy complexity, and exceptional ageing potential. Covering 8 hectares, it consists of two lieux-dits: Les Richebourgs (warmer, denser wines) and Les Véroilles (cooler, more mineral-driven wines). Its well-drained pebbly clay and limestone soils contribute to rich, structured wines. Domaine de la Romanée-Conti is the largest owner, alongside Domaine Leroy and Anne Gros. Henri Jayer’s rare Richebourg wines remain highly prized.",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Richebourg.png"],
    annual_production: 1200,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};
