export const WineRare382 = {
  investment_id: 382,
  case_size: 1,
  quantity: 1,
  market_value: 15950.0,
  is_owner: false,
  wine_vintage_details: {
    id: 549,
    name: "2016 Domaine de la Romanée-Conti Romanée-Conti Grand Cru",
    lwin11: "10286872016",
    vintage: 2016,
    rp_score: "98",
    release_price: "-13",
    rp_released: "Jan, 2019",
    rp_tasting_notes:
      "The 2016 Romanée-Conti Grand Cru was picked on September 25 at 24hL/ha. As usual, I allowed it five or six minutes to open in the glass. It is a very subtle Romanée-Conti, more discreet than the 2016 La Tâche, but then you become entranced by its spellbinding purity and grace. It gradually builds aromatically, augmenting the black fruit with red, and developing scents of wild hedgerow and freshly tilled soil - almost a pastoral element. The palate is medium-bodied with extremely precise and fine tannin and notes of wild strawberry, cranberry and crushed limestone. This feels very harmonious, the texture silkier than the La Tâche, displaying just a touch of bay leaf and black pepper toward the sustained finish, which gains depth and grip with aeration. Exquisite, though I suspect the La Tâche will challenge it for supremacy. 440 cases produced. Tasted at Corney & Barrow’s annual in-bottle tasting in London.",
    rp_reviewer: "Neal Martin",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2026 - 2060",
    market_value: "15950.00",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 19815.3,
    median: 17578.61,
    is_user_investment: true,
  },
  wine_parent: {
    id: 29,
    lwin7: "1028687",
    name: "DRC, Romanee-Conti Grand Cru",
    fromm: "Burgundy",
    red_wine: "Savory and Classic",
    grapes: "Pinot Noir",
    pair_with: "Duck, Goose and Game Birds",
    region_of_appellation: "NA",
    alcohol_abv: "13 - 13.5%",
    sweetness: "Dry",
    blend: "100% Pinot Noir",
    maturation: "Oaked",
    ownership: "de Villaine & Leroy Families",
    closure_type: "Cork",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    region:
      "Romanée-Conti, a Grand Cru vineyard in Vosne-Romanée, is one of the world’s most prestigious and exclusive wine estates. Owned solely by Domaine de la Romanée-Conti (DRC), its 1.81 hectares produce fewer than 500 cases annually of exceptional Pinot Noir, famed for elegance, depth, and ageing potential. Its ideal terroir—limestone-rich soils and an easterly slope—yields highly sought-after wines, commanding tens of thousands of dollars per bottle. Romanée-Conti’s rarity and prestige make it both the most coveted and counterfeited wine globally.",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Romanee_Conti.png",
    ],
    annual_production: 500,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};
