export const WineRare11 = {
  investment_id: 11,
  case_size: 1,
  quantity: 1,
  market_value: 300.0,
  is_owner: false,
  wine_vintage_details: {
    id: 1799,
    name: "Edivo, Navis Mysterium Undersea Amphora",
    lwin11: "30392452012",
    vintage: 2012,
    rp_score: "NA",
    release_price: 0.0,
    rp_released: "NA",
    rp_tasting_notes: "NA",
    rp_reviewer: "NA",
    holding_years: "NA",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "NA",
    market_value: "300.00",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 262.0,
    median: 262.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 60,
    lwin7: "0000000",
    name: "Edivo, Navis Mysterium Undersea Amphora",
    fromm: "Croatia",
    red_wine: "Rich and Intense",
    grapes: "Plavac Mali",
    pair_with: "Beef and Venison",
    region_of_appellation: "Peljesac Peninsula",
    alcohol_abv: "15%",
    sweetness: "NA",
    blend: "NA",
    maturation: "NA",
    ownership: "NA",
    closure_type: "NA",
    grape_variety:
      "Plavac Mali is a renowned red grape native to Croatia, especially prominent along the Dalmatian Coast. Known for producing robust wines with black cherry, spice, and smoky notes, it thrives in sun-drenched, rocky vineyards like those in Postup and Dingac. Its small, thick-skinned berries yield tannic, age-worthy wines, sometimes softened with residual sugar. Genetically linked to Zinfandel, it’s a cross between Zinfandel and Dobričić. Winemaker Mike Grgich helped introduce Plavac Mali to the global stage.",
    region:
      "The Pelješac Peninsula, between Split and Dubrovnik, is a key Croatian wine region famed for powerful Plavac Mali reds, especially from the Postup and Dingač appellations. Its mountainous, sun-drenched karst terrain creates ideal mesoclimates for viticulture. Dingač, established in 1961, was Croatia’s first appellation. Postup wines are slightly lighter but still rich. Pelješac wines are bold, tannic, and often feature smoky, gamey notes. The region also grows Graševina and lies just south of Hvar, another Plavac Mali stronghold.",
    winery:
      "Edivo Vina, located on Croatia's Pelješac Peninsula, is renowned for its unique underwater wine-aging process. Their signature wine, Navis Mysterium, matures in amphorae submerged beneath the Adriatic Sea for over 700 days, resulting in a distinct flavour profile. Visitors can enjoy wine tastings at the Edivo Wine Bar and, for certified divers, guided tours of the submerged cellar, offering an unparalleled oenological experience.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/edivo.png"],
    annual_production: 700,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare188 = {
  investment_id: 188,
  case_size: 1,
  quantity: 1,
  market_value: 306.0,
  is_owner: false,
  wine_vintage_details: {
    id: 779,
    name: "1998 Krug",
    lwin11: "13169351998",
    vintage: 1998,
    rp_score: "95",
    release_price: "135",
    rp_released: "Oct 31, 2012",
    rp_tasting_notes:
      "Krug's 1998 Brut Vintage is an excellent choice for drinking today, as the classic Krug style is rich, alive and totally vivid. Honey, almonds, smoke, graphite and dried apricots are some of the many aromas and flavors found in this rich, enveloping Champagne. A wine of texture and depth, the 1998 impresses for its vinous personality and terrific balance. Lively veins of underlying acidity suggest the 1998 will drink well for many years to follow. This is one of the best bottles of the 1998 I have ever tasted. Anticipated maturity: 2012-2038. There are no new vintage wines from Krug, but is always interesting to revisit these wines as they develop so much over time. The biggest news at Krug is the addition of ID Codes to the NV wines, which gives readers the opportunity to get more information on the wines (including disgorgement dates) through Krug's website. It would be great to see more of the larger houses follow suit.",
    rp_reviewer: "Antonio Galloni",
    holding_years: "0",
    liv_ex_value: 3112.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2012 - 2038",
    market_value: "1836.00",
    tags: "NA",
    processed_case: 6,
    bottle_size: "0750",
    mean: 1955.29,
    median: 1915.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 40,
    lwin7: "1316935",
    name: "Krug, Vintage Brut",
    fromm: "Champagne",
    red_wine: "Sparkling Wine – Complex and Traditional",
    grapes: "Champagne Blend",
    pair_with: "Shellfish, Crab and Lobster",
    region_of_appellation: "NA",
    alcohol_abv: "12%",
    sweetness: "Dry",
    blend: "Pinot Noir, Pinot Meunier & Chardonnay",
    maturation: "NA",
    ownership: "LVMH Moët Hennessy",
    closure_type: "Cork",
    grape_variety:
      "The Champagne Blend traditionally combines Pinot Noir, Chardonnay, and Pinot Meunier, creating balanced sparkling wines. Pinot Noir adds structure and red fruit notes, Chardonnay brings elegance and aging potential, and Meunier contributes bright, fruity flavors. This blend thrives in cool climates like Champagne, California, and Tasmania. Outside Champagne, Pinot Meunier is less common. Popular food pairings include smoked salmon terrine, pork and prawn dumplings, and fried chicken with chili mayo, complementing the wine's crisp, vibrant profile.",
    region:
      'Champagne Brut is a dry, sparkling wine from France’s Champagne region, made primarily from Chardonnay, Pinot Noir, and Pinot Meunier. It can also include rare varieties like Pinot Blanc, Pinot Gris, Petit Meslier, and Arbane. "Brut" means "raw," indicating minimal added sugar (less than 12g/L), although small amounts are added during disgorgement. Brut Champagne can be white, rosé, vintage, or non-vintage. Pioneered by Perrier-Jouët in 1846 for the English market, Brut is now the most popular Champagne style, surpassing sweeter versions like Sec and Demi-Sec.',
    winery:
      "Krug is one of Champagne's most prestigious houses, renowned for producing some of the most collectible and expensive wines in the region. Founded in 1843 by Joseph Krug, the house emphasizes crafting the best possible Champagne every year, rejecting traditional hierarchies. Its flagship wine, Grande Cuvée, blends around 120 wines from over 10 vintages, aged for six years for rich complexity. Krug also produces a vintage Champagne, a non-vintage rosé, and the rare, single-vineyard Clos du Mesnil (Chardonnay) and Clos d'Ambonnay (Pinot Noir). Now part of Moët Hennessy, Krug remains a symbol of luxury.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/krug.png"],
    annual_production: 15000,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare192 = {
  investment_id: 192,
  case_size: 6,
  quantity: 1,
  market_value: 1250.0,
  is_owner: false,
  wine_vintage_details: {
    id: 14,
    name: "2013 Bartolo Mascarello Barolo",
    lwin11: "11012452013",
    vintage: 2013,
    rp_score: "96",
    release_price: "60",
    rp_released: "Jul 01, 2017",
    rp_tasting_notes:
      "Bartolo Mascarello's 2013 Barolo is made with the estate's traditional blend of vineyard sites. This includes the San Lorenzo cru that will go offline starting with the 2015 vintage. This is a classic and traditional interpretation of Nebbiolo with an absolutely pristine and polished flavor profile. The bouquet opens to pressed violet, cassis, licorice, wild sage and cola. There is an elegant mineral imprint as well with rusty iron and iodine. This edition is evermore solid and centered compared to the warmer 2012 vintage. It will also require extra bottle aging in order to bring out its natural, but nuanced intensity.",
    rp_reviewer: "Monica Larner",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2019 - 2040",
    market_value: "1250.00",
    tags: "NA",
    processed_case: 6,
    bottle_size: "0750",
    mean: 1515.64,
    median: 1376.5,
    is_user_investment: true,
  },
  wine_parent: {
    id: 3,
    lwin7: "1101245",
    name: "Bartolo Mascarello, Barolo",
    fromm: "Italy",
    red_wine: "Savory and Classic",
    grapes: "Nebbiolo",
    pair_with: "Lamb",
    region_of_appellation: "NA",
    alcohol_abv: "13.50%",
    sweetness: "Dry",
    blend: "100% Nebbiolo",
    maturation: "Oaked",
    ownership: "Maria-Teresa Mascarello",
    closure_type: "Cork",
    grape_variety:
      'Nebbiolo is Piedmont’s iconic grape, famed for crafting Barolo and Barbaresco wines. Noted for its "tar and roses" aroma, Nebbiolo is high in tannins and acidity, aging into complex flavors of truffle and dark chocolate. It transitions from ruby to brick-red with age. Key regions include La Morra, Serralunga d\'Alba, and Roero. Nebbiolo thrives in well-drained, sunny slopes but is challenging to cultivate. Beyond Italy, it’s grown in the U.S., Australia, and Argentina.',
    region:
      'Barolo is a prestigious DOCG wine from Piedmont, Italy, crafted exclusively from Nebbiolo grapes. Known for its "tar and roses" aroma, firm tannins, and high acidity, Barolo develops complex flavors of truffles and dark chocolate with age. Key subregions like La Morra and Serralunga d\'Alba produce distinct styles, from aromatic to robust. Barolo must age at least 38 months (62 for Riserva). Modernists favor fruitier, earlier-drinking styles, sparking the ongoing "Barolo Wars" between tradition and innovation.',
    winery:
      'Bartolo Mascarello is a prestigious Barolo producer in Piedmont, Italy, founded in 1918. The estate gained global recognition under Bartolo Mascarello, a staunch traditionalist who opposed modern winemaking trends like French oak barriques and single-vineyard bottlings. His iconic "No Barrique, No Berlusconi" label highlighted his political views and commitment to tradition. Now led by his daughter Maria-Teresa Mascarello, the estate blends grapes from Cannubi, San Lorenzo, Rué, and Rocche dell\'Annunziata. Wines are elegant, aged in Slavonian oak botti, with annual Barolo production around 1,250 cases.',
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_-_Wine_3.png"],
    annual_production: 2000,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare379 = {
  investment_id: 379,
  case_size: 1,
  quantity: 1,
  market_value: 5083.333333333333,
  is_owner: false,
  wine_vintage_details: {
    id: 1852,
    name: "1994 Domaine de la Romanée-Conti La Tâche Grand Cru",
    lwin11: "10287041994",
    vintage: 1994,
    rp_score: "84",
    release_price: "4353",
    rp_released: "Dec 28, 2018",
    rp_tasting_notes:
      "The Domaine de la Romanée-Conti's 1994 La Tâche Grand Cru does not transcend the limitations of this challenging vintage, offering up a rather pedestrian bouquet of red-black fruit and licorice, becoming more and more dominated by its lavish application of high-quality new oak as it sits in the glass and never revealing any of the aromatic drama of which La Tâche is capable. On the palate, the wine is chunky and foursquare, with bright acids and a certain tannic asperity that suggests this is unlikely to change in any critical respect in the foreseeable future.",
    rp_reviewer: "William Kelley",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2018 - 2025",
    market_value: "30500.00",
    tags: "NA",
    processed_case: 6,
    bottle_size: "0750",
    mean: 30500.0,
    median: 30500.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 27,
    lwin7: "1028704",
    name: "DRC, La Tache Grand Cru (Romanee)",
    fromm: "Burgundy",
    red_wine: "Savory and Classic",
    grapes: "Pinot Noir",
    pair_with: "Duck, Goose and Game Birds",
    region_of_appellation: "NA",
    alcohol_abv: "13 - 13.5%",
    sweetness: "Dry",
    blend: "100% Pinot Noir",
    maturation: "Oaked",
    ownership: "de Villaine & Leroy Families",
    closure_type: "Cork",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    region:
      "La Tâche is a prestigious Grand Cru monopole vineyard in Vosne-Romanée, exclusively owned by Domaine de la Romanée-Conti (DRC) since 1933. Covering 6.06 hectares, it is over three times larger than Romanée-Conti. Its terroir features pebbly limestone soils, with thinner, free-draining soils on higher slopes and more clay at the base, allowing for complex, structured Pinot Noir wines. Known for power and elegance, La Tâche is farmed organically and produces wines celebrated for their depth, aging potential, and remarkable balance.",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRCLaTacheGrandCruRedWine.png",
    ],
    annual_production: 2000,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare380 = {
  investment_id: 380,
  case_size: 1,
  quantity: 1,
  market_value: 1862.0,
  is_owner: false,
  wine_vintage_details: {
    id: 1853,
    name: "1992 Domaine de la Romanée-Conti Richebourg Grand Cru",
    lwin11: "10286741992",
    vintage: 1992,
    rp_score: "83",
    release_price: "2721",
    rp_released: "NA",
    rp_tasting_notes: "NA",
    rp_reviewer: "Wine Spectator",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2007 - 2028",
    market_value: "1862.00",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 0.0,
    median: 0.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 28,
    lwin7: "1028674",
    name: "DRC, Richebourg Grand Cru (Romanee)",
    fromm: "Burgundy",
    red_wine: "Savory and Classic",
    grapes: "Pinot Noir",
    pair_with: "Duck, Goose and Game Birds",
    region_of_appellation: "NA",
    alcohol_abv: "13 - 13.5%",
    sweetness: "Dry",
    blend: "100% Pinot Noir",
    maturation: "Oaked",
    ownership: "de Villaine & Leroy Families",
    closure_type: "Cork",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    region:
      "Richebourg is a prestigious Grand Cru vineyard in Vosne-Romanée, producing some of Burgundy’s most opulent Pinot Noir wines, known for dense fruit, earthy complexity, and exceptional ageing potential. Covering 8 hectares, it consists of two lieux-dits: Les Richebourgs (warmer, denser wines) and Les Véroilles (cooler, more mineral-driven wines). Its well-drained pebbly clay and limestone soils contribute to rich, structured wines. Domaine de la Romanée-Conti is the largest owner, alongside Domaine Leroy and Anne Gros. Henri Jayer’s rare Richebourg wines remain highly prized.",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Richebourg.png"],
    annual_production: 1200,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare381 = {
  investment_id: 381,
  case_size: 3,
  quantity: 1,
  market_value: 10500.0,
  is_owner: false,
  wine_vintage_details: {
    id: 526,
    name: "2015 Domaine de la Romanée-Conti Richebourg Grand Cru",
    lwin11: "10286742015",
    vintage: 2015,
    rp_score: "96",
    release_price: "312",
    rp_released: "Mar 01, 2018",
    rp_tasting_notes:
      "The 2015 Richebourg Grand Cru is very good indeed, offering up a pure and surprisingly expressive nose of strawberry, dried rose, plum preserve, roast squab, raw cocoa and incipient rich soil tones, framed by some nutty new oak. On the palate, the wine is full-bodied, multidimensional and rich, sweet fruit playing in counterpoint with sapid, savory nuance. This Richebourg is denser at the core and less expansive than the corresponding Romanée-St-Vivant, and though the grain of its tannins is similar, their impact is more assertive and muscular. Cropped at 24 hectoliters per hectare and harvested September 8 and 9.",
    rp_reviewer: "William Kelley",
    holding_years: "0",
    liv_ex_value: 35018.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2025 - 2050",
    market_value: "10500.00",
    tags: "NA",
    processed_case: 3,
    bottle_size: "0750",
    mean: 10930.6,
    median: 10500.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 28,
    lwin7: "1028674",
    name: "DRC, Richebourg Grand Cru (Romanee)",
    fromm: "Burgundy",
    red_wine: "Savory and Classic",
    grapes: "Pinot Noir",
    pair_with: "Duck, Goose and Game Birds",
    region_of_appellation: "NA",
    alcohol_abv: "13 - 13.5%",
    sweetness: "Dry",
    blend: "100% Pinot Noir",
    maturation: "Oaked",
    ownership: "de Villaine & Leroy Families",
    closure_type: "Cork",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    region:
      "Richebourg is a prestigious Grand Cru vineyard in Vosne-Romanée, producing some of Burgundy’s most opulent Pinot Noir wines, known for dense fruit, earthy complexity, and exceptional ageing potential. Covering 8 hectares, it consists of two lieux-dits: Les Richebourgs (warmer, denser wines) and Les Véroilles (cooler, more mineral-driven wines). Its well-drained pebbly clay and limestone soils contribute to rich, structured wines. Domaine de la Romanée-Conti is the largest owner, alongside Domaine Leroy and Anne Gros. Henri Jayer’s rare Richebourg wines remain highly prized.",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Richebourg.png"],
    annual_production: 1200,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare382 = {
  investment_id: 382,
  case_size: 1,
  quantity: 1,
  market_value: 15950.0,
  is_owner: false,
  wine_vintage_details: {
    id: 549,
    name: "2016 Domaine de la Romanée-Conti Romanée-Conti Grand Cru",
    lwin11: "10286872016",
    vintage: 2016,
    rp_score: "98",
    release_price: "-13",
    rp_released: "Jan, 2019",
    rp_tasting_notes:
      "The 2016 Romanée-Conti Grand Cru was picked on September 25 at 24hL/ha. As usual, I allowed it five or six minutes to open in the glass. It is a very subtle Romanée-Conti, more discreet than the 2016 La Tâche, but then you become entranced by its spellbinding purity and grace. It gradually builds aromatically, augmenting the black fruit with red, and developing scents of wild hedgerow and freshly tilled soil - almost a pastoral element. The palate is medium-bodied with extremely precise and fine tannin and notes of wild strawberry, cranberry and crushed limestone. This feels very harmonious, the texture silkier than the La Tâche, displaying just a touch of bay leaf and black pepper toward the sustained finish, which gains depth and grip with aeration. Exquisite, though I suspect the La Tâche will challenge it for supremacy. 440 cases produced. Tasted at Corney & Barrow’s annual in-bottle tasting in London.",
    rp_reviewer: "Neal Martin",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2026 - 2060",
    market_value: "15950.00",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 19815.3,
    median: 17578.61,
    is_user_investment: true,
  },
  wine_parent: {
    id: 29,
    lwin7: "1028687",
    name: "DRC, Romanee-Conti Grand Cru",
    fromm: "Burgundy",
    red_wine: "Savory and Classic",
    grapes: "Pinot Noir",
    pair_with: "Duck, Goose and Game Birds",
    region_of_appellation: "NA",
    alcohol_abv: "13 - 13.5%",
    sweetness: "Dry",
    blend: "100% Pinot Noir",
    maturation: "Oaked",
    ownership: "de Villaine & Leroy Families",
    closure_type: "Cork",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    region:
      "Romanée-Conti, a Grand Cru vineyard in Vosne-Romanée, is one of the world’s most prestigious and exclusive wine estates. Owned solely by Domaine de la Romanée-Conti (DRC), its 1.81 hectares produce fewer than 500 cases annually of exceptional Pinot Noir, famed for elegance, depth, and ageing potential. Its ideal terroir—limestone-rich soils and an easterly slope—yields highly sought-after wines, commanding tens of thousands of dollars per bottle. Romanée-Conti’s rarity and prestige make it both the most coveted and counterfeited wine globally.",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Romanee_Conti.png",
    ],
    annual_production: 500,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare444 = {
  investment_id: 444,
  case_size: 1,
  quantity: 1,
  market_value: 17000.0,
  is_owner: false,
  wine_vintage_details: {
    id: 551,
    name: "2018 Domaine de la Romanée-Conti Romanée-Conti Grand Cru",
    lwin11: "10286872018",
    vintage: 2018,
    rp_score: "96 - 98",
    release_price: "3",
    rp_released: "Nov, 2019",
    rp_tasting_notes:
      'The 2018 Romanée-Conti Grand Cru sports a limpid ruby color. It is quintessential "RC" on the nose, which features crystalline scents of wild strawberry and cranberry fruit, crushed limestone, oyster shell and pressed rose petal. With aeration there is even a suggestion of crushed flint. The palate is medium-bodied with super-fine tannins that frame the ethereal red fruit. Understated yet imbued with stunning elegance. The finish seems to go on forever. Remarkable.',
    rp_reviewer: "Neal Martin",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2026 - 2055",
    market_value: "51000.00",
    tags: "NA",
    processed_case: 3,
    bottle_size: "0750",
    mean: 114000.0,
    median: 114000.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 29,
    lwin7: "1028687",
    name: "DRC, Romanee-Conti Grand Cru",
    fromm: "Burgundy",
    red_wine: "Savory and Classic",
    grapes: "Pinot Noir",
    pair_with: "Duck, Goose and Game Birds",
    region_of_appellation: "NA",
    alcohol_abv: "13 - 13.5%",
    sweetness: "Dry",
    blend: "100% Pinot Noir",
    maturation: "Oaked",
    ownership: "de Villaine & Leroy Families",
    closure_type: "Cork",
    grape_variety:
      "Pinot Noir is a highly revered and complex red grape variety, known for producing elegant, aromatic wines with flavours of red berries, cherries, and earthy undertones. Its thin skin results in lighter colour and softer tannins, making it versatile yet challenging to cultivate. Burgundy, particularly Côte de Nuits, is its spiritual home, though it thrives globally in regions like Oregon, California, and New Zealand. Pinot Noir pairs beautifully with dishes like roast duck, salmon, and creamy pastas, reflecting its refined yet adaptable character.",
    region:
      "Romanée-Conti, a Grand Cru vineyard in Vosne-Romanée, is one of the world’s most prestigious and exclusive wine estates. Owned solely by Domaine de la Romanée-Conti (DRC), its 1.81 hectares produce fewer than 500 cases annually of exceptional Pinot Noir, famed for elegance, depth, and ageing potential. Its ideal terroir—limestone-rich soils and an easterly slope—yields highly sought-after wines, commanding tens of thousands of dollars per bottle. Romanée-Conti’s rarity and prestige make it both the most coveted and counterfeited wine globally.",
    winery:
      "Domaine de la Romanée-Conti (DRC) is Burgundy's most prestigious and collectible wine estate, based in Vosne-Romanée. It produces world-renowned Pinot Noir wines from eight Grand Cru vineyards, including the legendary Romanée-Conti, La Tâche, and Richebourg. DRC also crafts exclusive Chardonnay from Montrachet. With limited production—only 6,000 bottles of Romanée-Conti annually—its wines are highly sought after and often fetch record prices at auction. Co-owned by the de Villaine and Leroy families, DRC remains a symbol of excellence and authenticity in fine wine.",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Romanee_Conti.png",
    ],
    annual_production: 500,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare190 = {
  investment_id: 190,
  case_size: 6,
  quantity: 1,
  market_value: 812.52,
  is_owner: false,
  wine_vintage_details: {
    id: 924,
    name: "2009 Pol Roger Cuvée Sir Winston Churchill",
    lwin11: "10828612009",
    vintage: 2009,
    rp_score: "96",
    release_price: "19",
    rp_released: "Mar 10, 2023",
    rp_tasting_notes:
      "A few years after its disgorgment now, the 2009 Cuvée Sir Winston Churchill has digested its dosage and is beginning to offer up real complexity. Mingling aromas of freshly baked bread, honeycomb, crisp peach, pear and subtle hints of dried fruits, it's medium to full-bodied, sapid and vinous, with bright acids, a pearly mousse and a long, saline finish. Exhibiting more structure than was apparent on release, this has always been a very approachable Churchill, yet it is really benefiting from age.",
    rp_reviewer: "William Kelley",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2022 - 2040",
    market_value: "135.42",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 978.68,
    median: 935.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 47,
    lwin7: "1082861",
    name: "Pol Roger, Sir Winston Churchill",
    fromm: "Champagne",
    red_wine: "Sparkling Wine – Complex and Traditional",
    grapes: "Champagne Blend",
    pair_with: "Shellfish, Crab and Lobster",
    region_of_appellation: "NA",
    alcohol_abv: "12 - 12.5%",
    sweetness: "Dry",
    blend: "Pinot Noir & Chardonnay",
    maturation: "NA",
    ownership: "NA",
    closure_type: "Cork",
    grape_variety:
      "The Champagne Blend traditionally combines Pinot Noir, Chardonnay, and Pinot Meunier, creating balanced sparkling wines. Pinot Noir adds structure and red fruit notes, Chardonnay brings elegance and aging potential, and Meunier contributes bright, fruity flavors. This blend thrives in cool climates like Champagne, California, and Tasmania. Outside Champagne, Pinot Meunier is less common. Popular food pairings include smoked salmon terrine, pork and prawn dumplings, and fried chicken with chili mayo, complementing the wine's crisp, vibrant profile.",
    region:
      'Champagne Brut is a dry, sparkling wine from France\'s Champagne region. It can be white or rosé and is typically made from the classic blend of Chardonnay, Pinot Noir, and Pinot Meunier, though it may also include lesser-known varieties like Pinot Blanc, Pinot Gris, Petit Meslier, and Arbane. The term "Brut" means "raw," indicating minimal added sugar (dosage) during production. By law, Brut Champagne contains less than 15g/L of sugar. Drier styles include Brut Nature (0–3g/L) and Extra Brut (0–6g/L). Introduced by Perrier-Jouët in 1846 for the British market, Brut has become the most popular Champagne style today, surpassing sweeter versions like Sec, Demi-Sec, and Doux.',
    winery:
      "Champagne Pol Roger, founded in 1849 in Épernay, is renowned for its elegant, balanced style crafted from equal parts Chardonnay, Pinot Noir, and Pinot Meunier. Its portfolio includes Brut Réserve, Vintage Brut, Demi-Sec, Brut Nature, Rosé, and Blanc de Blancs. The prestigious Cuvée Sir Winston Churchill, launched in 1975, features a Pinot Noir-dominant blend with Chardonnay. Pol Roger owns 89 hectares of vineyards and produces around 1.8 million bottles annually, emphasizing handcrafting and deep cellar aging.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Pol_Roger.png"],
    annual_production: 6000,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare193 = {
  investment_id: 193,
  case_size: 6,
  quantity: 1,
  market_value: 829.98,
  is_owner: false,
  wine_vintage_details: {
    id: 1811,
    name: "2020 Leoville Las Cases",
    lwin11: "10123742020",
    vintage: 2020,
    rp_score: "97+",
    release_price: "-30",
    rp_released: "Apr 06, 2023",
    rp_tasting_notes:
      "The 2020 Léoville Las Cases is a classic in the making, unwinding in the glass with aromas of cherries, cassis, loamy soil, violets and dark chocolate framed by a discreet touch of new oak. Full-bodied, broad and layered, it's rich and concentrated, with a deep core of fruit framed by sweet, powdery tannins and lively acids. Concluding with a long, resonant finish, it's built for the cellar.",
    rp_reviewer: "William Kelley",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2030 - 2060",
    market_value: "138.33",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 936.45,
    median: 925.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 58,
    lwin7: "1012374",
    name: "Leoville Las Cases",
    fromm: "Bordeaux",
    red_wine: "Savory and Classic",
    grapes: "Bordeaux Blend Red",
    pair_with: "Beef and Venison",
    region_of_appellation: "NA",
    alcohol_abv: "13.8%",
    sweetness: "Dry",
    blend: "85% Cabernet Sauvignon, 9% Cabernet Franc & 6% Merlot",
    maturation: "Oaked",
    ownership: "Domaines Delon",
    closure_type: "Corked",
    grape_variety:
      'The term "Bordeaux Blend", whilst not legally defined, is widely used to describe wines that combine traditional Bordeaux grape varieties, primarily Cabernet Sauvignon and Merlot. Unlike its American counterpart "Meritage", it lacks official recognition but serves as a useful international reference for Bordeaux-style red wines. These blends are characterised by powerful structure, deep fruit flavours, and firm tannins. Though originating in France, the style has spread globally, with vineyards worldwide crafting their interpretations. The term\'s flexibility is both its strength and potential weakness.',
    region:
      "Saint-Julien, a small but esteemed Left Bank Bordeaux appellation, lacks a first growth but compensates with 11 classed growths, including five top-rated second growths. It lies between Pauillac and Margaux, covering 900 hectares, with vineyards split between Saint-Julien-Beychevelle and Beychevelle. Saint-Julien wines are mainly Cabernet Sauvignon-based blends, governed by strict appellation laws since 1936. Despite its modest size, it attracts significant investment and produces consistently high-quality wines distinct from neighbouring Pauillac yet equally collectible.",
    winery:
      "Château Léoville-Las Cases, a second growth estate in Bordeaux's Saint-Julien appellation, is Cabernet Sauvignon-dominant with Merlot and Cabernet Franc. Originally part of a larger estate, it was divided in the 18th and 19th centuries, creating Léoville-Barton and Léoville-Poyferré. Covering 98 hectares, its gravel and clay soils benefit from the Gironde's moderating influence. The estate produces three wines, including Le Petit Lion du Marquis de Las Cases. Owned by Domaines Delon, it also manages Château Potensac and Château Nénin.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Vin_De_Leoville.png"],
    annual_production: 18000,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare384 = {
  investment_id: 384,
  case_size: 3,
  quantity: 1,
  market_value: 8437.0,
  is_owner: false,
  wine_vintage_details: {
    id: 907,
    name: "2018 Pétrus",
    lwin11: "10140332018",
    vintage: 2018,
    rp_score: "100",
    release_price: "47",
    rp_released: "Mar 31, 2021",
    rp_tasting_notes:
      "The 2018 Petrus has retained its opaque purple-black color after bottling, foreshadowing the seemingly frozen-in-time glacial pace at which this wine is proceeding. It opens very reluctantly, requiring considerable air with vigorous swirling and doggedly demands a few hours before it offers glimpses at this slumbering giant of a wine. As it eventually unfurls, it slowly morphs into a powerful, fantastically pure nose of preserved plums, blackberry preserves and blueberry compote, followed by nuances of molten licorice, dark chocolate, black truffles, iron ore and, still later, floral notions of lilacs and rose oil come through. The full-bodied palate is taut, muscular and oh-so-tightly wound at this stage, revealing peeks at many, many layers of perfectly ripe black and blue fruits, exotic spices and earthy notions for which words simply fail. The texture is at once rock solid and fantastically plush, with impeccably knit freshness, finishing so long you really can't taste or think of anything else for the rest of the day. Here is a heart-stopping titan that puts paid to all those naysayers who contest that perfection in wine cannot exist. It will require a good 8-10 years to hit its stride, then it is very likely to outlive us all, but you will want to make certain you drink this one before you go.",
    rp_reviewer: "Lisa Perrotti-Brown",
    holding_years: "0",
    liv_ex_value: 36346.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2029 - 2080",
    market_value: "16874.00",
    tags: "NA",
    processed_case: 6,
    bottle_size: "0750",
    mean: 23820.21,
    median: 22786.95,
    is_user_investment: true,
  },
  wine_parent: {
    id: 46,
    lwin7: "1014033",
    name: "Petrus, Pomerol",
    fromm: "Bordeaux",
    red_wine: "Red Wine – Savory and Classic",
    grapes: "Merlot",
    pair_with: "Beef and Venison",
    region_of_appellation: "NA",
    alcohol_abv: "14.50%",
    sweetness: "Dry",
    blend: "Merlot",
    maturation: "NA",
    ownership: "Jean-Francois Moueix",
    closure_type: "Cork",
    grape_variety:
      "Merlot is the world’s second most-planted red grape, prized for its smooth, plush texture and flavours of plum and black cherry. It thrives globally, notably in Bordeaux's Pomerol and Saint-Émilion, where it achieves depth and structure. Softer and less tannic than Cabernet Sauvignon, Merlot is used in blends and as a varietal wine, with Petrus being its most iconic example. Its versatility pairs well with roasted meats, spicy dishes, and barbecues, making it a widely enjoyed and adaptable wine choice.",
    region:
      "Pomerol, an unclassified yet esteemed Bordeaux appellation, stands apart for its Merlot-dominated wines, known for their richness and early approachability. Located near Saint-Émilion, its 792-hectare vineyard features diverse soils, with the finest wines produced on the clay-rich eastern plateau. Iconic producers like Pétrus, Lafleur, and Le Pin elevate Pomerol’s prestige. Though small and lacking a formal classification system, its limited production and growing global demand ensure Pomerol's prominence in the wine world.",
    winery:
      "Petrus is Pomerol’s most prestigious estate and one of Bordeaux's most iconic wines. Its 11.4-hectare vineyard, dominated by Merlot, produces rich, powerful wines with notes of chocolate, spice, and black fruit. The vineyard’s unique blue clay soils enhance the wine’s soft yet abundant tannins. Owned by the Moueix family since 1962, Petrus commands some of the highest global prices. Grapes are meticulously hand-harvested, fermented in concrete vats, and aged 18–20 months in 50% new oak before unfiltered bottling.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Petrus.png"],
    annual_production: 3000,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare7 = {
  investment_id: 7,
  case_size: 6,
  quantity: 1,
  market_value: 18391.2,
  is_owner: false,
  wine_vintage_details: {
    id: 899,
    name: "2010 Pétrus",
    lwin11: "10140332010",
    vintage: 2010,
    rp_score: "100",
    release_price: "54",
    rp_released: "Mar 06, 2020",
    rp_tasting_notes:
      "Deep garnet colored, the 2010 Petrus opens a little broody, with gentle crushed rocks, cast iron pan and fragrant earth notions giving way to a core plum preserves, baked blueberries, licorice and Black Forest cake plus wafts of pencil shavings, garrigue and violets. Full-bodied, the palate is beautifully poised with a firm line of exquisitely ripe, fine-grained tannins and fantastic freshness bolstering the generous fruit, finishing very long and very, very classy. Collectors fortunate enough to have a few bottles of this vintage are advised to be patient and allow it a further 7-10 years to loosen-up and emerge gloriously from this rock-solid structure.",
    rp_reviewer: "Lisa Perrotti-Brown",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2027 - 2070",
    market_value: "3065.20",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 19585.67,
    median: 18750.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 46,
    lwin7: "1014033",
    name: "Petrus, Pomerol",
    fromm: "Bordeaux",
    red_wine: "Red Wine – Savory and Classic",
    grapes: "Merlot",
    pair_with: "Beef and Venison",
    region_of_appellation: "NA",
    alcohol_abv: "14.50%",
    sweetness: "Dry",
    blend: "Merlot",
    maturation: "NA",
    ownership: "Jean-Francois Moueix",
    closure_type: "Cork",
    grape_variety:
      "Merlot is the world’s second most-planted red grape, prized for its smooth, plush texture and flavours of plum and black cherry. It thrives globally, notably in Bordeaux's Pomerol and Saint-Émilion, where it achieves depth and structure. Softer and less tannic than Cabernet Sauvignon, Merlot is used in blends and as a varietal wine, with Petrus being its most iconic example. Its versatility pairs well with roasted meats, spicy dishes, and barbecues, making it a widely enjoyed and adaptable wine choice.",
    region:
      "Pomerol, an unclassified yet esteemed Bordeaux appellation, stands apart for its Merlot-dominated wines, known for their richness and early approachability. Located near Saint-Émilion, its 792-hectare vineyard features diverse soils, with the finest wines produced on the clay-rich eastern plateau. Iconic producers like Pétrus, Lafleur, and Le Pin elevate Pomerol’s prestige. Though small and lacking a formal classification system, its limited production and growing global demand ensure Pomerol's prominence in the wine world.",
    winery:
      "Petrus is Pomerol’s most prestigious estate and one of Bordeaux's most iconic wines. Its 11.4-hectare vineyard, dominated by Merlot, produces rich, powerful wines with notes of chocolate, spice, and black fruit. The vineyard’s unique blue clay soils enhance the wine’s soft yet abundant tannins. Owned by the Moueix family since 1962, Petrus commands some of the highest global prices. Grapes are meticulously hand-harvested, fermented in concrete vats, and aged 18–20 months in 50% new oak before unfiltered bottling.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Petrus.png"],
    annual_production: 3000,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare378 = {
  investment_id: 378,
  case_size: 1,
  quantity: 1,
  market_value: 400.0,
  is_owner: false,
  wine_vintage_details: {
    id: 1803,
    name: "2018 Tenuta San Guido Bolgheri Sassicaia",
    lwin11: "110203720181",
    vintage: 2018,
    rp_score: "97+",
    release_price: "167",
    rp_released: "Jan 15, 2021",
    rp_tasting_notes:
      "This is a classic vintage of an Italian icon now celebrating its 50th vintage. The Tenuta San Guido 2018 Bolgheri Sassicaia lays out a familiar blueprint that borrows from the proven track record of this landmark estate that extends into the hills just beyond the Tyrrhenian shores of Tuscany. This vintage is crystalline and pure in its delivery, and if you are familiar with previous editions, it is impossible to mistake this wine for anything but Sassicaia. The growing season started off cool and wet but turned to warm and dry conditions comfortably before the harvest. Cabernet Sauvignon with Cabernet Franc in a supporting role deliver a graceful mid-weight texture that holds back style-wise in terms of phenolic density. The wine's careful balance is achieved thanks to the nuanced character of the fruit, the present acidity, the well-managed structure and the contained alcohol. The palate is lifted and bright, the finish is polished and long, and the wine skips over any heaviness on the mid-palate. The bouquet is especially intriguing with a very lively plummy fruit element that is enhanced by baker's chocolate, pepper spice, iron ore, caramel and pie crust. There is also a green character that adds positively to the bouquet with aniseed, tea leaf, soya, menthol rub and black olive. The fruit maturity is spot-on with no elements that feel over or underripe. Overall, the 2018 Sassicaia weighs in with a svelte frame and long persistence. Moreover, it is distinguished by the archetypal elegance and pedigree of the classic vintages of the past. This new release gives you much pleasure to await.",
    rp_reviewer: "Monica Larner",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: false,
    size: "NA",
    status: "NA",
    drinking_window: "2024 - 2045",
    market_value: "400.00",
    tags: "NA",
    processed_case: 1,
    bottle_size: "1500",
    mean: 0.0,
    median: 0.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 50,
    lwin7: "1102037",
    name: "Sassicaia, Tenuta San Guido, Bolgheri",
    fromm: "Italy",
    red_wine: "Red Wine – Bold and Structured",
    grapes: "Cabernet Franc - Cabernet Sauvignon",
    pair_with: "Beef and Venison",
    region_of_appellation: "NA",
    alcohol_abv: "13.50%",
    sweetness: "Dry",
    blend: "Cabernet Sauvignon",
    maturation: "85% Cabernet Sauvignon & 15% Cabernet Franc",
    ownership: "Nicolò Incisa della Rocchetta",
    closure_type: "Cork",
    grape_variety:
      "Cabernet Sauvignon and Cabernet Franc are key Bordeaux grapes, often blended with Merlot. Typically, Cabernet Sauvignon provides structure and complex aromas (cassis, cedar, tobacco), while Cabernet Franc adds floral, spicy notes. Though usually dominant, Cabernet Sauvignon is less so in the Loire Valley. In Tuscany, the blend shines in the famed Super Tuscan Sassicaia; in California, Meritage blends benefit from Cabernet Franc’s earlier ripening. Great pairings: sautéed pork chops, wild-mushroom ragu, and lamb shawarma.",
    region:
      "Bolgheri is a prestigious yet young Italian appellation in Tuscany’s Maremma, famed for its deep, ageworthy red wines primarily made from Bordeaux varieties like Cabernet Sauvignon and Cabernet Franc. Once dismissed as swampy, the region gained renown after Sassicaia’s 1978 Decanter tasting win. Today, Bolgheri produces notable reds—including Bolgheri Rosso and the Sassicaia DOC subzone—as well as crisp whites such as Bolgheri Bianco, while wine tourism thrives with attractions like the World Wine Town.",
    winery:
      "Tenuta San Guido, in Tuscany’s Maremma, is best known for its flagship wine, Sassicaia—a pioneering Super Tuscan. Created in the 1940s by Marchese Mario Incisa to rival Bordeaux, Sassicaia blends primarily Cabernet Sauvignon with a hint of Cabernet Franc, offering elegance, perfume, and a supple texture. The grapes are picked early, fermented in stainless steel, and aged 24 months in French oak. The estate also produces Guidalberto and Le Difese, further highlighting its innovative winemaking.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/sassicaia.png"],
    annual_production: 20000,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare191 = {
  investment_id: 191,
  case_size: 6,
  quantity: 1,
  market_value: 1847.46,
  is_owner: false,
  wine_vintage_details: {
    id: 980,
    name: "2016 Tenuta San Guido Bolgheri Sassicaia",
    lwin11: "11020372016",
    vintage: 2016,
    rp_score: "100",
    release_price: "71",
    rp_released: "Jan 18, 2019",
    rp_tasting_notes:
      "The 2016 Bolgheri Sassicaia is a wine of soaring achievement. I tasted this wine several times during the course of its creation in both barrel and bottle, and the highly deserved 100-point score you see here was enthusiastically assigned at the conclusion of a mini vertical in which I tasted and compared the 2016 vintage against 2015 (which I scored 97 points). It makes perfect sense to present these two excellent vintages in back-to-back comparison fashion because they are two of the best to emerge from Bolgheri, and indeed Tenuta San Guido, in recent memory. These are very similar vintages with long, hot summer months that fueled a long growing season. There was a bit more rain in 2016, and in analytical terms this vintage has a tad more acidity. However, the results in the glass are extraordinarily different. The 2015 vintage is exuberant, round, succulent and immediate, whereas the 2016 vintage shows pinpoint sharpness and precision (with similar grit and texture at the back). That acidity will carry it long into the future as the wine completes its slow evolutionary course. This wine is chiseled and sharp with blackberry, ripe cherry, grilled herb and barbecue spice. The aromas flow from the glass in a continuous stream and are all marked by radiant intensity. The mouthfeel is long and powerful. The crisp linearity of the wine's tannic backbone is perfectly measured to the volume and depth of the fruit flavors. To my mind, the 2016 Sassicaia stands tall next to the epic 1985 vintage that set the ultimate benchmark for vino italiano.",
    rp_reviewer: "Monica Larner",
    holding_years: "0",
    liv_ex_value: 2500.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2021 - 2050",
    market_value: "307.91",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 2023.78,
    median: 1950.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 50,
    lwin7: "1102037",
    name: "Sassicaia, Tenuta San Guido, Bolgheri",
    fromm: "Italy",
    red_wine: "Red Wine – Bold and Structured",
    grapes: "Cabernet Franc - Cabernet Sauvignon",
    pair_with: "Beef and Venison",
    region_of_appellation: "NA",
    alcohol_abv: "13.50%",
    sweetness: "Dry",
    blend: "Cabernet Sauvignon",
    maturation: "85% Cabernet Sauvignon & 15% Cabernet Franc",
    ownership: "Nicolò Incisa della Rocchetta",
    closure_type: "Cork",
    grape_variety:
      "Cabernet Sauvignon and Cabernet Franc are key Bordeaux grapes, often blended with Merlot. Typically, Cabernet Sauvignon provides structure and complex aromas (cassis, cedar, tobacco), while Cabernet Franc adds floral, spicy notes. Though usually dominant, Cabernet Sauvignon is less so in the Loire Valley. In Tuscany, the blend shines in the famed Super Tuscan Sassicaia; in California, Meritage blends benefit from Cabernet Franc’s earlier ripening. Great pairings: sautéed pork chops, wild-mushroom ragu, and lamb shawarma.",
    region:
      "Bolgheri is a prestigious yet young Italian appellation in Tuscany’s Maremma, famed for its deep, ageworthy red wines primarily made from Bordeaux varieties like Cabernet Sauvignon and Cabernet Franc. Once dismissed as swampy, the region gained renown after Sassicaia’s 1978 Decanter tasting win. Today, Bolgheri produces notable reds—including Bolgheri Rosso and the Sassicaia DOC subzone—as well as crisp whites such as Bolgheri Bianco, while wine tourism thrives with attractions like the World Wine Town.",
    winery:
      "Tenuta San Guido, in Tuscany’s Maremma, is best known for its flagship wine, Sassicaia—a pioneering Super Tuscan. Created in the 1940s by Marchese Mario Incisa to rival Bordeaux, Sassicaia blends primarily Cabernet Sauvignon with a hint of Cabernet Franc, offering elegance, perfume, and a supple texture. The grapes are picked early, fermented in stainless steel, and aged 24 months in French oak. The estate also produces Guidalberto and Le Difese, further highlighting its innovative winemaking.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/sassicaia.png"],
    annual_production: 20000,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare546 = {
  investment_id: 546,
  case_size: 6,
  quantity: 1,
  market_value: 1081.2,
  is_owner: false,
  wine_vintage_details: {
    id: 983,
    name: "2019 Tenuta San Guido Bolgheri Sassicaia",
    lwin11: "11020372019",
    vintage: 2019,
    rp_score: "98",
    release_price: "9",
    rp_released: "Jan 14, 2022",
    rp_tasting_notes:
      "The latest release from Tenuta San Guido is the 2019 Bolgheri Sassicaia. The bouquet is up front and very expressive from the get-go. It offers a generous display of crunchy, dark cherry that hints at the extra concentration and fruit weight obtained in the 2019 growing season. This vintage will be remembered for the crisp richness of the fruit and its important textural imprint. It also shows fine elegance, bordering on the ethereal, with berry aromas, tarry earth and brushes of balsam herb or grilled rosemary. Sassicaia always shows an almost-glossy finely knit quality to the polished mouthfeel, and I find it again here next to fresh acidity and firm tannins. Mouthfeel in 2019 is the wine's strongest suit. The 2019 is one of the prettiest and most balanced editions of Sassicaia we've seen this past decade, along with the back-to-back duo of 2016 and 2015. The 2019 marries the precision of the 2016 with the rich fruit weight of the 2015.",
    rp_reviewer: "Monica Larner",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2025 - 2055",
    market_value: "180.20",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 1278.39,
    median: 1200.0,
    is_user_investment: true,
  },
  wine_parent: {
    id: 50,
    lwin7: "1102037",
    name: "Sassicaia, Tenuta San Guido, Bolgheri",
    fromm: "Italy",
    red_wine: "Red Wine – Bold and Structured",
    grapes: "Cabernet Franc - Cabernet Sauvignon",
    pair_with: "Beef and Venison",
    region_of_appellation: "NA",
    alcohol_abv: "13.50%",
    sweetness: "Dry",
    blend: "Cabernet Sauvignon",
    maturation: "85% Cabernet Sauvignon & 15% Cabernet Franc",
    ownership: "Nicolò Incisa della Rocchetta",
    closure_type: "Cork",
    grape_variety:
      "Cabernet Sauvignon and Cabernet Franc are key Bordeaux grapes, often blended with Merlot. Typically, Cabernet Sauvignon provides structure and complex aromas (cassis, cedar, tobacco), while Cabernet Franc adds floral, spicy notes. Though usually dominant, Cabernet Sauvignon is less so in the Loire Valley. In Tuscany, the blend shines in the famed Super Tuscan Sassicaia; in California, Meritage blends benefit from Cabernet Franc’s earlier ripening. Great pairings: sautéed pork chops, wild-mushroom ragu, and lamb shawarma.",
    region:
      "Bolgheri is a prestigious yet young Italian appellation in Tuscany’s Maremma, famed for its deep, ageworthy red wines primarily made from Bordeaux varieties like Cabernet Sauvignon and Cabernet Franc. Once dismissed as swampy, the region gained renown after Sassicaia’s 1978 Decanter tasting win. Today, Bolgheri produces notable reds—including Bolgheri Rosso and the Sassicaia DOC subzone—as well as crisp whites such as Bolgheri Bianco, while wine tourism thrives with attractions like the World Wine Town.",
    winery:
      "Tenuta San Guido, in Tuscany’s Maremma, is best known for its flagship wine, Sassicaia—a pioneering Super Tuscan. Created in the 1940s by Marchese Mario Incisa to rival Bordeaux, Sassicaia blends primarily Cabernet Sauvignon with a hint of Cabernet Franc, offering elegance, perfume, and a supple texture. The grapes are picked early, fermented in stainless steel, and aged 24 months in French oak. The estate also produces Guidalberto and Le Difese, further highlighting its innovative winemaking.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/sassicaia.png"],
    annual_production: 20000,
    default_case_size: 12,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare545 = {
  investment_id: 545,
  case_size: 6,
  quantity: 1,
  market_value: 608.52,
  is_owner: false,
  wine_vintage_details: {
    id: 1071,
    name: "2019 Marchesi Antinori Tignanello",
    lwin11: "10953912019",
    vintage: 2019,
    rp_score: "96",
    release_price: "22",
    rp_released: "Jun 30, 2022",
    rp_tasting_notes:
      "The Marchesi Antinori 2019 Tignanello was born in a classic growing season that saw some cooling summer rains and relatively stress-free conditions. This is an elegant and extremely polished wine made with mostly Sangiovese and smaller parts Cabernet Sauvignon and Cabernet Franc. Here too, the small blending element of Cabernet Franc has been slowly increasing in recent years. The 2019 vintage was born with a good amount of power and tannic structure, and maceration times were slightly reduced as a result. This less extractive approach shapes a polished and elegant wine with plenty of bright berry fruit, cherry, dried mint, blue flower, blood orange and rusty earth. The palate is more compact and streamlined. It shows beautiful grace. After this, the next vintage to watch is the highly anticipated 2021.",
    rp_reviewer: "Monica Larner",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2024 - 2045",
    market_value: "101.42",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 645.6,
    median: 630.38,
    is_user_investment: true,
  },
  wine_parent: {
    id: 54,
    lwin7: "1095391",
    name: "Tignanello, Toscana",
    fromm: "Italy",
    red_wine: "Red Wine – Bold and Structured",
    grapes: "Cabernet - Sangiovese",
    pair_with: "Beef and Venison",
    region_of_appellation: "NA",
    alcohol_abv: "14%",
    sweetness: "Dry",
    blend: "Sangiovese, Cabernet Sauvignon & Cabernet Franc",
    maturation: "Oaked",
    ownership: "NA",
    closure_type: "Cork",
    grape_variety:
      "In the 1960s and 1970s, Tuscan producers began blending Sangiovese with Cabernet Sauvignon and Cabernet Franc, creating Italy's iconic Super Tuscans. These wines, once labeled as Vino da Tavola, led to the creation of the IGT classification and the Bolgheri DOC in 1994. The blend combines Sangiovese’s cherry and berry flavors with Cabernet’s structure and depth. Popular globally, especially in California, it pairs well with lasagna Bolognese, beef steaks, slow-roasted pork, and mushroom risotto.",
    region:
      "The Indicazione Geografica Tipica (IGT) classification in Tuscany allows winemakers flexibility beyond the stricter DOCG and DOC rules, covering diverse styles from dry whites to sweet reds and sparkling rosés. Introduced in 1992, IGT aimed to legitimize high-quality wines, notably Super Tuscans, which previously bore the low-ranking Vino da Tavola label. Predominantly made from Sangiovese, along with Cabernet Sauvignon, Merlot, and Cabernet Franc, IGT wines now span 13,388 hectares with annual production around 65 million liters, driving Tuscany’s modern wine evolution.",
    winery:
      "Tignanello, a Super Tuscan red wine from Marchesi Antinori, is a blend of Sangiovese, Cabernet Sauvignon and Cabernet Franc, known for its rich complex flavours and elegant structure, and is considered an innovative pioneer of modern italian top wines. Antinori is a prestigious Tuscan wine company and one of Italy's largest producers, with a history dating back to the 14th Century. Known for pioneering innovation in winemaking, Antinori produces around 20 million bottles annually across 150 labels. Its flagship wines include Tignanello, the first to blend Sangiovese with Cabernet Sauvignon and Cabernet Franc, and Solaia, a bold Bordeaux-style blend. Antinori also owns estates like Badia a Passignano, Pian delle Vigne in Montalcino, and Castello della Sala in Umbria.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Tignanello.png"],
    annual_production: 25000,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};

export const WineRare371 = {
  investment_id: 371,
  case_size: 6,
  quantity: 1,
  market_value: 628.98,
  is_owner: false,
  wine_vintage_details: {
    id: 1070,
    name: "2018 Marchesi Antinori Tignanello",
    lwin11: "10953912018",
    vintage: 2018,
    rp_score: "98",
    release_price: "46",
    rp_released: "May 06, 2021",
    rp_tasting_notes:
      "This wine brought to mind precise imagery of tailcoats, striped dress pants, wingtip collar shirts and other gentlemen's fashion choices from the Roaring Twenties. Sporting a retro but classic personality, the Marchesi Antinori 2018 Tignanello is quite the dapper and jovial wine that hits the market just as much of the world is emerging from a dark chapter of lockdowns and coronavirus curfews. I love the optimism that springs bright with such clarity and detail from within this blend of Sangiovese, Cabernet Sauvignon and Cabernet Franc. The 2016 vintage was a benchmark for sure, but I prefer the 2018, thanks to that tinge of nostalgia or emotion that is so deftly rendered in this cool, long growing season. The 2018 vintage offers a deconstructed Tignanello upon first inspection because you can clearly make out the varietal typicity of the grapes, especially the green spice and white pepper of the two Cabernets, along with aromas of crushed limestone that recall the white rocks carefully placed in the vineyards to protect the rows. The wine's fruit weight is contained and polished, and there are no exaggerations, excesses or loose ends. The results are calculated and exacting, especially if you consider the tannic management (with aging in both new and used Hungarian and French oak for up to 16 months) and the quality of the elegant mouthfeel. With time in the glass, those deconstructed elements converge to create unity and balance. The Tignanello vineyard is 57 hectares and sits at a breezy 390 meters above sea level with alberese and galestro soils. Those elevations proved important for shedding excess humidity at the end of this 2018 growing season. Production for this excellent wine is an impressive 345,000 bottles.",
    rp_reviewer: "Monica Larner",
    holding_years: "0",
    liv_ex_value: 0.0,
    is_listed: true,
    size: "NA",
    status: "NA",
    drinking_window: "2023 - 2045",
    market_value: "104.83",
    tags: "NA",
    processed_case: 1,
    bottle_size: "0750",
    mean: 704.34,
    median: 682.5,
    is_user_investment: true,
  },
  wine_parent: {
    id: 54,
    lwin7: "1095391",
    name: "Tignanello, Toscana",
    fromm: "Italy",
    red_wine: "Red Wine – Bold and Structured",
    grapes: "Cabernet - Sangiovese",
    pair_with: "Beef and Venison",
    region_of_appellation: "NA",
    alcohol_abv: "14%",
    sweetness: "Dry",
    blend: "Sangiovese, Cabernet Sauvignon & Cabernet Franc",
    maturation: "Oaked",
    ownership: "NA",
    closure_type: "Cork",
    grape_variety:
      "In the 1960s and 1970s, Tuscan producers began blending Sangiovese with Cabernet Sauvignon and Cabernet Franc, creating Italy's iconic Super Tuscans. These wines, once labeled as Vino da Tavola, led to the creation of the IGT classification and the Bolgheri DOC in 1994. The blend combines Sangiovese’s cherry and berry flavors with Cabernet’s structure and depth. Popular globally, especially in California, it pairs well with lasagna Bolognese, beef steaks, slow-roasted pork, and mushroom risotto.",
    region:
      "The Indicazione Geografica Tipica (IGT) classification in Tuscany allows winemakers flexibility beyond the stricter DOCG and DOC rules, covering diverse styles from dry whites to sweet reds and sparkling rosés. Introduced in 1992, IGT aimed to legitimize high-quality wines, notably Super Tuscans, which previously bore the low-ranking Vino da Tavola label. Predominantly made from Sangiovese, along with Cabernet Sauvignon, Merlot, and Cabernet Franc, IGT wines now span 13,388 hectares with annual production around 65 million liters, driving Tuscany’s modern wine evolution.",
    winery:
      "Tignanello, a Super Tuscan red wine from Marchesi Antinori, is a blend of Sangiovese, Cabernet Sauvignon and Cabernet Franc, known for its rich complex flavours and elegant structure, and is considered an innovative pioneer of modern italian top wines. Antinori is a prestigious Tuscan wine company and one of Italy's largest producers, with a history dating back to the 14th Century. Known for pioneering innovation in winemaking, Antinori produces around 20 million bottles annually across 150 labels. Its flagship wines include Tignanello, the first to blend Sangiovese with Cabernet Sauvignon and Cabernet Franc, and Solaia, a bold Bordeaux-style blend. Antinori also owns estates like Badia a Passignano, Pian delle Vigne in Montalcino, and Castello della Sala in Umbria.",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Tignanello.png"],
    annual_production: 25000,
    default_case_size: 6,
  },
  basket_details: null,
  basket_items: null,
};


// export const WineRare384 = {}
// export const WineRare384 = {}
// export const WineRare384 = {}
// export const WineRare384 = {}
