export const special_volume = [
  {
    id: 21,
    name: "Dom Perignon",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Dom_Perignon_2012.png",
    ],
    price: 350.00,
    fromm: "Champagne",
    vintage: 2008,
    bottle_size: ["1500"],
    annual_production: 25000,
    default_case_size: 6,
  },
  {
    id: 42,
    name: "Louis Roederer, Cristal",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Louis_Roederer_Cristal.png",
    ],
    price: 5000.0,
    fromm: "Champagne",
    vintage: 1995,
    bottle_size: ["6000"],
    annual_production: 30000,
    default_case_size: 6,
  },
  {
    id: 53,
    name: "Taittinger, Comtes de Champagne Blanc de Blancs",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Taittinger.png"],
    price: 2869.2,
    fromm: "Champagne",
    vintage: 1999,
    bottle_size: ["1500"],
    annual_production: 12000,
    default_case_size: 6,
  },
  {
    id: 54,
    name: "Tignanello, Toscana",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Tignanello.png"],
    price: 2250.0,
    fromm: "Italy",
    vintage: 2000,
    bottle_size: ["1500", "3000"],
    annual_production: 25000,
    default_case_size: 6,
  },
];
