export const vintex = [
  {
    id: 7,
    name: "Barolo Le Rocche del Falletto Riserva Bruno Giacosa",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_Falletto_1.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2016",
    price_range: "£1,300.00 - £4,225.00",
    maximum_price: 1490.0,
    fromm: "Italy",
    oldest_vintage: 2012,
    annual_production: 1000,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 3,
    name: "Bartolo Mascarello, Barolo",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_-_Wine_3.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2020",
    price_range: "£246.00 - £2,629.68",
    maximum_price: 390.0,
    fromm: "Italy",
    oldest_vintage: 2014,
    annual_production: 2000,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 77,
    name: "Bollinger 'James Bond 007' Millesime",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/jamesbond.png"],
    is_very_special: true,
    vintage_range: "2011",
    price_range: "£882.00",
    maximum_price: 147.0,
    fromm: "Champagne",
    oldest_vintage: 2011,
    annual_production: 6000,
    default_case_size: 6,
    grapes: "Champagne Blend",
  },
  {
    id: 4,
    name: "Bollinger, La Grande Annee",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/BollingerGrandeAnnee.png",
    ],
    is_very_special: false,
    vintage_range: "1995 - 2015",
    price_range: "£450.00 - £1,679.98",
    maximum_price: 450.0,
    fromm: "Champagne",
    oldest_vintage: 2007,
    annual_production: 15000,
    default_case_size: 6,
    grapes: "Chardonnay - Pinot Noir",
  },
  {
    id: 5,
    name: "Bollinger, R.D., Champagne",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Champagne_Bollinger_RD.png",
    ],
    is_very_special: false,
    vintage_range: "1990 - 2008",
    price_range: "£603.50 - £2,824.80",
    maximum_price: 375.0,
    fromm: "Champagne",
    oldest_vintage: 2004,
    annual_production: 8000,
    default_case_size: 6,
    grapes: "Chardonnay - Pinot Noir",
  },
  {
    id: 56,
    name: "Bollinger Vieilles Vignes Francaises",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Bollinger_Vignes.png",
    ],
    is_very_special: false,
    vintage_range: "2008",
    price_range: "£4,815.00",
    maximum_price: 1605.0,
    fromm: "Champagne",
    oldest_vintage: 2008,
    annual_production: 300,
    default_case_size: 3,
    grapes: "Pinot Noir",
  },
  {
    id: 66,
    name: "Bouchard Pere & Fils Montrachet",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/bouchard_G3SKiiN.png",
    ],
    is_very_special: false,
    vintage_range: "2018",
    price_range: "£2,909.00",
    maximum_price: 2909.0,
    fromm: "Burgundy",
    oldest_vintage: 2018,
    annual_production: 300,
    default_case_size: 6,
    grapes: "Chardonnay",
  },
  {
    id: 6,
    name: "Bruno Giacosa, Barolo, Falletto",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_Falletto_white.png",
    ],
    is_very_special: false,
    vintage_range: "1999 - 2020",
    price_range: "£500.00 - £2,388.46",
    maximum_price: 500.0,
    fromm: "Italy",
    oldest_vintage: 2014,
    annual_production: 2000,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 78,
    name: "Ceretto, Barolo, Brunate",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/barolo-brunate-docg-bio_11381_zoom.png",
    ],
    is_very_special: false,
    vintage_range: "2016",
    price_range: "£389.00",
    maximum_price: 389.0,
    fromm: "Italy",
    oldest_vintage: 2016,
    annual_production: 1200,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 8,
    name: "Chateau Angelus",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_Angelus_1.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£2,087.00 - £6,096.02",
    maximum_price: 190.16666666666666,
    fromm: "Bordeaux",
    oldest_vintage: 2017,
    annual_production: 9000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 9,
    name: "Chateau Ausone",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_Ausone.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£2,980.00 - £11,498.96",
    maximum_price: 1125.0,
    fromm: "Bordeaux",
    oldest_vintage: 2018,
    annual_production: 2500,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 79,
    name: "Chateau Berliquet Grand Cru Classe",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/20221007039_Chateau-Berliquet_Ch-Berliquet-St-Emilion_2022_01.png",
    ],
    is_very_special: false,
    vintage_range: "2018",
    price_range: "£145.00",
    maximum_price: 290.0,
    fromm: "Bordeaux",
    oldest_vintage: 2018,
    annual_production: 3000,
    default_case_size: 6,
    grapes: "Cabernet Franc - Merlot",
  },
  {
    id: 80,
    name: "Chateau Beychevelle",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/beychevelle-750.png",
    ],
    is_very_special: false,
    vintage_range: "2021",
    price_range: "£378.50",
    maximum_price: 378.5,
    fromm: "Bordeaux",
    oldest_vintage: 2021,
    annual_production: 25000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 10,
    name: "Chateau Cheval Blanc",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/chateau_Blanc.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2023",
    price_range: "£3,118.50 - £9,102.00",
    maximum_price: 1559.25,
    fromm: "Bordeaux",
    oldest_vintage: 2021,
    annual_production: 7000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 11,
    name: "Chateau d'Yquem Superieur, Sauternes",
    wine_images: [
      "https://millesimes.com/img/photo/66335.png",
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_d_yquem_1.png",
    ],
    is_very_special: false,
    vintage_range: "1986 - 2021",
    price_range: "£2,581.36 - £4,646.00",
    maximum_price: 215.16666666666666,
    fromm: "Bordeaux",
    oldest_vintage: 2020,
    annual_production: 10000,
    default_case_size: 12,
    grapes: "Sauvignon Blanc - Semillon",
  },
  {
    id: 64,
    name: "Chateau Figeac",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/figac-sm_vDl28FJ.png",
    ],
    is_very_special: false,
    vintage_range: "2020",
    price_range: "£707.00",
    maximum_price: 707.0,
    fromm: "Bordeaux",
    oldest_vintage: 2020,
    annual_production: 12000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 81,
    name: "Chateau Grand-Puy-Lacoste",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_Grand-Puy-Lacoste.png",
    ],
    is_very_special: false,
    vintage_range: "2010 - 2019",
    price_range: "£233.67 - £412.12",
    maximum_price: 233.67,
    fromm: "Bordeaux",
    oldest_vintage: 2019,
    annual_production: 13000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 82,
    name: "Chateau Haut-Bailly",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/20208037220_Chateau-Haut-Bailly_Pessac-Leognan_2019_01.png",
    ],
    is_very_special: false,
    vintage_range: "2020",
    price_range: "£384.50",
    maximum_price: 384.5,
    fromm: "Bordeaux",
    oldest_vintage: 2020,
    annual_production: 1,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 12,
    name: "Chateau Haut-Brion",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_Haut_Brion.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£2,904.00 - £7,978.86",
    maximum_price: 911.25,
    fromm: "Bordeaux",
    oldest_vintage: 2018,
    annual_production: 12000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 13,
    name: "Chateau Lafite Rothschild",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Lafite_Rothschild.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2022",
    price_range: "£4,157.00 - £9,600.00",
    maximum_price: 1575.0,
    fromm: "Bordeaux",
    oldest_vintage: 2010,
    annual_production: 20000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 14,
    name: "Chateau Lafleur, Pomerol",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/laFleur_Pomerol.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£4,082.00 - £22,802.68",
    maximum_price: 558.3333333333334,
    fromm: "Bordeaux",
    oldest_vintage: 2021,
    annual_production: 2000,
    default_case_size: 12,
    grapes: "Cabernet Franc - Merlot",
  },
  {
    id: 15,
    name: "Chateau Latour",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_Latour_1.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2017",
    price_range: "£3,900.00 - £9,448.24",
    maximum_price: 1062.5,
    fromm: "Bordeaux",
    oldest_vintage: 2014,
    annual_production: 18000,
    default_case_size: 12,
    grapes: "Cabernet Sauvignon - Merlot",
  },
  {
    id: 16,
    name: "Chateau Margaux",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_Margaux_1.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2022",
    price_range: "£3,303.34 - £8,646.62",
    maximum_price: 1391.5,
    fromm: "Bordeaux",
    oldest_vintage: 2022,
    annual_production: 13000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 17,
    name: "Chateau Mouton Rothschild",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Mouton_Rothschild.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£3,521.00 - £16,392.02",
    maximum_price: 1822.5,
    fromm: "Bordeaux",
    oldest_vintage: 2014,
    annual_production: 25000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 85,
    name: "Chateau Pichon Baron",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/20158008769_Chateau-Pichon-Longueville-Baron_Ch-Pichon-Longueville-BaronPauillac_2015_01.png",
    ],
    is_very_special: false,
    vintage_range: "2016",
    price_range: "£690.33",
    maximum_price: 690.33,
    fromm: "Bordeaux",
    oldest_vintage: 2016,
    annual_production: 20000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 87,
    name: "Chateau Troplong Mondot",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/2021-Chateau-Troplong-Mondot-750-ml_1_uVdgMgg.png",
    ],
    is_very_special: false,
    vintage_range: "2020",
    price_range: "£333.00",
    maximum_price: 333.0,
    fromm: "Bordeaux",
    oldest_vintage: 2020,
    annual_production: 10000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 18,
    name: "Clos de Tart, Clos de Tart Grand Cru",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Clos_De_Tart.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£3,988.00 - £8,123.88",
    maximum_price: 1673.65,
    fromm: "Burgundy",
    oldest_vintage: 2020,
    annual_production: 2000,
    default_case_size: 12,
    grapes: "Pinot Noir",
  },
  {
    id: 19,
    name: "Coche-Dury, Meursault",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Meursault_Coche_Dury.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£3,300.00 - £9,486.85",
    maximum_price: 12824.0,
    fromm: "Burgundy",
    oldest_vintage: 2015,
    annual_production: 4000,
    default_case_size: 6,
    grapes: "Chardonnay",
  },
  {
    id: 20,
    name: "Cos d'Estournel 2eme Cru Classe, Saint-Estephe",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Cos_D_estournel.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£794.00 - £2,830.48",
    maximum_price: 443.67,
    fromm: "Bordeaux",
    oldest_vintage: 2021,
    annual_production: 25000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 61,
    name: "Domaie Fontaine-Gagnard, Chassagne-Montrachet",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Fontaine-Gagnard.png",
    ],
    is_very_special: true,
    vintage_range: "1988",
    price_range: "£600.00",
    maximum_price: 100.0,
    fromm: "France",
    oldest_vintage: 1988,
    annual_production: 600,
    default_case_size: 6,
    grapes: "Chardonnay - Pinot Noir",
  },
  {
    id: 22,
    name: "Domaine Armand Rousseau, Chambertin",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/chambertin.png"],
    is_very_special: false,
    vintage_range: "1998 - 2021",
    price_range: "£11,045.00 - £25,750.00",
    maximum_price: 11045.0,
    fromm: "Burgundy",
    oldest_vintage: 2017,
    annual_production: 600,
    default_case_size: 6,
    grapes: "Pinot Noir",
  },
  {
    id: 23,
    name: "Domaine Bonneau du Martray, Charlemagne",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/20018119937_Bonneau-Du-Martray_Corton-Charlemagne-Grand-CruDomaine-Bonneau-du-Martray_2001_01.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£1,198.00 - £2,486.88",
    maximum_price: 1445.0,
    fromm: "Burgundy",
    oldest_vintage: 2018,
    annual_production: 2500,
    default_case_size: 6,
    grapes: "Chardonnay",
  },
  {
    id: 24,
    name: "Domaine Comte Georges de Vogue, Musigny",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/musigny.png"],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£2,905.87 - £6,109.00",
    maximum_price: 742.7216666666667,
    fromm: "Burgundy",
    oldest_vintage: 2014,
    annual_production: 1000,
    default_case_size: 6,
    grapes: "Pinot Noir",
  },
  {
    id: 31,
    name: "Domaine des Lambrays, Clos des Lambrays",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Clos_Des_Lambrays.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£1,028.00 - £2,400.00",
    maximum_price: 949.0,
    fromm: "Burgundy",
    oldest_vintage: 2019,
    annual_production: 2000,
    default_case_size: 6,
    grapes: "Pinot Noir",
  },
  {
    id: 32,
    name: "Domaine Georges Roumier Bonnes Mares",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Bonnes_Mares.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£5,184.00 - £14,106.17",
    maximum_price: 6312.0,
    fromm: "Burgundy",
    oldest_vintage: 2018,
    annual_production: 400,
    default_case_size: 6,
    grapes: "Pinot Noir",
  },
  {
    id: 33,
    name: "Domaine Leflaive, Chevalier-Montrachet",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chevalier_Montrachet_Domaine_Leflave.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£5,700.00 - £11,656.75",
    maximum_price: 1188.7166666666667,
    fromm: "Burgundy",
    oldest_vintage: 2019,
    annual_production: 400,
    default_case_size: 6,
    grapes: "Chardonnay",
  },
  {
    id: 34,
    name: "Dominus, Napa Valley",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Dominus_Napa_Valley.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£772.00 - £1,919.00",
    maximum_price: 772.0,
    fromm: "California",
    oldest_vintage: 2017,
    annual_production: 6000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 21,
    name: "Dom Perignon",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Dom_Perignon_2012.png",
    ],
    is_very_special: false,
    vintage_range: "1995 - 2015",
    price_range: "£711.00 - £2,100.00",
    maximum_price: 711.0,
    fromm: "Champagne",
    oldest_vintage: 2010,
    annual_production: 25000,
    default_case_size: 6,
    grapes: "Champagne Blend",
  },
  {
    id: 73,
    name: "DRC Assortment Case",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRCNewAssortment.png",
    ],
    is_very_special: false,
    vintage_range: "2016 - 2020",
    price_range: "£43,000.00 - £372,006.00",
    maximum_price: 7187.5,
    fromm: "Burgundy",
    oldest_vintage: 2016,
    annual_production: 1,
    default_case_size: 6,
    grapes: "Pinot Noir",
  },
  {
    id: 68,
    name: "DRC, Corton Grand Cru (Romanee)",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/romanee-conti-corton-2018.png",
    ],
    is_very_special: false,
    vintage_range: "2011",
    price_range: "£16,715.34",
    maximum_price: 2785.89,
    fromm: "Burgundy",
    oldest_vintage: 2011,
    annual_production: 800,
    default_case_size: 6,
    grapes: "Pinot Noir",
  },
  {
    id: 25,
    name: "DRC, Echezeaux Grand Cru (Romanee)",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Echezeaux.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£23,800.00 - £41,889.00",
    maximum_price: 7663.835,
    fromm: "Burgundy",
    oldest_vintage: 2017,
    annual_production: 1500,
    default_case_size: 12,
    grapes: "Pinot Noir",
  },
  {
    id: 26,
    name: "DRC, Grands Echezeaux Grand Cru (Romanee)",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Grands_Echezeaux.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£25,800.00 - £84,240.84",
    maximum_price: 6568.67,
    fromm: "Burgundy",
    oldest_vintage: 2021,
    annual_production: 1000,
    default_case_size: 12,
    grapes: "Pinot Noir",
  },
  {
    id: 27,
    name: "DRC, La Tache Grand Cru (Romanee)",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRCLaTacheGrandCruRedWine.png",
    ],
    is_very_special: false,
    vintage_range: "1994 - 2021",
    price_range: "£46,000.00 - £92,000.00",
    maximum_price: 5166.666666666667,
    fromm: "Burgundy",
    oldest_vintage: 2018,
    annual_production: 2000,
    default_case_size: 12,
    grapes: "Pinot Noir",
  },
  {
    id: 28,
    name: "DRC, Richebourg Grand Cru (Romanee)",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Richebourg.png",
    ],
    is_very_special: false,
    vintage_range: "1992 - 2021",
    price_range: "£22,344.00 - £61,600.00",
    maximum_price: 1862.0,
    fromm: "Burgundy",
    oldest_vintage: 1992,
    annual_production: 1200,
    default_case_size: 12,
    grapes: "Pinot Noir",
  },
  {
    id: 29,
    name: "DRC, Romanee-Conti Grand Cru",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Romanee_Conti.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£156,000.00 - £306,027.72",
    maximum_price: 14666.666666666666,
    fromm: "Burgundy",
    oldest_vintage: 2014,
    annual_production: 500,
    default_case_size: 12,
    grapes: "Pinot Noir",
  },
  {
    id: 30,
    name: "DRC, Romanee-Saint-Vivant Grand Cru",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Romanee_St_Vivant.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£13,500.00 - £22,800.00",
    maximum_price: 2842.0833333333335,
    fromm: "Burgundy",
    oldest_vintage: 2006,
    annual_production: 1800,
    default_case_size: 6,
    grapes: "Pinot Noir",
  },
  {
    id: 60,
    name: "Edivo, Navis Mysterium Undersea Amphora",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/edivo.png"],
    is_very_special: true,
    vintage_range: "2012",
    price_range: "£1,800.00",
    maximum_price: 300.0,
    fromm: "Croatia",
    oldest_vintage: 2012,
    annual_production: 700,
    default_case_size: 6,
    grapes: "Plavac Mali",
  },
  {
    id: 35,
    name: "Flaccianello della Pieve",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Flaccoanello_Della_Pieve.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£380.00 - £1,635.66",
    maximum_price: 380.0,
    fromm: "Italy",
    oldest_vintage: 2017,
    annual_production: 6000,
    default_case_size: 6,
    grapes: "Sangiovese",
  },
  {
    id: 36,
    name: "Gaja, Barbaresco",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/gaja.png"],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£703.00 - £2,890.56",
    maximum_price: 703.0,
    fromm: "Italy",
    oldest_vintage: 2017,
    annual_production: 4000,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 37,
    name: "Giacomo Conterno, Barolo, Monfortino Riserva",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_Monfortino.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£4,386.00 - £8,661.37",
    maximum_price: 2196.55,
    fromm: "Italy",
    oldest_vintage: 2013,
    annual_production: 800,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 55,
    name: "Giuseppe Rinaldi",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Rinaldi_Barolo.webp",
    ],
    is_very_special: false,
    vintage_range: "2015",
    price_range: "£1,605.00",
    maximum_price: 1605.0,
    fromm: "Italy",
    oldest_vintage: 2015,
    annual_production: 1500,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 38,
    name: "Harlan Estate, Napa Valley",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/HarlanEstate.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£2,150.00 - £4,100.00",
    maximum_price: 2675.0,
    fromm: "California",
    oldest_vintage: 2017,
    annual_production: 2000,
    default_case_size: 3,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 69,
    name: "Joseph Drouhin Clos de Vougeot",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/20138019123_Joseph-Drouhin_Clos-de-Vougeot_2013_01.png",
    ],
    is_very_special: true,
    vintage_range: "2018",
    price_range: "£600.00",
    maximum_price: 600.0,
    fromm: "Burgundy",
    oldest_vintage: 2018,
    annual_production: 2000,
    default_case_size: 6,
    grapes: "Pinot Noir",
  },
  {
    id: 39,
    name: "Joseph Drouhin, Montrachet Grand Cru, Marquis de Laguiche",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/JDMontrachet.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£3,000.00 - £5,159.51",
    maximum_price: 1600.0,
    fromm: "Burgundy",
    oldest_vintage: 2020,
    annual_production: 300,
    default_case_size: 6,
    grapes: "Chardonnay",
  },
  {
    id: 76,
    name: "Krug, Grande Cuvee 168eme Edition",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/10008055082_Champagne-Krug_Grande-Cuvee-168eme-Edition_0000_01.png",
    ],
    is_very_special: false,
    vintage_range: "0",
    price_range: "£943.00",
    maximum_price: 943.0,
    fromm: "Champagne",
    oldest_vintage: 0,
    annual_production: 25000,
    default_case_size: 6,
    grapes: "Champagne Blend",
  },
  {
    id: 40,
    name: "Krug, Vintage Brut",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/krug.png"],
    is_very_special: false,
    vintage_range: "1990 - 2011",
    price_range: "£1,200.00 - £4,620.00",
    maximum_price: 1288.33,
    fromm: "Champagne",
    oldest_vintage: 2004,
    annual_production: 15000,
    default_case_size: 6,
    grapes: "Champagne Blend",
  },
  {
    id: 58,
    name: "Leoville Las Cases",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Vin_De_Leoville.png",
    ],
    is_very_special: false,
    vintage_range: "2015 - 2020",
    price_range: "£810.00 - £812.50",
    maximum_price: 810.0,
    fromm: "Bordeaux",
    oldest_vintage: 2020,
    annual_production: 18000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 41,
    name: "Le Pin, Pomerol",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/LePin.png"],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£10,583.00 - £25,223.04",
    maximum_price: 2277.733333333333,
    fromm: "Bordeaux",
    oldest_vintage: 2021,
    annual_production: 500,
    default_case_size: 6,
    grapes: "Merlot",
  },
  {
    id: 59,
    name: "Louis Roederer, collection 243, champagne",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Louis_Roederer_244.png",
    ],
    is_very_special: true,
    vintage_range: "0",
    price_range: "£190.00",
    maximum_price: 190.0,
    fromm: "Champagne",
    oldest_vintage: 0,
    annual_production: 30000,
    default_case_size: 6,
    grapes: "Chardonnay - Pinot Noir",
  },
  {
    id: 42,
    name: "Louis Roederer, Cristal",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Louis_Roederer_Cristal.png",
    ],
    is_very_special: false,
    vintage_range: "1995 - 2015",
    price_range: "£848.00 - £30,000.00",
    maximum_price: 550.0,
    fromm: "Champagne",
    oldest_vintage: 2005,
    annual_production: 30000,
    default_case_size: 6,
    grapes: "Chardonnay - Pinot Noir",
  },
  {
    id: 43,
    name: "Masseto, Toscana",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Masetto.png"],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£1,635.00 - £4,326.71",
    maximum_price: 545.0,
    fromm: "Italy",
    oldest_vintage: 2021,
    annual_production: 4000,
    default_case_size: 3,
    grapes: "Merlot",
  },
  {
    id: 48,
    name: "Monte Bello, Ridge Vineyard",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Ridge_Monte_Bello.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£748.10 - £2,000.00",
    maximum_price: 405.0,
    fromm: "California",
    oldest_vintage: 2019,
    annual_production: 5000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 44,
    name: "Opus One, Napa Valley",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/OpusOne.png"],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£1,452.50 - £3,776.22",
    maximum_price: 1471.67,
    fromm: "California",
    oldest_vintage: 2021,
    annual_production: 30000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 45,
    name: "Ornellaia, Bolgheri",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Ornellaia.png"],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£750.00 - £1,836.04",
    maximum_price: 783.0,
    fromm: "Italy",
    oldest_vintage: 2017,
    annual_production: 14000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 46,
    name: "Petrus, Pomerol",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Petrus.png"],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£12,500.00 - £22,000.00",
    maximum_price: 2283.3333333333335,
    fromm: "Bordeaux",
    oldest_vintage: 2017,
    annual_production: 3000,
    default_case_size: 6,
    grapes: "Merlot",
  },
  {
    id: 47,
    name: "Pol Roger, Sir Winston Churchill",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Pol_Roger.png"],
    is_very_special: false,
    vintage_range: "1995 - 2015",
    price_range: "£745.60 - £2,520.00",
    maximum_price: 750.0,
    fromm: "Champagne",
    oldest_vintage: 2015,
    annual_production: 6000,
    default_case_size: 6,
    grapes: "Champagne Blend",
  },
  {
    id: 94,
    name: "Rare, Champagne",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/rare_champagne.png",
    ],
    is_very_special: false,
    vintage_range: "2008",
    price_range: "£526.66",
    maximum_price: 263.33,
    fromm: "Champagne",
    oldest_vintage: 2008,
    annual_production: 4000,
    default_case_size: 6,
    grapes: "Champagne Blend",
  },
  {
    id: 49,
    name: "Salon, Le Mesnil Grand Cru",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/salon.png"],
    is_very_special: false,
    vintage_range: "1995 - 2013",
    price_range: "£1,875.50 - £4,153.04",
    maximum_price: 1248.4383333333333,
    fromm: "Champagne",
    oldest_vintage: 1997,
    annual_production: 10000,
    default_case_size: 3,
    grapes: "Chardonnay",
  },
  {
    id: 50,
    name: "Sassicaia, Tenuta San Guido, Bolgheri",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/sassicaia.png"],
    is_very_special: false,
    vintage_range: "2000 - 2022",
    price_range: "£1,986.66 - £4,800.00",
    maximum_price: 993.33,
    fromm: "Italy",
    oldest_vintage: 2022,
    annual_production: 20000,
    default_case_size: 12,
    grapes: "Cabernet Franc - Cabernet Sauvignon",
  },
  {
    id: 75,
    name: "Scarecrow, Cabernet Sauvignon, Rutherford",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/2015Scarecrow_800x.png",
    ],
    is_very_special: false,
    vintage_range: "2019",
    price_range: "£1,555.00",
    maximum_price: 1555.0,
    fromm: "California",
    oldest_vintage: 2019,
    annual_production: 500,
    default_case_size: 3,
    grapes: "Cabernet Sauvignon",
  },
  {
    id: 51,
    name: "Screaming Eagle, Cabernet Sauvignon, Oakville",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Screaming_eagle.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£5,407.00 - £14,333.37",
    maximum_price: 5407.0,
    fromm: "California",
    oldest_vintage: 2020,
    annual_production: 750,
    default_case_size: 3,
    grapes: "Cabernet Sauvignon",
  },
  {
    id: 65,
    name: "Screaming Eagle 'The Flight'",
    wine_images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/ScreamingEagleSecondFlight.png",
    ],
    is_very_special: false,
    vintage_range: "2007 - 2019",
    price_range: "£1,912.00 - £2,459.13",
    maximum_price: 1912.0,
    fromm: "California",
    oldest_vintage: 2019,
    annual_production: 600,
    default_case_size: 3,
    grapes: "Cabernet Sauvignon",
  },
  {
    id: 52,
    name: "Solaia, Toscana",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Solaia.png"],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£1,135.50 - £2,235.91",
    maximum_price: 249.83333333333334,
    fromm: "Italy",
    oldest_vintage: 2013,
    annual_production: 8000,
    default_case_size: 6,
    grapes: "Cabernet - Sangiovese",
  },
  {
    id: 53,
    name: "Taittinger, Comtes de Champagne Blanc de Blancs",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Taittinger.png"],
    is_very_special: false,
    vintage_range: "1999 - 2021",
    price_range: "£453.42 - £2,869.20",
    maximum_price: 513.0,
    fromm: "Champagne",
    oldest_vintage: 2006,
    annual_production: 12000,
    default_case_size: 6,
    grapes: "Chardonnay",
  },
  {
    id: 54,
    name: "Tignanello, Toscana",
    wine_images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/Tignanello.png"],
    is_very_special: false,
    vintage_range: "2000 - 2022",
    price_range: "£571.67 - £3,150.00",
    maximum_price: 571.67,
    fromm: "Italy",
    oldest_vintage: 2022,
    annual_production: 25000,
    default_case_size: 6,
    grapes: "Cabernet - Sangiovese",
  },
];
