export const vintex = [
  {
    id: 77,
    name: "Bollinger 'James Bond 007' Millesime",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/jamesbond.png"],
    is_very_special: true,
    vintage_range: "2011",
    price_range: "£882.00",
    maximum_price: 147.0,
    fromm: "Champagne",
    oldest_vintage: 2011,
    annual_production: 6000,
    default_case_size: 6,
    grapes: "Champagne Blend",
  },
  {
    id: 4,
    name: "Bollinger, La Grande Annee",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/BollingerGrandeAnnee.png",
    ],
    is_very_special: false,
    vintage_range: "1995 - 2015",
    price_range: "£442.50 - £1,680.00",
    maximum_price: 715.02,
    fromm: "Champagne",
    oldest_vintage: 2002,
    annual_production: 15000,
    default_case_size: 6,
    grapes: "Chardonnay - Pinot Noir",
  },
  {
    id: 56,
    name: "Bollinger Vieilles Vignes Francaises",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Bollinger_Vignes.png",
    ],
    is_very_special: false,
    vintage_range: "2008",
    price_range: "£4,962.51",
    maximum_price: 1654.17,
    fromm: "Champagne",
    oldest_vintage: 2008,
    annual_production: 300,
    default_case_size: 3,
    grapes: "Pinot Noir",
  },
  {
    id: 66,
    name: "Bouchard Pere & Fils Montrachet",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/bouchard_G3SKiiN.png",
    ],
    is_very_special: false,
    vintage_range: "2018",
    price_range: "£2,711.88",
    maximum_price: 2711.88,
    fromm: "Burgundy",
    oldest_vintage: 2018,
    annual_production: 300,
    default_case_size: 6,
    grapes: "Chardonnay",
  },
  {
    id: 6,
    name: "Bruno Giacosa, Barolo, Falletto",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_Falletto_white.png",
    ],
    is_very_special: false,
    vintage_range: "1999 - 2020",
    price_range: "£480.00 - £2,569.44",
    maximum_price: 498.96,
    fromm: "Italy",
    oldest_vintage: 2017,
    annual_production: 2000,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 78,
    name: "Ceretto, Barolo, Brunate",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/barolo-brunate-docg-bio_11381_zoom.png",
    ],
    is_very_special: false,
    vintage_range: "2016",
    price_range: "£388.98",
    maximum_price: 388.98,
    fromm: "Italy",
    oldest_vintage: 2016,
    annual_production: 1200,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 79,
    name: "Chateau Berliquet Grand Cru Classe",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/20221007039_Chateau-Berliquet_Ch-Berliquet-St-Emilion_2022_01.png",
    ],
    is_very_special: false,
    vintage_range: "2018",
    price_range: "£110.00",
    maximum_price: 220.0,
    fromm: "Bordeaux",
    oldest_vintage: 2018,
    annual_production: 3000,
    default_case_size: 6,
    grapes: "Cabernet Franc - Merlot",
  },
  {
    id: 10,
    name: "Chateau Cheval Blanc",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/chateau_Blanc.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2023",
    price_range: "£3,110.04 - £8,700.00",
    maximum_price: 1887.0,
    fromm: "Bordeaux",
    oldest_vintage: 2020,
    annual_production: 7000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 11,
    name: "Chateau d'Yquem Superieur, Sauternes",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_d_yquem.png",
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_d_yquem_1.png",
    ],
    is_very_special: false,
    vintage_range: "1986 - 2021",
    price_range: "£2,516.64 - £4,643.04",
    maximum_price: 813.0,
    fromm: "Bordeaux",
    oldest_vintage: 2016,
    annual_production: 10000,
    default_case_size: 12,
    grapes: "Sauvignon Blanc - Semillon",
  },
  {
    id: 64,
    name: "Chateau Figeac",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/figac-sm_vDl28FJ.png",
    ],
    is_very_special: false,
    vintage_range: "2020",
    price_range: "£750.48",
    maximum_price: 750.48,
    fromm: "Bordeaux",
    oldest_vintage: 2020,
    annual_production: 12000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 13,
    name: "Chateau Lafite Rothschild",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Lafite_Rothschild.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2022",
    price_range: "£4,343.04 - £9,300.00",
    maximum_price: 1682.55,
    fromm: "Bordeaux",
    oldest_vintage: 2003,
    annual_production: 20000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 15,
    name: "Chateau Latour",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Chateau_Latour_1.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2017",
    price_range: "£3,800.04 - £8,799.96",
    maximum_price: 2119.98,
    fromm: "Bordeaux",
    oldest_vintage: 2012,
    annual_production: 18000,
    default_case_size: 12,
    grapes: "Cabernet Sauvignon - Merlot",
  },
  {
    id: 17,
    name: "Chateau Mouton Rothschild",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Mouton_Rothschild.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£3,583.32 - £14,400.00",
    maximum_price: 1801.68,
    fromm: "Bordeaux",
    oldest_vintage: 2021,
    annual_production: 25000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 85,
    name: "Chateau Pichon Baron",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/20158008769_Chateau-Pichon-Longueville-Baron_Ch-Pichon-Longueville-BaronPauillac_2015_01.png",
    ],
    is_very_special: false,
    vintage_range: "2016",
    price_range: "£670.02",
    maximum_price: 670.02,
    fromm: "Bordeaux",
    oldest_vintage: 2016,
    annual_production: 20000,
    default_case_size: 6,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 20,
    name: "Cos d'Estournel 2eme Cru Classe, Saint-Estephe",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Cos_D_estournel.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£860.04 - £2,139.72",
    maximum_price: 430.02,
    fromm: "Bordeaux",
    oldest_vintage: 2017,
    annual_production: 25000,
    default_case_size: 12,
    grapes: "Bordeaux Blend Red",
  },
  {
    id: 61,
    name: "Domaie Fontaine-Gagnard, Chassagne-Montrachet",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Fontaine-Gagnard.png",
    ],
    is_very_special: true,
    vintage_range: "1988",
    price_range: "£600.00",
    maximum_price: 100.0,
    fromm: "France",
    oldest_vintage: 1988,
    annual_production: 600,
    default_case_size: 6,
    grapes: "Chardonnay - Pinot Noir",
  },
  {
    id: 21,
    name: "Dom Perignon",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Dom_Perignon_2012.png",
    ],
    is_very_special: false,
    vintage_range: "1995 - 2015",
    price_range: "£706.50 - £1,800.00",
    maximum_price: 1000.44,
    fromm: "Champagne",
    oldest_vintage: 2013,
    annual_production: 25000,
    default_case_size: 6,
    grapes: "Champagne Blend",
  },
  {
    id: 68,
    name: "DRC, Corton Grand Cru (Romanee)",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/romanee-conti-corton-2018.png",
    ],
    is_very_special: false,
    vintage_range: "2011",
    price_range: "£16,199.16",
    maximum_price: 2699.86,
    fromm: "Burgundy",
    oldest_vintage: 2011,
    annual_production: 800,
    default_case_size: 6,
    grapes: "Pinot Noir",
  },
  {
    id: 28,
    name: "DRC, Richebourg Grand Cru (Romanee)",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Richebourg.png",
    ],
    is_very_special: false,
    vintage_range: "1992 - 2021",
    price_range: "£22,344.00 - £62,594.04",
    maximum_price: 1862.0,
    fromm: "Burgundy",
    oldest_vintage: 1992,
    annual_production: 1200,
    default_case_size: 12,
    grapes: "Pinot Noir",
  },
  {
    id: 29,
    name: "DRC, Romanee-Conti Grand Cru",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/DRC_Romanee_Conti.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£176,000.04 - £328,973.64",
    maximum_price: 15425.33,
    fromm: "Burgundy",
    oldest_vintage: 2017,
    annual_production: 500,
    default_case_size: 12,
    grapes: "Pinot Noir",
  },
  {
    id: 60,
    name: "Edivo, Navis Mysterium Undersea Amphora",
    images: ["https://d18vt6ndh4jzvp.cloudfront.net/media/edivo.png"],
    is_very_special: true,
    vintage_range: "2012",
    price_range: "£1,800.00",
    maximum_price: 300.0,
    fromm: "Croatia",
    oldest_vintage: 2012,
    annual_production: 700,
    default_case_size: 6,
    grapes: "Plavac Mali",
  },
  {
    id: 35,
    name: "Flaccianello della Pieve",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Flaccoanello_Della_Pieve.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£379.98 - £1,635.66",
    maximum_price: 379.98,
    fromm: "Italy",
    oldest_vintage: 2017,
    annual_production: 6000,
    default_case_size: 6,
    grapes: "Sangiovese",
  },
  {
    id: 37,
    name: "Giacomo Conterno, Barolo, Monfortino Riserva",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Barolo_Monfortino.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£3,985.74 - £7,617.30",
    maximum_price: 1992.87,
    fromm: "Italy",
    oldest_vintage: 2013,
    annual_production: 800,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 55,
    name: "Giuseppe Rinaldi",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/Rinaldi_Barolo.webp",
    ],
    is_very_special: false,
    vintage_range: "2015",
    price_range: "£1,489.98",
    maximum_price: 2979.96,
    fromm: "Italy",
    oldest_vintage: 2015,
    annual_production: 1500,
    default_case_size: 6,
    grapes: "Nebbiolo",
  },
  {
    id: 38,
    name: "Harlan Estate, Napa Valley",
    images: [
      "https://d18vt6ndh4jzvp.cloudfront.net/media/HarlanEstate.png",
    ],
    is_very_special: false,
    vintage_range: "2000 - 2021",
    price_range: "£2,150.00 - £3,900.00",
    maximum_price: 2390.5,
    fromm: "California",
    oldest_vintage: 2017,
    annual_production: 2000,
    default_case_size: 3,
    grapes: "Bordeaux Blend Red",
  },
];
